use alloc::boxed::Box;

use super::*;

pub(super) fn apply_integrated_command(
    graph: &mut SemanticGraph,
    command: SemanticCommand,
) -> ApplyDispatch {
    let applied = match command {
        SemanticCommand::RecordIntegratedSmpPreemptionCleanup {
            integrated,
            scenario,
            stress_run,
            stress_run_generation,
            preemption,
            preemption_generation,
            timer_interrupt,
            timer_interrupt_generation,
            saved_context,
            saved_context_generation,
            remote_preempt,
            remote_preempt_generation,
            activation_cleanup,
            activation_cleanup_generation,
            smp_cleanup_quiescence,
            smp_cleanup_quiescence_generation,
            invariant_checks,
            note,
        } => graph.record_integrated_smp_preemption_cleanup_with_id(
            integrated,
            &scenario,
            stress_run,
            stress_run_generation,
            preemption,
            preemption_generation,
            timer_interrupt,
            timer_interrupt_generation,
            saved_context,
            saved_context_generation,
            remote_preempt,
            remote_preempt_generation,
            activation_cleanup,
            activation_cleanup_generation,
            smp_cleanup_quiescence,
            smp_cleanup_quiescence_generation,
            invariant_checks,
            &note,
        ),
        SemanticCommand::RecordIntegratedSmpNetworkFault {
            integrated,
            scenario,
            network_driver_cleanup,
            network_driver_cleanup_generation,
            smp_stress_run,
            smp_stress_run_generation,
            remote_preempt,
            remote_preempt_generation,
            smp_cleanup_quiescence,
            smp_cleanup_quiescence_generation,
            invariant_checks,
            note,
        } => graph.record_integrated_smp_network_fault_with_id(
            integrated,
            &scenario,
            network_driver_cleanup,
            network_driver_cleanup_generation,
            smp_stress_run,
            smp_stress_run_generation,
            remote_preempt,
            remote_preempt_generation,
            smp_cleanup_quiescence,
            smp_cleanup_quiescence_generation,
            invariant_checks,
            &note,
        ),
        SemanticCommand::RecordIntegratedDiskPreemptFault {
            integrated,
            scenario,
            preemption,
            preemption_generation,
            block_pending_io_policy,
            block_pending_io_policy_generation,
            invariant_checks,
            note,
        } => graph.record_integrated_disk_preempt_fault_with_id(
            integrated,
            &scenario,
            preemption,
            preemption_generation,
            block_pending_io_policy,
            block_pending_io_policy_generation,
            invariant_checks,
            &note,
        ),
        SemanticCommand::RecordIntegratedSimdMigration {
            integrated,
            scenario,
            activation_migration,
            activation_migration_generation,
            invariant_checks,
            note,
        } => graph.record_integrated_simd_migration_with_id(
            integrated,
            &scenario,
            activation_migration,
            activation_migration_generation,
            invariant_checks,
            &note,
        ),
        SemanticCommand::RecordIntegratedNetworkDiskIo {
            integrated,
            scenario,
            network_benchmark,
            network_benchmark_generation,
            block_benchmark,
            block_benchmark_generation,
            invariant_checks,
            note,
        } => graph.record_integrated_network_disk_io_with_id(
            integrated,
            &scenario,
            network_benchmark,
            network_benchmark_generation,
            block_benchmark,
            block_benchmark_generation,
            invariant_checks,
            &note,
        ),
        SemanticCommand::RecordIntegratedDisplaySchedulerLoad {
            integrated,
            scenario,
            framebuffer_benchmark,
            framebuffer_benchmark_generation,
            scheduler_decision,
            scheduler_decision_generation,
            invariant_checks,
            note,
        } => graph.record_integrated_display_scheduler_load_with_id(
            integrated,
            &scenario,
            framebuffer_benchmark,
            framebuffer_benchmark_generation,
            scheduler_decision,
            scheduler_decision_generation,
            invariant_checks,
            &note,
        ),
        SemanticCommand::RecordIntegratedSnapshotIoLeaseBarrier {
            integrated,
            scenario,
            smp_snapshot_barrier,
            smp_snapshot_barrier_generation,
            io_cleanup,
            io_cleanup_generation,
            display_snapshot_barrier,
            display_snapshot_barrier_generation,
            invariant_checks,
            note,
        } => graph.record_integrated_snapshot_io_lease_barrier_with_id(
            integrated,
            &scenario,
            smp_snapshot_barrier,
            smp_snapshot_barrier_generation,
            io_cleanup,
            io_cleanup_generation,
            display_snapshot_barrier,
            display_snapshot_barrier_generation,
            invariant_checks,
            &note,
        ),
        SemanticCommand::RecordIntegratedCodePublishSmpWorkload {
            integrated,
            scenario,
            smp_stress_run,
            smp_stress_run_generation,
            smp_code_publish_barrier,
            smp_code_publish_barrier_generation,
            invariant_checks,
            note,
        } => graph.record_integrated_code_publish_smp_workload_with_id(
            integrated,
            &scenario,
            smp_stress_run,
            smp_stress_run_generation,
            smp_code_publish_barrier,
            smp_code_publish_barrier_generation,
            invariant_checks,
            &note,
        ),
        SemanticCommand::RecordIntegratedDisplayPanic {
            integrated,
            scenario,
            substrate_panic_event,
            display_panic_last_frame,
            display_panic_last_frame_generation,
            panic_ring_bytes,
            panic_record_max_bytes,
            panic_ring_oldest_seq,
            panic_ring_newest_seq,
            panic_ring_record_count,
            panic_ring_lost_count,
            jsonl_frame_count,
            contract_panic_summary_records,
            last_frame_summary_records,
            corrupt_record_count,
            truncated_record_count,
            invariant_checks,
            note,
        } => graph.record_integrated_display_panic_with_id(
            integrated,
            &scenario,
            substrate_panic_event,
            display_panic_last_frame,
            display_panic_last_frame_generation,
            panic_ring_bytes,
            panic_record_max_bytes,
            panic_ring_oldest_seq,
            panic_ring_newest_seq,
            panic_ring_record_count,
            panic_ring_lost_count,
            jsonl_frame_count,
            contract_panic_summary_records,
            last_frame_summary_records,
            corrupt_record_count,
            truncated_record_count,
            invariant_checks,
            &note,
        ),
        SemanticCommand::RecordIntegratedOsctlTraceReplay {
            integrated,
            scenario,
            integrated_smp_preemption_cleanup,
            integrated_smp_preemption_cleanup_generation,
            integrated_smp_network_fault,
            integrated_smp_network_fault_generation,
            integrated_disk_preempt_fault,
            integrated_disk_preempt_fault_generation,
            integrated_simd_migration,
            integrated_simd_migration_generation,
            integrated_network_disk_io,
            integrated_network_disk_io_generation,
            integrated_display_scheduler_load,
            integrated_display_scheduler_load_generation,
            integrated_snapshot_io_lease_barrier,
            integrated_snapshot_io_lease_barrier_generation,
            integrated_code_publish_smp_workload,
            integrated_code_publish_smp_workload_generation,
            integrated_display_panic,
            integrated_display_panic_generation,
            replay_event_cursor,
            stable_view_count,
            historical_edge_count,
            replayed_root_count,
            integrated_scenario_count,
            replay_fixture_count,
            invariant_checks,
            note,
        } => graph.record_integrated_osctl_trace_replay_with_id(
            integrated,
            &scenario,
            integrated_smp_preemption_cleanup,
            integrated_smp_preemption_cleanup_generation,
            integrated_smp_network_fault,
            integrated_smp_network_fault_generation,
            integrated_disk_preempt_fault,
            integrated_disk_preempt_fault_generation,
            integrated_simd_migration,
            integrated_simd_migration_generation,
            integrated_network_disk_io,
            integrated_network_disk_io_generation,
            integrated_display_scheduler_load,
            integrated_display_scheduler_load_generation,
            integrated_snapshot_io_lease_barrier,
            integrated_snapshot_io_lease_barrier_generation,
            integrated_code_publish_smp_workload,
            integrated_code_publish_smp_workload_generation,
            integrated_display_panic,
            integrated_display_panic_generation,
            replay_event_cursor,
            stable_view_count,
            historical_edge_count,
            replayed_root_count,
            integrated_scenario_count,
            replay_fixture_count,
            invariant_checks,
            &note,
        ),
        other => return ApplyDispatch::Next(Box::new(other)),
    };
    ApplyDispatch::Applied(applied)
}
