use alloc::boxed::Box;

use super::*;

pub(super) fn apply_scheduler_command(
    graph: &mut SemanticGraph,
    command: SemanticCommand,
) -> ApplyDispatch {
    let applied = match command {
        SemanticCommand::RegisterHart { hart, hardware_id, label, boot, note } => {
            graph.register_hart_with_id(hart, hardware_id, &label, boot, &note)
        }
        SemanticCommand::SetHartState { hart, hart_generation, state, reason, note } => {
            graph.set_hart_state(hart, hart_generation, state, &reason, &note)
        }
        SemanticCommand::BindHartCurrentActivation {
            hart,
            hart_generation,
            activation,
            activation_generation,
            note,
        } => graph.bind_hart_current_activation(
            hart,
            hart_generation,
            activation,
            activation_generation,
            &note,
        ),
        SemanticCommand::ClearHartCurrentActivation {
            hart,
            hart_generation,
            activation,
            activation_generation,
            reason,
            note,
        } => graph.clear_hart_current_activation(
            hart,
            hart_generation,
            activation,
            activation_generation,
            &reason,
            &note,
        ),
        SemanticCommand::CreateRuntimeActivation {
            activation,
            owner_task,
            owner_task_generation,
            owner_store,
            owner_store_generation,
            code_object,
        } => graph.create_runtime_activation_with_id(
            activation,
            owner_task,
            owner_task_generation,
            owner_store,
            owner_store_generation,
            code_object,
        ),
        SemanticCommand::CreateRunnableQueue { queue, label } => {
            graph.create_runnable_queue_with_id(queue, &label)
        }
        SemanticCommand::BindRunnableQueueOwner {
            queue,
            queue_generation,
            hart,
            hart_generation,
            note,
        } => graph.bind_runnable_queue_owner(queue, queue_generation, hart, hart_generation, &note),
        SemanticCommand::EnqueueRunnable { queue, activation, activation_generation } => {
            graph.enqueue_runnable_activation(queue, activation, activation_generation)
        }
        SemanticCommand::DequeueRunnable { queue, activation } => {
            graph.dequeue_runnable_activation(queue, activation)
        }
        SemanticCommand::CreateActivationContext { context, activation, activation_generation } => {
            graph.create_activation_context_with_id(context, activation, activation_generation)
        }
        SemanticCommand::UpdateActivationContextVectorState {
            context,
            context_generation,
            vector_state,
            vector_status,
            note,
        } => graph.update_activation_context_vector_state(
            context,
            context_generation,
            vector_state,
            vector_status,
            &note,
        ),
        SemanticCommand::EnableLazyVectorState {
            context,
            context_generation,
            vector_state,
            note,
        } => graph.enable_lazy_vector_state(context, context_generation, vector_state, &note),
        SemanticCommand::CaptureSavedContext {
            saved_context,
            context,
            context_generation,
            reason,
            pc,
            sp,
            flags,
            note,
        } => graph.capture_saved_context_with_id(
            saved_context,
            context,
            context_generation,
            reason,
            pc,
            sp,
            flags,
            &note,
        ),
        SemanticCommand::SavePreemptedContext {
            context,
            saved_context,
            preemption,
            preemption_generation,
            pc,
            sp,
            flags,
            note,
        } => graph.save_preempted_context_with_ids(
            context,
            saved_context,
            preemption,
            preemption_generation,
            pc,
            sp,
            flags,
            &note,
        ),
        SemanticCommand::SaveDirtyVectorStateOnPreempt {
            context,
            context_generation,
            saved_context,
            saved_context_generation,
            preemption,
            preemption_generation,
            vector_state,
            note,
        } => graph.save_dirty_vector_state_on_preempt(
            context,
            context_generation,
            saved_context,
            saved_context_generation,
            preemption,
            preemption_generation,
            vector_state,
            &note,
        ),
        SemanticCommand::RecordTimerInterrupt {
            interrupt,
            timer_epoch,
            hart,
            hart_generation,
            target_activation,
            target_activation_generation,
            note,
        } => graph.record_timer_interrupt_with_id(
            interrupt,
            timer_epoch,
            hart,
            hart_generation,
            target_activation,
            target_activation_generation,
            &note,
        ),
        SemanticCommand::RecordIpiEvent {
            ipi,
            source_hart,
            source_hart_generation,
            target_hart,
            target_hart_generation,
            kind,
            reason,
            note,
        } => graph.record_ipi_event_with_id(
            ipi,
            source_hart,
            source_hart_generation,
            target_hart,
            target_hart_generation,
            kind,
            &reason,
            &note,
        ),
        SemanticCommand::RemotePreemptActivation {
            remote_preempt,
            ipi,
            ipi_generation,
            source_hart,
            source_hart_generation,
            target_hart,
            target_hart_generation,
            activation,
            activation_generation,
            queue,
            note,
        } => graph.remote_preempt_activation_with_id(
            remote_preempt,
            ipi,
            ipi_generation,
            source_hart,
            source_hart_generation,
            target_hart,
            target_hart_generation,
            activation,
            activation_generation,
            queue,
            &note,
        ),
        SemanticCommand::RemoteParkHart {
            remote_park,
            ipi,
            ipi_generation,
            source_hart,
            source_hart_generation,
            target_hart,
            target_hart_generation,
            reason,
            note,
        } => graph.remote_park_hart_with_id(
            remote_park,
            ipi,
            ipi_generation,
            source_hart,
            source_hart_generation,
            target_hart,
            target_hart_generation,
            &reason,
            &note,
        ),
        SemanticCommand::PreemptActivation {
            preemption,
            activation,
            activation_generation,
            timer_interrupt,
            timer_interrupt_generation,
            queue,
            note,
        } => graph.preempt_running_activation_with_id(
            preemption,
            activation,
            activation_generation,
            timer_interrupt,
            timer_interrupt_generation,
            queue,
            &note,
        ),
        SemanticCommand::RecordSchedulerDecision {
            decision,
            queue,
            queue_generation,
            selected_activation,
            selected_activation_generation,
            reason,
            note,
        } => graph.record_scheduler_decision_with_id(
            decision,
            queue,
            queue_generation,
            selected_activation,
            selected_activation_generation,
            &reason,
            &note,
        ),
        SemanticCommand::RecordCrossHartSchedulerDecision {
            cross_decision,
            scheduler_decision,
            scheduler_decision_generation,
            deciding_hart,
            deciding_hart_generation,
            target_hart,
            target_hart_generation,
            reason,
            note,
        } => graph.record_cross_hart_scheduler_decision_with_id(
            cross_decision,
            scheduler_decision,
            scheduler_decision_generation,
            deciding_hart,
            deciding_hart_generation,
            target_hart,
            target_hart_generation,
            &reason,
            &note,
        ),
        SemanticCommand::MigrateRunnableActivation {
            migration,
            activation,
            activation_generation,
            source_queue,
            source_queue_generation,
            target_queue,
            target_queue_generation,
            source_hart,
            source_hart_generation,
            target_hart,
            target_hart_generation,
            reason,
            note,
        } => graph.migrate_runnable_activation_with_id(
            migration,
            activation,
            activation_generation,
            source_queue,
            source_queue_generation,
            target_queue,
            target_queue_generation,
            source_hart,
            source_hart_generation,
            target_hart,
            target_hart_generation,
            &reason,
            &note,
        ),
        SemanticCommand::RecordSmpSafePoint {
            safe_point,
            coordinator_hart,
            coordinator_hart_generation,
            participants,
            reason,
            note,
        } => graph.record_smp_safe_point_with_id(
            safe_point,
            coordinator_hart,
            coordinator_hart_generation,
            participants,
            &reason,
            &note,
        ),
        SemanticCommand::CompleteStopTheWorldRendezvous {
            rendezvous,
            epoch,
            safe_point,
            safe_point_generation,
            stop_new_activations,
            reason,
            note,
        } => graph.complete_stop_the_world_rendezvous_with_id(
            rendezvous,
            epoch,
            safe_point,
            safe_point_generation,
            stop_new_activations,
            &reason,
            &note,
        ),
        SemanticCommand::ValidateSmpCodePublishBarrier {
            barrier,
            rendezvous,
            rendezvous_generation,
            code_publish_epoch_before,
            code_publish_epoch_after,
            remote_icache_sync_required,
            code_publish_executed,
            reason,
            note,
        } => graph.validate_smp_code_publish_barrier_with_id(
            barrier,
            rendezvous,
            rendezvous_generation,
            code_publish_epoch_before,
            code_publish_epoch_after,
            remote_icache_sync_required,
            code_publish_executed,
            &reason,
            &note,
        ),
        SemanticCommand::ValidateSmpCleanupQuiescence {
            quiescence,
            cleanup,
            cleanup_generation,
            rendezvous,
            rendezvous_generation,
            store,
            target_store_generation,
            result_store_generation,
            reason,
            note,
        } => graph.validate_smp_cleanup_quiescence_with_id(
            quiescence,
            cleanup,
            cleanup_generation,
            rendezvous,
            rendezvous_generation,
            store,
            target_store_generation,
            result_store_generation,
            &reason,
            &note,
        ),
        SemanticCommand::ValidateSmpSnapshotBarrier {
            barrier,
            rendezvous,
            rendezvous_generation,
            snapshot_state,
            reason,
            note,
        } => graph.validate_smp_snapshot_barrier_with_id(
            barrier,
            rendezvous,
            rendezvous_generation,
            snapshot_state,
            &reason,
            &note,
        ),
        SemanticCommand::RecordSmpStressRun {
            run,
            scenario,
            iterations,
            invariant_checks,
            reason,
            note,
        } => graph.record_smp_stress_run_with_id(
            run,
            &scenario,
            iterations,
            invariant_checks,
            &reason,
            &note,
        ),
        SemanticCommand::RecordSmpScalingBenchmark {
            benchmark,
            scenario,
            stress_run,
            stress_run_generation,
            workload_units,
            baseline_single_hart_nanos,
            measured_smp_nanos,
            budget_nanos,
            note,
        } => graph.record_smp_scaling_benchmark_with_id(
            benchmark,
            &scenario,
            stress_run,
            stress_run_generation,
            workload_units,
            baseline_single_hart_nanos,
            measured_smp_nanos,
            budget_nanos,
            &note,
        ),
        other => return ApplyDispatch::Next(Box::new(other)),
    };
    ApplyDispatch::Applied(applied)
}
