use serde::{Deserialize, Serialize};

use crate::target_runtime::ContractObjectRefManifest;

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct TargetFeatureSetManifest {
    pub id: u64,
    pub name: String,
    pub discovery_source: String,
    pub target_profile: String,
    pub target_arch: String,
    pub base_isa: String,
    pub simd_abi: String,
    pub simd_supported: bool,
    pub vector_register_count: u16,
    pub vector_register_bits: u16,
    pub scalar_fallback: bool,
    pub unsupported_reason: String,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct VectorStateManifest {
    pub id: u64,
    pub owner_activation: ContractObjectRefManifest,
    pub owner_store: ContractObjectRefManifest,
    pub code_object: ContractObjectRefManifest,
    pub target_feature_set: ContractObjectRefManifest,
    pub simd_abi: String,
    pub vector_register_count: u16,
    pub vector_register_bits: u16,
    pub register_bytes: u32,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct SimdFaultInjectionManifest {
    pub id: u64,
    pub activation: ContractObjectRefManifest,
    pub code_object: ContractObjectRefManifest,
    pub trap: ContractObjectRefManifest,
    pub target_feature_set: ContractObjectRefManifest,
    pub vector_state: Option<ContractObjectRefManifest>,
    pub kind: String,
    pub effect: String,
    pub required_abi: String,
    pub vector_register_count: u16,
    pub vector_register_bits: u16,
    pub injected_faults: u32,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct SimdBenchmarkManifest {
    pub id: u64,
    pub target_feature_set: ContractObjectRefManifest,
    pub scalar_code_object: ContractObjectRefManifest,
    pub vector_code_object: ContractObjectRefManifest,
    pub simd_abi: String,
    pub vector_register_count: u16,
    pub vector_register_bits: u16,
    pub workload_units: u64,
    pub scalar_nanos: u64,
    pub vector_nanos: u64,
    pub speedup_milli: u64,
    pub context_overhead_nanos: u64,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct SimdContextSwitchBenchmarkManifest {
    pub id: u64,
    pub preemption: ContractObjectRefManifest,
    pub activation_resume: ContractObjectRefManifest,
    pub saved_vector_state: ContractObjectRefManifest,
    pub restored_vector_state: ContractObjectRefManifest,
    pub target_feature_set: ContractObjectRefManifest,
    pub simd_abi: String,
    pub vector_register_count: u16,
    pub vector_register_bits: u16,
    pub sample_count: u64,
    pub scalar_context_switch_nanos: u64,
    pub vector_context_switch_nanos: u64,
    pub overhead_nanos: u64,
    pub budget_nanos: u64,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FramebufferObjectManifest {
    pub id: u64,
    pub name: String,
    pub resource: u64,
    pub resource_generation: u64,
    pub width: u32,
    pub height: u32,
    pub stride_bytes: u32,
    pub pixel_format: String,
    pub byte_len: u64,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DisplayObjectManifest {
    pub id: u64,
    pub name: String,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub mode_name: String,
    pub width: u32,
    pub height: u32,
    pub refresh_millihz: u32,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DisplayCapabilityManifest {
    pub id: u64,
    pub owner_store: u64,
    pub owner_store_generation: u64,
    pub display: u64,
    pub display_generation: u64,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub capability: u64,
    pub capability_generation: u64,
    pub handle_slot: u32,
    pub handle_generation: u32,
    pub handle_tag: u64,
    pub operations: Vec<String>,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FramebufferWindowLeaseManifest {
    pub id: u64,
    pub owner_store: u64,
    pub owner_store_generation: u64,
    pub display_capability: u64,
    pub display_capability_generation: u64,
    pub display: u64,
    pub display_generation: u64,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub x: u32,
    pub y: u32,
    pub width: u32,
    pub height: u32,
    pub byte_offset: u64,
    pub byte_len: u64,
    pub access: String,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FramebufferMappingManifest {
    pub id: u64,
    pub owner_store: u64,
    pub owner_store_generation: u64,
    pub framebuffer_window_lease: u64,
    pub framebuffer_window_lease_generation: u64,
    pub display_capability: u64,
    pub display_capability_generation: u64,
    pub display: u64,
    pub display_generation: u64,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub map_handle_slot: u32,
    pub map_handle_generation: u32,
    pub map_handle_tag: u64,
    pub x: u32,
    pub y: u32,
    pub width: u32,
    pub height: u32,
    pub byte_offset: u64,
    pub byte_len: u64,
    pub access: String,
    pub mode: String,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FramebufferWriteManifest {
    pub id: u64,
    pub owner_store: u64,
    pub owner_store_generation: u64,
    pub framebuffer_mapping: u64,
    pub framebuffer_mapping_generation: u64,
    pub framebuffer_window_lease: u64,
    pub framebuffer_window_lease_generation: u64,
    pub display_capability: u64,
    pub display_capability_generation: u64,
    pub display: u64,
    pub display_generation: u64,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub map_handle_slot: u32,
    pub map_handle_generation: u32,
    pub map_handle_tag: u64,
    pub x: u32,
    pub y: u32,
    pub width: u32,
    pub height: u32,
    pub byte_offset: u64,
    pub byte_len: u64,
    pub pixel_format: String,
    pub payload_digest: u64,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FramebufferFlushRegionManifest {
    pub id: u64,
    pub owner_store: u64,
    pub owner_store_generation: u64,
    pub framebuffer_write: u64,
    pub framebuffer_write_generation: u64,
    pub display_capability: u64,
    pub display_capability_generation: u64,
    pub display: u64,
    pub display_generation: u64,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub x: u32,
    pub y: u32,
    pub width: u32,
    pub height: u32,
    pub byte_offset: u64,
    pub byte_len: u64,
    pub pixel_format: String,
    pub payload_digest: u64,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FramebufferDirtyRegionManifest {
    pub id: u64,
    pub owner_store: u64,
    pub owner_store_generation: u64,
    pub framebuffer_write: u64,
    pub framebuffer_write_generation: u64,
    pub framebuffer_flush_region: Option<u64>,
    pub framebuffer_flush_region_generation: Option<u64>,
    pub display_capability: u64,
    pub display_capability_generation: u64,
    pub display: u64,
    pub display_generation: u64,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub x: u32,
    pub y: u32,
    pub width: u32,
    pub height: u32,
    pub byte_offset: u64,
    pub byte_len: u64,
    pub pixel_format: String,
    pub payload_digest: u64,
    pub generation: u64,
    pub state: String,
    pub dirty_at_event: u64,
    pub cleaned_at_event: Option<u64>,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DisplayEventLogManifest {
    pub id: u64,
    pub owner_store: u64,
    pub owner_store_generation: u64,
    pub display_capability: u64,
    pub display_capability_generation: u64,
    pub display: u64,
    pub display_generation: u64,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub framebuffer_dirty_region: u64,
    pub framebuffer_dirty_region_generation: u64,
    pub first_event: u64,
    pub last_event: u64,
    pub event_count: u64,
    pub flush_count: u64,
    pub dirty_region_count: u64,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DisplayCleanupStepManifest {
    pub kind: String,
    pub target: ContractObjectRefManifest,
    pub observed_generation: u64,
    pub status: String,
    pub event: Option<u64>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DisplayCleanupManifest {
    pub id: u64,
    pub owner_store: u64,
    pub owner_store_generation: u64,
    pub display_capability: u64,
    pub display_capability_generation: u64,
    pub display: u64,
    pub display_generation: u64,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub generation: u64,
    pub state: String,
    pub reason: String,
    pub started_at_event: u64,
    pub completed_at_event: u64,
    pub unmapped_framebuffer_mappings: Vec<ContractObjectRefManifest>,
    pub released_framebuffer_window_leases: Vec<ContractObjectRefManifest>,
    pub revoked_display_capabilities: Vec<ContractObjectRefManifest>,
    pub revoked_capabilities: Vec<ContractObjectRefManifest>,
    pub steps: Vec<DisplayCleanupStepManifest>,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DisplaySnapshotBarrierManifest {
    pub id: u64,
    pub owner_store: u64,
    pub owner_store_generation: u64,
    pub display: u64,
    pub display_generation: u64,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub display_cleanup: Option<u64>,
    pub display_cleanup_generation: Option<u64>,
    pub active_framebuffer_window_lease_count: u32,
    pub active_framebuffer_mapping_count: u32,
    pub dirty_framebuffer_region_count: u32,
    pub snapshot_validation_ok: bool,
    pub generation: u64,
    pub state: String,
    pub validated_at_event: u64,
    pub reason: String,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct DisplayPanicLastFrameManifest {
    pub id: u64,
    pub owner_store: u64,
    pub owner_store_generation: u64,
    pub display: u64,
    pub display_generation: u64,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub display_snapshot_barrier: u64,
    pub display_snapshot_barrier_generation: u64,
    pub display_event_log: u64,
    pub display_event_log_generation: u64,
    pub framebuffer_write: u64,
    pub framebuffer_write_generation: u64,
    pub framebuffer_flush_region: u64,
    pub framebuffer_flush_region_generation: u64,
    pub x: u32,
    pub y: u32,
    pub width: u32,
    pub height: u32,
    pub byte_offset: u64,
    pub byte_len: u64,
    pub pixel_format: String,
    pub payload_digest: u64,
    pub summary_digest: u64,
    pub summary_record_bytes: u32,
    pub panic_epoch: u64,
    pub panic_cpu: u32,
    pub panic_reason_code: u32,
    pub panic_record_kind: String,
    pub raw_framebuffer_bytes_exported: bool,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FramebufferBenchmarkManifest {
    pub id: u64,
    pub scenario: String,
    pub owner_store: u64,
    pub owner_store_generation: u64,
    pub display: u64,
    pub display_generation: u64,
    pub framebuffer: u64,
    pub framebuffer_generation: u64,
    pub display_capability: u64,
    pub display_capability_generation: u64,
    pub framebuffer_write: u64,
    pub framebuffer_write_generation: u64,
    pub framebuffer_flush_region: u64,
    pub framebuffer_flush_region_generation: u64,
    pub display_event_log: u64,
    pub display_event_log_generation: u64,
    pub display_snapshot_barrier: u64,
    pub display_snapshot_barrier_generation: u64,
    pub sample_frames: u32,
    pub sample_bytes: u64,
    pub frame_area_pixels: u64,
    pub write_nanos: u64,
    pub flush_nanos: u64,
    pub measured_nanos: u64,
    pub budget_nanos: u64,
    pub throughput_bytes_per_sec: u64,
    pub flushes_per_sec_milli: u64,
    pub p50_latency_nanos: u64,
    pub p99_latency_nanos: u64,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct ActivationResumeManifest {
    pub id: u64,
    pub scheduler_decision: u64,
    pub scheduler_decision_generation: u64,
    pub activation: u64,
    pub activation_generation_before: u64,
    pub activation_generation_after: u64,
    pub owner_task: u64,
    pub owner_task_generation: u64,
    pub queue: u64,
    pub queue_generation: u64,
    pub context: Option<u64>,
    #[serde(default)]
    pub context_generation_before: Option<u64>,
    #[serde(default)]
    pub context_generation_after: Option<u64>,
    pub saved_context: Option<u64>,
    #[serde(default)]
    pub saved_context_generation: Option<u64>,
    #[serde(default)]
    pub saved_vector_state: Option<ContractObjectRefManifest>,
    #[serde(default)]
    pub restored_vector_state: Option<ContractObjectRefManifest>,
    #[serde(default)]
    pub vector_status: String,
    #[serde(default)]
    pub vector_restored_at_event: Option<u64>,
    pub generation: u64,
    pub state: String,
    pub resumed_at_event: u64,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct ActivationWaitManifest {
    pub id: u64,
    pub activation: u64,
    pub activation_generation_before: u64,
    pub activation_generation_after_block: u64,
    #[serde(default)]
    pub activation_generation_after_cancel: Option<u64>,
    pub wait: u64,
    pub wait_generation: u64,
    pub owner_task: u64,
    pub owner_task_generation: u64,
    pub queue: Option<u64>,
    #[serde(default)]
    pub queue_generation: Option<u64>,
    pub generation: u64,
    pub state: String,
    pub blocked_at_event: u64,
    #[serde(default)]
    pub completed_at_event: Option<u64>,
    #[serde(default)]
    pub cancel_reason: Option<String>,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct ActivationCleanupManifest {
    pub id: u64,
    pub store: u64,
    pub target_store_generation: u64,
    pub result_store_generation: u64,
    pub activation: u64,
    pub activation_generation_before: u64,
    pub activation_generation_after: u64,
    pub wait: Option<u64>,
    #[serde(default)]
    pub wait_generation: Option<u64>,
    pub owner_task: u64,
    pub owner_task_generation_before: u64,
    pub owner_task_generation_after: u64,
    pub generation: u64,
    pub state: String,
    pub reason: String,
    pub started_at_event: u64,
    pub completed_at_event: u64,
    #[serde(default)]
    pub steps: Vec<ActivationCleanupStepManifest>,
    pub note: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct ActivationCleanupStepManifest {
    pub kind: String,
    pub target: ContractObjectRefManifest,
    pub observed_generation: u64,
    pub status: String,
    #[serde(default)]
    pub event: Option<u64>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct PreemptionLatencySampleManifest {
    pub id: u64,
    pub timer_interrupt: u64,
    pub timer_interrupt_generation: u64,
    pub preemption: u64,
    pub preemption_generation: u64,
    pub scheduler_decision: u64,
    pub scheduler_decision_generation: u64,
    pub activation_resume: u64,
    pub activation_resume_generation: u64,
    pub activation: u64,
    pub activation_generation_before: u64,
    pub activation_generation_after: u64,
    pub queue: u64,
    pub queue_generation: u64,
    pub interrupt_recorded_at_event: u64,
    pub preempted_at_event: u64,
    pub decided_at_event: u64,
    pub resumed_at_event: u64,
    pub interrupt_to_preempt_events: u64,
    pub preempt_to_decision_events: u64,
    pub decision_to_resume_events: u64,
    pub interrupt_to_resume_events: u64,
    pub measured_nanos: u64,
    pub budget_nanos: u64,
    pub generation: u64,
    pub state: String,
    pub recorded_at_event: u64,
    pub note: String,
}
