[package]
license.workspace = true
name = "visa-wanco-carrier"
version = "0.1.0"
publish = false
edition = "2024"

[dependencies]
contract_core = { path = "../../core/contract_core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
substrate_api = { path = "../../backend/substrate_api" }
substrate_host = { path = "../../backend/substrate_host" }
visa_component_adapter = { path = "../visa_component_adapter" }
visa_profile = { path = "../../core/visa_profile" }
visa-regular-file-observation = { path = "../../testing/visa-regular-file-observation" }
visa_runtime = { path = "../visa_runtime" }
