use alloc::boxed::Box;

use super::*;

pub(super) fn apply_device_io_command(
    graph: &mut SemanticGraph,
    command: SemanticCommand,
) -> ApplyDispatch {
    let applied = match command {
        SemanticCommand::RecordDeviceObject {
            device,
            name,
            class,
            resource,
            resource_generation,
            backend,
            bus,
            vendor,
            model,
            note,
        } => graph.record_device_object_with_id(
            device,
            &name,
            &class,
            resource,
            resource_generation,
            &backend,
            &bus,
            &vendor,
            &model,
            &note,
        ),
        SemanticCommand::RecordQueueObject {
            queue,
            name,
            role,
            queue_index,
            depth,
            device,
            device_generation,
            note,
        } => graph.record_queue_object_with_id(
            queue,
            &name,
            role,
            queue_index,
            depth,
            device,
            device_generation,
            &note,
        ),
        SemanticCommand::RecordDescriptorObject {
            descriptor,
            queue,
            queue_generation,
            slot,
            access,
            length,
            note,
        } => graph.record_descriptor_object_with_id(
            descriptor,
            queue,
            queue_generation,
            slot,
            access,
            length,
            &note,
        ),
        SemanticCommand::RecordDmaBufferObject {
            dma_buffer,
            descriptor,
            descriptor_generation,
            resource,
            resource_generation,
            access,
            length,
            note,
        } => graph.record_dma_buffer_object_with_id(
            dma_buffer,
            descriptor,
            descriptor_generation,
            resource,
            resource_generation,
            access,
            length,
            &note,
        ),
        SemanticCommand::RecordMmioRegionObject {
            mmio_region,
            device,
            device_generation,
            resource,
            resource_generation,
            region_index,
            offset,
            length,
            access,
            note,
        } => graph.record_mmio_region_object_with_id(
            mmio_region,
            device,
            device_generation,
            resource,
            resource_generation,
            region_index,
            offset,
            length,
            access,
            &note,
        ),
        SemanticCommand::RecordIrqLineObject {
            irq_line,
            device,
            device_generation,
            resource,
            resource_generation,
            irq_number,
            trigger,
            polarity,
            note,
        } => graph.record_irq_line_object_with_id(
            irq_line,
            device,
            device_generation,
            resource,
            resource_generation,
            irq_number,
            trigger,
            polarity,
            &note,
        ),
        SemanticCommand::RecordIrqEvent {
            irq_event,
            irq_line,
            irq_line_generation,
            device,
            device_generation,
            driver_store,
            driver_store_generation,
            sequence,
            note,
        } => graph.record_irq_event_with_id(
            irq_event,
            irq_line,
            irq_line_generation,
            device,
            device_generation,
            driver_store,
            driver_store_generation,
            sequence,
            &note,
        ),
        SemanticCommand::RecordDeviceCapability {
            device_capability,
            driver_store,
            driver_store_generation,
            target,
            class,
            operation,
            handle,
            note,
        } => graph.record_device_capability_with_id(
            device_capability,
            driver_store,
            driver_store_generation,
            target,
            class,
            &operation,
            handle,
            &note,
        ),
        SemanticCommand::BindDriverStore {
            binding,
            driver_store,
            driver_store_generation,
            device,
            device_generation,
            device_capability,
            device_capability_generation,
            note,
        } => graph.record_driver_store_binding_with_id(
            binding,
            driver_store,
            driver_store_generation,
            device,
            device_generation,
            device_capability,
            device_capability_generation,
            &note,
        ),
        SemanticCommand::RecordIoWait {
            io_wait,
            wait,
            wait_generation,
            driver_store,
            driver_store_generation,
            device,
            device_generation,
            driver_binding,
            driver_binding_generation,
            blocker,
            note,
        } => graph.record_io_wait_with_id(
            io_wait,
            wait,
            wait_generation,
            driver_store,
            driver_store_generation,
            device,
            device_generation,
            driver_binding,
            driver_binding_generation,
            blocker,
            &note,
        ),
        SemanticCommand::ResolveIoWait {
            io_wait,
            io_wait_generation,
            irq_event,
            irq_event_generation,
            note,
        } => graph.resolve_io_wait_with_irq_event(
            io_wait,
            io_wait_generation,
            irq_event,
            irq_event_generation,
            &note,
        ),
        SemanticCommand::CancelIoWait { io_wait, io_wait_generation, errno, reason, note } => {
            graph.cancel_io_wait(io_wait, io_wait_generation, errno, reason, &note)
        }
        SemanticCommand::CleanupIoDriver {
            cleanup,
            driver_store,
            driver_store_generation,
            device,
            device_generation,
            driver_binding,
            driver_binding_generation,
            reason,
            note,
        } => graph.cleanup_io_driver_for_device_fault_with_id(
            cleanup,
            driver_store,
            driver_store_generation,
            device,
            device_generation,
            driver_binding,
            driver_binding_generation,
            &reason,
            &note,
        ),
        SemanticCommand::InjectIoFault {
            fault,
            cleanup,
            driver_store,
            driver_store_generation,
            device,
            device_generation,
            driver_binding,
            driver_binding_generation,
            target,
            kind,
            note,
        } => graph.inject_io_fault_with_id(
            fault,
            driver_store,
            driver_store_generation,
            device,
            device_generation,
            driver_binding,
            driver_binding_generation,
            target,
            cleanup,
            kind,
            &note,
        ),
        SemanticCommand::ValidateIoRuntime { report, note } => {
            graph.record_io_validation_report_with_id(report, &note)
        }
        other => return ApplyDispatch::Next(Box::new(other)),
    };
    ApplyDispatch::Applied(applied)
}
