use alloc::boxed::Box;

use super::*;

pub(super) fn apply_network_command(
    graph: &mut SemanticGraph,
    command: SemanticCommand,
) -> ApplyDispatch {
    let applied = match command {
        SemanticCommand::RecordPacketDeviceObject {
            packet_device,
            name,
            device,
            device_generation,
            mtu,
            rx_queue_depth,
            tx_queue_depth,
            mac,
            frame_format_version,
            max_payload_len,
            note,
        } => graph.record_packet_device_object_with_id(
            packet_device,
            &name,
            device,
            device_generation,
            mtu,
            rx_queue_depth,
            tx_queue_depth,
            mac,
            frame_format_version,
            max_payload_len,
            &note,
        ),
        SemanticCommand::RecordPacketBufferObject {
            packet_buffer,
            packet_device,
            packet_device_generation,
            direction,
            frame_format_version,
            capacity,
            payload_len,
            sequence,
            state,
            note,
        } => graph.record_packet_buffer_object_with_id(
            packet_buffer,
            packet_device,
            packet_device_generation,
            direction,
            frame_format_version,
            capacity,
            payload_len,
            sequence,
            state,
            &note,
        ),
        SemanticCommand::RecordPacketQueueObject {
            packet_queue,
            name,
            packet_device,
            packet_device_generation,
            role,
            queue_index,
            depth,
            note,
        } => graph.record_packet_queue_object_with_id(
            packet_queue,
            &name,
            packet_device,
            packet_device_generation,
            role,
            queue_index,
            depth,
            &note,
        ),
        SemanticCommand::RecordPacketDescriptorObject {
            packet_descriptor,
            packet_queue,
            packet_queue_generation,
            packet_buffer,
            packet_buffer_generation,
            slot,
            length,
            note,
        } => graph.record_packet_descriptor_object_with_id(
            packet_descriptor,
            packet_queue,
            packet_queue_generation,
            packet_buffer,
            packet_buffer_generation,
            slot,
            length,
            &note,
        ),
        SemanticCommand::RecordFakeNetBackendObject {
            fake_net_backend,
            name,
            packet_device,
            packet_device_generation,
            provider,
            profile,
            mtu,
            rx_queue_depth,
            tx_queue_depth,
            mac,
            frame_format_version,
            max_payload_len,
            deterministic_seed,
            note,
        } => graph.record_fake_net_backend_object_with_id(
            fake_net_backend,
            &name,
            packet_device,
            packet_device_generation,
            &provider,
            &profile,
            mtu,
            rx_queue_depth,
            tx_queue_depth,
            mac,
            frame_format_version,
            max_payload_len,
            deterministic_seed,
            &note,
        ),
        SemanticCommand::RecordVirtioNetBackendObject {
            virtio_net_backend,
            name,
            packet_device,
            packet_device_generation,
            driver_binding,
            driver_binding_generation,
            provider,
            profile,
            model,
            mtu,
            rx_queue_depth,
            tx_queue_depth,
            mac,
            frame_format_version,
            max_payload_len,
            device_features,
            driver_features,
            negotiated_features,
            rx_queue_index,
            tx_queue_index,
            queue_size,
            irq_vector,
            note,
        } => graph.record_virtio_net_backend_object_with_id(
            virtio_net_backend,
            &name,
            packet_device,
            packet_device_generation,
            driver_binding,
            driver_binding_generation,
            &provider,
            &profile,
            &model,
            mtu,
            rx_queue_depth,
            tx_queue_depth,
            mac,
            frame_format_version,
            max_payload_len,
            device_features,
            driver_features,
            negotiated_features,
            rx_queue_index,
            tx_queue_index,
            queue_size,
            irq_vector,
            &note,
        ),
        SemanticCommand::RecordNetworkRxInterrupt {
            rx_interrupt,
            virtio_net_backend,
            virtio_net_backend_generation,
            irq_event,
            irq_event_generation,
            packet_device,
            packet_device_generation,
            rx_queue,
            rx_queue_generation,
            ready_descriptors,
            sequence,
            note,
        } => graph.record_network_rx_interrupt_with_id(
            rx_interrupt,
            virtio_net_backend,
            virtio_net_backend_generation,
            irq_event,
            irq_event_generation,
            packet_device,
            packet_device_generation,
            rx_queue,
            rx_queue_generation,
            ready_descriptors,
            sequence,
            &note,
        ),
        SemanticCommand::ResolveNetworkRxWait {
            resolution,
            io_wait,
            io_wait_generation,
            rx_interrupt,
            rx_interrupt_generation,
            note,
        } => graph.resolve_network_rx_wait_with_id(
            resolution,
            io_wait,
            io_wait_generation,
            rx_interrupt,
            rx_interrupt_generation,
            &note,
        ),
        SemanticCommand::RecordNetworkTxCapabilityGate {
            tx_gate,
            driver_store,
            driver_store_generation,
            packet_descriptor,
            packet_descriptor_generation,
            device_capability,
            device_capability_generation,
            handle,
            note,
        } => graph.record_network_tx_capability_gate_with_id(
            tx_gate,
            driver_store,
            driver_store_generation,
            packet_descriptor,
            packet_descriptor_generation,
            device_capability,
            device_capability_generation,
            handle,
            &note,
        ),
        SemanticCommand::RecordNetworkTxCompletion {
            completion,
            tx_gate,
            tx_gate_generation,
            backend,
            completion_sequence,
            note,
        } => graph.record_network_tx_completion_with_id(
            completion,
            tx_gate,
            tx_gate_generation,
            backend,
            completion_sequence,
            &note,
        ),
        SemanticCommand::RecordNetworkStackAdapter {
            adapter,
            backend,
            packet_device,
            packet_device_generation,
            rx_queue,
            rx_queue_generation,
            tx_queue,
            tx_queue_generation,
            implementation,
            implementation_version,
            profile,
            medium,
            mac,
            ipv4_addr,
            ipv4_prefix_len,
            mtu,
            rx_queue_depth,
            tx_queue_depth,
            max_payload_len,
            socket_capacity,
            note,
        } => graph.record_network_stack_adapter_with_id(
            adapter,
            backend,
            packet_device,
            packet_device_generation,
            rx_queue,
            rx_queue_generation,
            tx_queue,
            tx_queue_generation,
            &implementation,
            &implementation_version,
            &profile,
            &medium,
            mac,
            ipv4_addr,
            ipv4_prefix_len,
            mtu,
            rx_queue_depth,
            tx_queue_depth,
            max_payload_len,
            socket_capacity,
            &note,
        ),
        SemanticCommand::RecordSocketObject {
            socket,
            adapter,
            adapter_generation,
            owner_store,
            owner_store_generation,
            domain,
            socket_type,
            protocol,
            note,
        } => graph.record_socket_object_with_id(
            socket,
            adapter,
            adapter_generation,
            owner_store,
            owner_store_generation,
            domain,
            socket_type,
            protocol,
            &note,
        ),
        SemanticCommand::RecordEndpointObject {
            endpoint,
            socket,
            socket_generation,
            local_addr,
            local_port,
            remote_addr,
            remote_port,
            note,
        } => graph.record_endpoint_object_with_id(
            endpoint,
            socket,
            socket_generation,
            local_addr,
            local_port,
            remote_addr,
            remote_port,
            &note,
        ),
        SemanticCommand::BindSocketEndpoint {
            operation_id,
            endpoint,
            endpoint_generation,
            local_addr,
            local_port,
            sequence,
            note,
        } => graph.record_socket_operation_with_id(
            operation_id,
            endpoint,
            endpoint_generation,
            SocketOperationKind::Bind,
            local_addr,
            local_port,
            [0, 0, 0, 0],
            0,
            0,
            0,
            sequence,
            &note,
        ),
        SemanticCommand::ListenSocketEndpoint {
            operation_id,
            endpoint,
            endpoint_generation,
            backlog,
            sequence,
            note,
        } => graph.record_socket_operation_with_id(
            operation_id,
            endpoint,
            endpoint_generation,
            SocketOperationKind::Listen,
            [0, 0, 0, 0],
            0,
            [0, 0, 0, 0],
            0,
            backlog,
            0,
            sequence,
            &note,
        ),
        SemanticCommand::ConnectSocketEndpoint {
            operation_id,
            endpoint,
            endpoint_generation,
            remote_addr,
            remote_port,
            sequence,
            note,
        } => graph.record_socket_operation_with_id(
            operation_id,
            endpoint,
            endpoint_generation,
            SocketOperationKind::Connect,
            [0, 0, 0, 0],
            0,
            remote_addr,
            remote_port,
            0,
            0,
            sequence,
            &note,
        ),
        SemanticCommand::SendSocket {
            operation_id,
            endpoint,
            endpoint_generation,
            byte_len,
            sequence,
            note,
        } => graph.record_socket_operation_with_id(
            operation_id,
            endpoint,
            endpoint_generation,
            SocketOperationKind::Send,
            [0, 0, 0, 0],
            0,
            [0, 0, 0, 0],
            0,
            0,
            byte_len,
            sequence,
            &note,
        ),
        SemanticCommand::RecvSocket {
            operation_id,
            endpoint,
            endpoint_generation,
            byte_len,
            sequence,
            note,
        } => graph.record_socket_operation_with_id(
            operation_id,
            endpoint,
            endpoint_generation,
            SocketOperationKind::Recv,
            [0, 0, 0, 0],
            0,
            [0, 0, 0, 0],
            0,
            0,
            byte_len,
            sequence,
            &note,
        ),
        SemanticCommand::RecordSocketWait {
            socket_wait,
            wait,
            wait_generation,
            endpoint,
            endpoint_generation,
            wait_kind,
            blocker,
            note,
        } => graph.record_socket_wait_with_id(
            socket_wait,
            wait,
            wait_generation,
            endpoint,
            endpoint_generation,
            wait_kind,
            blocker,
            &note,
        ),
        SemanticCommand::ResolveSocketWait {
            socket_wait,
            socket_wait_generation,
            ready_sequence,
            byte_len,
            note,
        } => graph.resolve_socket_wait(
            socket_wait,
            socket_wait_generation,
            ready_sequence,
            byte_len,
            &note,
        ),
        SemanticCommand::CancelSocketWait {
            socket_wait,
            socket_wait_generation,
            errno,
            reason,
            note,
        } => graph.cancel_socket_wait(socket_wait, socket_wait_generation, errno, reason, &note),
        SemanticCommand::RecordNetworkBackpressure {
            backpressure,
            adapter,
            adapter_generation,
            packet_device,
            packet_device_generation,
            packet_queue,
            packet_queue_generation,
            endpoint,
            endpoint_generation,
            direction,
            reason,
            action,
            queue_depth,
            queue_limit,
            dropped_packets,
            dropped_bytes,
            sequence,
            note,
        } => graph.record_network_backpressure_with_id(
            backpressure,
            adapter,
            adapter_generation,
            packet_device,
            packet_device_generation,
            packet_queue,
            packet_queue_generation,
            endpoint,
            endpoint_generation,
            direction,
            reason,
            action,
            queue_depth,
            queue_limit,
            dropped_packets,
            dropped_bytes,
            sequence,
            &note,
        ),
        SemanticCommand::CleanupNetworkDriver {
            cleanup,
            io_cleanup,
            adapter,
            adapter_generation,
            packet_device,
            packet_device_generation,
            backend,
            reason,
            note,
        } => graph.cleanup_network_driver_with_id(
            cleanup,
            io_cleanup,
            adapter,
            adapter_generation,
            packet_device,
            packet_device_generation,
            backend,
            &reason,
            &note,
        ),
        SemanticCommand::RecordNetworkGenerationAudit {
            audit,
            adapter,
            adapter_generation,
            packet_device,
            packet_device_generation,
            packet_queue,
            packet_queue_generation,
            packet_descriptor,
            packet_descriptor_generation,
            packet_buffer,
            packet_buffer_generation,
            dma_buffer,
            device_capability,
            rejected_packet_generation_probes,
            rejected_dma_generation_probes,
            note,
        } => graph.record_network_generation_audit_with_id(
            audit,
            adapter,
            adapter_generation,
            packet_device,
            packet_device_generation,
            packet_queue,
            packet_queue_generation,
            packet_descriptor,
            packet_descriptor_generation,
            packet_buffer,
            packet_buffer_generation,
            dma_buffer,
            device_capability,
            rejected_packet_generation_probes,
            rejected_dma_generation_probes,
            &note,
        ),
        SemanticCommand::RecordNetworkFaultInjection {
            injection,
            adapter,
            adapter_generation,
            packet_device,
            packet_device_generation,
            packet_queue,
            packet_queue_generation,
            packet_descriptor,
            packet_descriptor_generation,
            packet_buffer,
            packet_buffer_generation,
            endpoint,
            endpoint_generation,
            direction,
            kind,
            effect,
            injected_packets,
            dropped_packets,
            error_packets,
            error_code,
            sequence,
            note,
        } => graph.record_network_fault_injection_with_id(
            injection,
            adapter,
            adapter_generation,
            packet_device,
            packet_device_generation,
            packet_queue,
            packet_queue_generation,
            packet_descriptor,
            packet_descriptor_generation,
            packet_buffer,
            packet_buffer_generation,
            endpoint,
            endpoint_generation,
            direction,
            kind,
            effect,
            injected_packets,
            dropped_packets,
            error_packets,
            &error_code,
            sequence,
            &note,
        ),
        SemanticCommand::RecordNetworkBenchmark {
            benchmark,
            scenario,
            adapter,
            adapter_generation,
            packet_device,
            packet_device_generation,
            tx_queue,
            tx_queue_generation,
            rx_queue,
            rx_queue_generation,
            tx_completion,
            tx_completion_generation,
            rx_wait_resolution,
            rx_wait_resolution_generation,
            endpoint,
            endpoint_generation,
            backpressure,
            backpressure_generation,
            sample_packets,
            sample_bytes,
            tx_completed_packets,
            rx_resolved_packets,
            dropped_packets,
            measured_nanos,
            budget_nanos,
            p50_latency_nanos,
            p99_latency_nanos,
            note,
        } => graph.record_network_benchmark_with_id(
            benchmark,
            &scenario,
            adapter,
            adapter_generation,
            packet_device,
            packet_device_generation,
            tx_queue,
            tx_queue_generation,
            rx_queue,
            rx_queue_generation,
            tx_completion,
            tx_completion_generation,
            rx_wait_resolution,
            rx_wait_resolution_generation,
            endpoint,
            endpoint_generation,
            backpressure,
            backpressure_generation,
            sample_packets,
            sample_bytes,
            tx_completed_packets,
            rx_resolved_packets,
            dropped_packets,
            measured_nanos,
            budget_nanos,
            p50_latency_nanos,
            p99_latency_nanos,
            &note,
        ),
        SemanticCommand::RecordNetworkRecoveryBenchmark {
            benchmark,
            scenario,
            cleanup,
            cleanup_generation,
            io_cleanup,
            io_cleanup_generation,
            fault_injection,
            fault_injection_generation,
            recovery_start_event,
            recovery_complete_event,
            cancelled_socket_waits,
            revoked_packet_capabilities,
            recovery_nanos,
            budget_nanos,
            note,
        } => graph.record_network_recovery_benchmark_with_id(
            benchmark,
            &scenario,
            cleanup,
            cleanup_generation,
            io_cleanup,
            io_cleanup_generation,
            fault_injection,
            fault_injection_generation,
            recovery_start_event,
            recovery_complete_event,
            cancelled_socket_waits,
            revoked_packet_capabilities,
            recovery_nanos,
            budget_nanos,
            &note,
        ),
        other => return ApplyDispatch::Next(Box::new(other)),
    };
    ApplyDispatch::Applied(applied)
}
