use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

use contract_core::{manifest_binding_hash, module_abi_fingerprint};
use sha2::{Digest, Sha256};
use supervisor_catalog::{
    ARTIFACT_SIGNATURE_PROFILE, SUPERVISOR_WASM_MODULES, USER_BINARIES, module_dependencies,
};

const EMBEDDED_ARTIFACT_PROFILE: &str = "target-embedded-kernel";
const EMBEDDED_RUNTIME_MODE: &str = "research";
const EMBEDDED_CWASM_HASH: &str = "target-cwasm-not-linked";
const EMBEDDED_SIGNER: &str = "kernel-buildrs-embedded-manifest";

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
    let workspace_root = manifest_dir.parent().expect("kernel crate should live in workspace root");
    let target_dir =
        PathBuf::from(env::var_os("OUT_DIR").expect("missing OUT_DIR")).join("wasm-target");
    let cargo = env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned());
    println!("cargo:rerun-if-changed={}", workspace_root.join(".cargo/config.toml").display());

    for module in SUPERVISOR_WASM_MODULES {
        build_module(&cargo, workspace_root, &target_dir, module.package);
        expose_artifact_path(workspace_root, &target_dir, module.package);
    }
    generate_embedded_manifest_plan(workspace_root, &target_dir, &out_dir());

    let user_target_dir =
        PathBuf::from(env::var_os("OUT_DIR").expect("missing OUT_DIR")).join("user-target");
    for binary in USER_BINARIES {
        build_user_binary(&cargo, workspace_root, &user_target_dir, binary.package);
        expose_user_binary_path(workspace_root, &user_target_dir, binary.package);
    }
}

fn out_dir() -> PathBuf {
    PathBuf::from(env::var_os("OUT_DIR").expect("missing OUT_DIR"))
}

fn build_module(cargo: &str, workspace_root: &Path, target_dir: &Path, module: &str) {
    let status = Command::new(cargo)
        .current_dir(workspace_root)
        .env("CARGO_TARGET_DIR", target_dir)
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .env("RUSTFLAGS", wasm_rustflags())
        .args(["build", "-p", module, "--target", "wasm32-unknown-unknown", "--release"])
        .status()
        .unwrap_or_else(|err| panic!("failed to spawn cargo for {module}: {err}"));

    if !status.success() {
        panic!("building {module} for wasm32-unknown-unknown failed");
    }
}

fn wasm_rustflags() -> &'static str {
    "-C target-feature=-bulk-memory,-multivalue,-reference-types,-sign-ext,-nontrapping-fptoint"
}

fn expose_artifact_path(workspace_root: &Path, target_dir: &Path, module: &str) {
    println!("cargo:rerun-if-changed={}", workspace_root.join(module).display());
    println!("cargo:rerun-if-changed={}", workspace_root.join("abi").display());

    let artifact =
        target_dir.join("wasm32-unknown-unknown").join("release").join(format!("{module}.wasm"));
    strip_custom_sections(&artifact);
    let env_key = format!("VMOS_{}_WASM", module.to_ascii_uppercase());
    println!("cargo:rustc-env={}={}", env_key, artifact.display());
}

fn generate_embedded_manifest_plan(workspace_root: &Path, target_dir: &Path, out_dir: &Path) {
    let path = out_dir.join("supervisor_manifest_plan.rs");
    let mut source = String::new();
    source.push_str("// @generated by kernel/build.rs\n");
    source.push_str("pub(crate) static EMBEDDED_ARTIFACT_MANIFEST_PLAN: EmbeddedArtifactManifestPlan = EmbeddedArtifactManifestPlan {\n");
    source.push_str(&format!(
        "    artifact_profile: {:?},\n    runtime_mode: {:?},\n    entries: &[\n",
        EMBEDDED_ARTIFACT_PROFILE, EMBEDDED_RUNTIME_MODE
    ));
    for module in SUPERVISOR_WASM_MODULES {
        let wasm_path = wasm_artifact_path(target_dir, module.package);
        let wasm_bytes = fs::read(&wasm_path).unwrap_or_else(|err| {
            panic!("failed to read embedded wasm artifact {}: {err}", wasm_path.display())
        });
        let wasm_sha256 = sha256_hex(&wasm_bytes);
        let abi_fingerprint = module_abi_fingerprint(module);
        let manifest_binding_hash =
            manifest_binding_hash(module, &wasm_sha256, EMBEDDED_CWASM_HASH, &abi_fingerprint);
        source.push_str("        EmbeddedArtifactManifestEntry {\n");
        source.push_str(&format!("            package: {:?},\n", module.package));
        source.push_str(&format!("            artifact_name: {:?},\n", module.artifact_name));
        source.push_str(&format!("            role: {:?},\n", module.role.as_str()));
        source
            .push_str(&format!("            fault_policy: {:?},\n", module.fault_policy.as_str()));
        source.push_str(&format!(
            "            wasm_path: {:?},\n",
            relative_to_workspace(workspace_root, &wasm_path)
        ));
        source.push_str(&format!("            wasm_sha256: {:?},\n", wasm_sha256));
        source.push_str(&format!("            cwasm_sha256: {:?},\n", EMBEDDED_CWASM_HASH));
        source.push_str(&format!("            abi_fingerprint: {:?},\n", abi_fingerprint));
        source.push_str(&format!(
            "            manifest_binding_hash: {:?},\n",
            manifest_binding_hash
        ));
        source.push_str(&format!(
            "            signature_profile: {:?},\n",
            ARTIFACT_SIGNATURE_PROFILE
        ));
        source.push_str(&format!("            signer: {:?},\n", EMBEDDED_SIGNER));
        source.push_str("            resource_limits: StoreResourceLimits {\n");
        source.push_str("                max_memory_pages: 16,\n");
        source.push_str("                max_table_elements: 0,\n");
        source.push_str("                max_hostcalls_per_activation: 64,\n");
        source.push_str("            },\n");
        source.push_str(&format!(
            "            dependency_count: {},\n",
            module_dependencies(module).len()
        ));
        source.push_str(&format!(
            "            expected_export_count: {},\n",
            module.expected_exports.len()
        ));
        source.push_str("        },\n");
    }
    source.push_str("    ],\n};\n");
    fs::write(&path, source).unwrap_or_else(|err| {
        panic!("failed to write embedded manifest plan {}: {err}", path.display())
    });
}

fn wasm_artifact_path(target_dir: &Path, module: &str) -> PathBuf {
    target_dir.join("wasm32-unknown-unknown").join("release").join(format!("{module}.wasm"))
}

fn relative_to_workspace(workspace_root: &Path, path: &Path) -> String {
    path.strip_prefix(workspace_root).unwrap_or(path).display().to_string()
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hex::encode(hasher.finalize())
}

fn strip_custom_sections(path: &Path) {
    let bytes = fs::read(path)
        .unwrap_or_else(|err| panic!("failed to read wasm artifact {}: {err}", path.display()));
    let stripped = strip_wasm_custom_sections(&bytes)
        .unwrap_or_else(|err| panic!("failed to strip wasm artifact {}: {err}", path.display()));
    fs::write(path, stripped)
        .unwrap_or_else(|err| panic!("failed to write wasm artifact {}: {err}", path.display()));
}

fn strip_wasm_custom_sections(bytes: &[u8]) -> Result<Vec<u8>, &'static str> {
    if bytes.len() < 8 || &bytes[..4] != b"\0asm" {
        return Err("invalid wasm header");
    }
    let mut out = bytes[..8].to_vec();
    let mut offset = 8usize;
    while offset < bytes.len() {
        let section_id = bytes[offset];
        offset += 1;
        let (section_len, leb_len) = read_leb_u32(&bytes[offset..])?;
        offset += leb_len;
        let end =
            offset.checked_add(section_len as usize).ok_or("wasm section length overflowed")?;
        if end > bytes.len() {
            return Err("wasm section exceeded file length");
        }
        if section_id != 0 {
            out.push(section_id);
            write_leb_u32(section_len, &mut out);
            out.extend_from_slice(&bytes[offset..end]);
        }
        offset = end;
    }
    Ok(out)
}

fn read_leb_u32(bytes: &[u8]) -> Result<(u32, usize), &'static str> {
    let mut value = 0u32;
    let mut shift = 0u32;
    for (index, byte) in bytes.iter().copied().enumerate().take(5) {
        value |= ((byte & 0x7f) as u32) << shift;
        if byte & 0x80 == 0 {
            return Ok((value, index + 1));
        }
        shift += 7;
    }
    Err("invalid wasm leb128")
}

fn write_leb_u32(mut value: u32, out: &mut Vec<u8>) {
    loop {
        let mut byte = (value & 0x7f) as u8;
        value >>= 7;
        if value != 0 {
            byte |= 0x80;
        }
        out.push(byte);
        if value == 0 {
            break;
        }
    }
}

fn build_user_binary(cargo: &str, workspace_root: &Path, target_dir: &Path, binary: &str) {
    let status = Command::new(cargo)
        .current_dir(workspace_root)
        .env("CARGO_TARGET_DIR", target_dir)
        .args(["build", "-p", binary, "--target", "x86_64-unknown-none"])
        .status()
        .unwrap_or_else(|err| panic!("failed to spawn cargo for {binary}: {err}"));

    if !status.success() {
        panic!("building {binary} for x86_64-unknown-none failed");
    }
}

fn expose_user_binary_path(workspace_root: &Path, target_dir: &Path, binary: &str) {
    println!("cargo:rerun-if-changed={}", workspace_root.join(binary).display());
    println!("cargo:rerun-if-changed={}", workspace_root.join("abi").display());

    let artifact = target_dir.join("x86_64-unknown-none").join("debug").join(binary);
    let env_key = format!("VMOS_{}_ELF", binary.to_ascii_uppercase());
    println!("cargo:rustc-env={}={}", env_key, artifact.display());
}
