use alloc::{string::String, vec::Vec};

use super::*;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SemanticCommand {
    RegisterHart {
        hart: HartId,
        hardware_id: u32,
        label: String,
        boot: bool,
        note: String,
    },
    SetHartState {
        hart: HartId,
        hart_generation: Generation,
        state: HartState,
        reason: String,
        note: String,
    },
    BindHartCurrentActivation {
        hart: HartId,
        hart_generation: Generation,
        activation: ActivationId,
        activation_generation: Generation,
        note: String,
    },
    ClearHartCurrentActivation {
        hart: HartId,
        hart_generation: Generation,
        activation: ActivationId,
        activation_generation: Generation,
        reason: String,
        note: String,
    },
    CreateRuntimeActivation {
        activation: ActivationId,
        owner_task: TaskId,
        owner_task_generation: Generation,
        owner_store: Option<StoreId>,
        owner_store_generation: Option<Generation>,
        code_object: Option<ContractObjectRef>,
    },
    CreateRunnableQueue {
        queue: RunnableQueueId,
        label: String,
    },
    BindRunnableQueueOwner {
        queue: RunnableQueueId,
        queue_generation: Generation,
        hart: HartId,
        hart_generation: Generation,
        note: String,
    },
    EnqueueRunnable {
        queue: RunnableQueueId,
        activation: ActivationId,
        activation_generation: Generation,
    },
    DequeueRunnable {
        queue: RunnableQueueId,
        activation: ActivationId,
    },
    CreateActivationContext {
        context: ActivationContextId,
        activation: ActivationId,
        activation_generation: Generation,
    },
    UpdateActivationContextVectorState {
        context: ActivationContextId,
        context_generation: Generation,
        vector_state: Option<ContractObjectRef>,
        vector_status: ActivationVectorState,
        note: String,
    },
    EnableLazyVectorState {
        context: ActivationContextId,
        context_generation: Generation,
        vector_state: ContractObjectRef,
        note: String,
    },
    CaptureSavedContext {
        saved_context: SavedContextId,
        context: ActivationContextId,
        context_generation: Generation,
        reason: SavedContextReason,
        pc: u64,
        sp: u64,
        flags: u64,
        note: String,
    },
    SavePreemptedContext {
        context: ActivationContextId,
        saved_context: SavedContextId,
        preemption: PreemptionId,
        preemption_generation: Generation,
        pc: u64,
        sp: u64,
        flags: u64,
        note: String,
    },
    SaveDirtyVectorStateOnPreempt {
        context: ActivationContextId,
        context_generation: Generation,
        saved_context: SavedContextId,
        saved_context_generation: Generation,
        preemption: PreemptionId,
        preemption_generation: Generation,
        vector_state: ContractObjectRef,
        note: String,
    },
    RecordTimerInterrupt {
        interrupt: TimerInterruptId,
        timer_epoch: u64,
        hart: HartId,
        hart_generation: Generation,
        target_activation: Option<ActivationId>,
        target_activation_generation: Option<Generation>,
        note: String,
    },
    RecordIpiEvent {
        ipi: IpiEventId,
        source_hart: HartId,
        source_hart_generation: Generation,
        target_hart: HartId,
        target_hart_generation: Generation,
        kind: IpiEventKind,
        reason: String,
        note: String,
    },
    RemotePreemptActivation {
        remote_preempt: RemotePreemptId,
        ipi: IpiEventId,
        ipi_generation: Generation,
        source_hart: HartId,
        source_hart_generation: Generation,
        target_hart: HartId,
        target_hart_generation: Generation,
        activation: ActivationId,
        activation_generation: Generation,
        queue: RunnableQueueId,
        note: String,
    },
    RemoteParkHart {
        remote_park: RemoteParkId,
        ipi: IpiEventId,
        ipi_generation: Generation,
        source_hart: HartId,
        source_hart_generation: Generation,
        target_hart: HartId,
        target_hart_generation: Generation,
        reason: String,
        note: String,
    },
    PreemptActivation {
        preemption: PreemptionId,
        activation: ActivationId,
        activation_generation: Generation,
        timer_interrupt: TimerInterruptId,
        timer_interrupt_generation: Generation,
        queue: RunnableQueueId,
        note: String,
    },
    RecordSchedulerDecision {
        decision: SchedulerDecisionId,
        queue: RunnableQueueId,
        queue_generation: Generation,
        selected_activation: ActivationId,
        selected_activation_generation: Generation,
        reason: String,
        note: String,
    },
    RecordCrossHartSchedulerDecision {
        cross_decision: CrossHartSchedulerDecisionId,
        scheduler_decision: SchedulerDecisionId,
        scheduler_decision_generation: Generation,
        deciding_hart: HartId,
        deciding_hart_generation: Generation,
        target_hart: HartId,
        target_hart_generation: Generation,
        reason: String,
        note: String,
    },
    MigrateRunnableActivation {
        migration: ActivationMigrationId,
        activation: ActivationId,
        activation_generation: Generation,
        source_queue: RunnableQueueId,
        source_queue_generation: Generation,
        target_queue: RunnableQueueId,
        target_queue_generation: Generation,
        source_hart: HartId,
        source_hart_generation: Generation,
        target_hart: HartId,
        target_hart_generation: Generation,
        reason: String,
        note: String,
    },
    RecordSmpSafePoint {
        safe_point: SmpSafePointId,
        coordinator_hart: HartId,
        coordinator_hart_generation: Generation,
        participants: Vec<(HartId, Generation)>,
        reason: String,
        note: String,
    },
    CompleteStopTheWorldRendezvous {
        rendezvous: StopTheWorldRendezvousId,
        epoch: u64,
        safe_point: SmpSafePointId,
        safe_point_generation: Generation,
        stop_new_activations: bool,
        reason: String,
        note: String,
    },
    ValidateSmpCodePublishBarrier {
        barrier: SmpCodePublishBarrierId,
        rendezvous: StopTheWorldRendezvousId,
        rendezvous_generation: Generation,
        code_publish_epoch_before: u64,
        code_publish_epoch_after: u64,
        remote_icache_sync_required: bool,
        code_publish_executed: bool,
        reason: String,
        note: String,
    },
    ValidateSmpCleanupQuiescence {
        quiescence: SmpCleanupQuiescenceId,
        cleanup: ActivationCleanupId,
        cleanup_generation: Generation,
        rendezvous: StopTheWorldRendezvousId,
        rendezvous_generation: Generation,
        store: StoreId,
        target_store_generation: Generation,
        result_store_generation: Generation,
        reason: String,
        note: String,
    },
    ValidateSmpSnapshotBarrier {
        barrier: SmpSnapshotBarrierId,
        rendezvous: StopTheWorldRendezvousId,
        rendezvous_generation: Generation,
        snapshot_state: SnapshotBarrierValidationState,
        reason: String,
        note: String,
    },
    RecordSmpStressRun {
        run: SmpStressRunId,
        scenario: String,
        iterations: u32,
        invariant_checks: u32,
        reason: String,
        note: String,
    },
    RecordSmpScalingBenchmark {
        benchmark: SmpScalingBenchmarkId,
        scenario: String,
        stress_run: SmpStressRunId,
        stress_run_generation: Generation,
        workload_units: u64,
        baseline_single_hart_nanos: u64,
        measured_smp_nanos: u64,
        budget_nanos: u64,
        note: String,
    },
    RecordIntegratedSmpPreemptionCleanup {
        integrated: IntegratedSmpPreemptionCleanupId,
        scenario: String,
        stress_run: SmpStressRunId,
        stress_run_generation: Generation,
        preemption: PreemptionId,
        preemption_generation: Generation,
        timer_interrupt: TimerInterruptId,
        timer_interrupt_generation: Generation,
        saved_context: SavedContextId,
        saved_context_generation: Generation,
        remote_preempt: RemotePreemptId,
        remote_preempt_generation: Generation,
        activation_cleanup: ActivationCleanupId,
        activation_cleanup_generation: Generation,
        smp_cleanup_quiescence: SmpCleanupQuiescenceId,
        smp_cleanup_quiescence_generation: Generation,
        invariant_checks: u32,
        note: String,
    },
    RecordIntegratedSmpNetworkFault {
        integrated: IntegratedSmpNetworkFaultId,
        scenario: String,
        network_driver_cleanup: NetworkDriverCleanupId,
        network_driver_cleanup_generation: Generation,
        smp_stress_run: SmpStressRunId,
        smp_stress_run_generation: Generation,
        remote_preempt: RemotePreemptId,
        remote_preempt_generation: Generation,
        smp_cleanup_quiescence: SmpCleanupQuiescenceId,
        smp_cleanup_quiescence_generation: Generation,
        invariant_checks: u32,
        note: String,
    },
    RecordIntegratedDiskPreemptFault {
        integrated: IntegratedDiskPreemptFaultId,
        scenario: String,
        preemption: PreemptionId,
        preemption_generation: Generation,
        block_pending_io_policy: BlockPendingIoPolicyId,
        block_pending_io_policy_generation: Generation,
        invariant_checks: u32,
        note: String,
    },
    RecordIntegratedSimdMigration {
        integrated: IntegratedSimdMigrationId,
        scenario: String,
        activation_migration: ActivationMigrationId,
        activation_migration_generation: Generation,
        invariant_checks: u32,
        note: String,
    },
    RecordIntegratedNetworkDiskIo {
        integrated: IntegratedNetworkDiskIoId,
        scenario: String,
        network_benchmark: NetworkBenchmarkId,
        network_benchmark_generation: Generation,
        block_benchmark: BlockBenchmarkId,
        block_benchmark_generation: Generation,
        invariant_checks: u32,
        note: String,
    },
    RecordIntegratedDisplaySchedulerLoad {
        integrated: IntegratedDisplaySchedulerLoadId,
        scenario: String,
        framebuffer_benchmark: FramebufferBenchmarkId,
        framebuffer_benchmark_generation: Generation,
        scheduler_decision: SchedulerDecisionId,
        scheduler_decision_generation: Generation,
        invariant_checks: u32,
        note: String,
    },
    RecordIntegratedSnapshotIoLeaseBarrier {
        integrated: IntegratedSnapshotIoLeaseBarrierId,
        scenario: String,
        smp_snapshot_barrier: SmpSnapshotBarrierId,
        smp_snapshot_barrier_generation: Generation,
        io_cleanup: IoCleanupId,
        io_cleanup_generation: Generation,
        display_snapshot_barrier: DisplaySnapshotBarrierId,
        display_snapshot_barrier_generation: Generation,
        invariant_checks: u32,
        note: String,
    },
    RecordIntegratedCodePublishSmpWorkload {
        integrated: IntegratedCodePublishSmpWorkloadId,
        scenario: String,
        smp_stress_run: SmpStressRunId,
        smp_stress_run_generation: Generation,
        smp_code_publish_barrier: SmpCodePublishBarrierId,
        smp_code_publish_barrier_generation: Generation,
        invariant_checks: u32,
        note: String,
    },
    RecordIntegratedDisplayPanic {
        integrated: IntegratedDisplayPanicId,
        scenario: String,
        substrate_panic_event: EventId,
        display_panic_last_frame: DisplayPanicLastFrameId,
        display_panic_last_frame_generation: Generation,
        panic_ring_bytes: u32,
        panic_record_max_bytes: u32,
        panic_ring_oldest_seq: u64,
        panic_ring_newest_seq: u64,
        panic_ring_record_count: u32,
        panic_ring_lost_count: u64,
        jsonl_frame_count: u32,
        contract_panic_summary_records: u32,
        last_frame_summary_records: u32,
        corrupt_record_count: u32,
        truncated_record_count: u32,
        invariant_checks: u32,
        note: String,
    },
    RecordIntegratedOsctlTraceReplay {
        integrated: IntegratedOsctlTraceReplayId,
        scenario: String,
        integrated_smp_preemption_cleanup: IntegratedSmpPreemptionCleanupId,
        integrated_smp_preemption_cleanup_generation: Generation,
        integrated_smp_network_fault: IntegratedSmpNetworkFaultId,
        integrated_smp_network_fault_generation: Generation,
        integrated_disk_preempt_fault: IntegratedDiskPreemptFaultId,
        integrated_disk_preempt_fault_generation: Generation,
        integrated_simd_migration: IntegratedSimdMigrationId,
        integrated_simd_migration_generation: Generation,
        integrated_network_disk_io: IntegratedNetworkDiskIoId,
        integrated_network_disk_io_generation: Generation,
        integrated_display_scheduler_load: IntegratedDisplaySchedulerLoadId,
        integrated_display_scheduler_load_generation: Generation,
        integrated_snapshot_io_lease_barrier: IntegratedSnapshotIoLeaseBarrierId,
        integrated_snapshot_io_lease_barrier_generation: Generation,
        integrated_code_publish_smp_workload: IntegratedCodePublishSmpWorkloadId,
        integrated_code_publish_smp_workload_generation: Generation,
        integrated_display_panic: IntegratedDisplayPanicId,
        integrated_display_panic_generation: Generation,
        replay_event_cursor: EventId,
        stable_view_count: u32,
        historical_edge_count: u32,
        replayed_root_count: u32,
        integrated_scenario_count: u32,
        replay_fixture_count: u32,
        invariant_checks: u32,
        note: String,
    },
    RecordDeviceObject {
        device: DeviceObjectId,
        name: String,
        class: String,
        resource: ResourceId,
        resource_generation: Generation,
        backend: String,
        bus: String,
        vendor: String,
        model: String,
        note: String,
    },
    RecordPacketDeviceObject {
        packet_device: PacketDeviceObjectId,
        name: String,
        device: DeviceObjectId,
        device_generation: Generation,
        mtu: u32,
        rx_queue_depth: u32,
        tx_queue_depth: u32,
        mac: [u8; 6],
        frame_format_version: u32,
        max_payload_len: u32,
        note: String,
    },
    RecordPacketBufferObject {
        packet_buffer: PacketBufferObjectId,
        packet_device: PacketDeviceObjectId,
        packet_device_generation: Generation,
        direction: PacketBufferDirection,
        frame_format_version: u32,
        capacity: u32,
        payload_len: u32,
        sequence: u64,
        state: PacketBufferObjectState,
        note: String,
    },
    RecordPacketQueueObject {
        packet_queue: PacketQueueObjectId,
        name: String,
        packet_device: PacketDeviceObjectId,
        packet_device_generation: Generation,
        role: PacketQueueRole,
        queue_index: u16,
        depth: u32,
        note: String,
    },
    RecordPacketDescriptorObject {
        packet_descriptor: PacketDescriptorObjectId,
        packet_queue: PacketQueueObjectId,
        packet_queue_generation: Generation,
        packet_buffer: PacketBufferObjectId,
        packet_buffer_generation: Generation,
        slot: u16,
        length: u32,
        note: String,
    },
    RecordFakeNetBackendObject {
        fake_net_backend: FakeNetBackendObjectId,
        name: String,
        packet_device: PacketDeviceObjectId,
        packet_device_generation: Generation,
        provider: String,
        profile: String,
        mtu: u32,
        rx_queue_depth: u32,
        tx_queue_depth: u32,
        mac: [u8; 6],
        frame_format_version: u32,
        max_payload_len: u32,
        deterministic_seed: u64,
        note: String,
    },
    RecordFakeBlockBackendObject {
        fake_block_backend: FakeBlockBackendObjectId,
        name: String,
        block_device: BlockDeviceObjectId,
        block_device_generation: Generation,
        provider: String,
        profile: String,
        sector_size: u32,
        sector_count: u64,
        read_only: bool,
        max_transfer_sectors: u32,
        deterministic_seed: u64,
        note: String,
    },
    RecordVirtioBlkBackendObject {
        virtio_blk_backend: VirtioBlkBackendObjectId,
        name: String,
        block_device: BlockDeviceObjectId,
        block_device_generation: Generation,
        driver_binding: DriverStoreBindingId,
        driver_binding_generation: Generation,
        provider: String,
        profile: String,
        model: String,
        sector_size: u32,
        sector_count: u64,
        read_only: bool,
        max_transfer_sectors: u32,
        device_features: u64,
        driver_features: u64,
        negotiated_features: u64,
        request_queue_index: u16,
        queue_size: u16,
        irq_vector: u16,
        note: String,
    },
    RecordBlockReadPath {
        read_path: BlockReadPathId,
        backend: ContractObjectRef,
        block_request: BlockRequestObjectId,
        block_request_generation: Generation,
        block_completion: BlockCompletionObjectId,
        block_completion_generation: Generation,
        data_digest: u64,
        note: String,
    },
    RecordBlockWritePath {
        write_path: BlockWritePathId,
        backend: ContractObjectRef,
        block_request: BlockRequestObjectId,
        block_request_generation: Generation,
        block_completion: BlockCompletionObjectId,
        block_completion_generation: Generation,
        payload_digest: u64,
        note: String,
    },
    RecordBlockRequestQueue {
        queue: BlockRequestQueueId,
        backend: ContractObjectRef,
        block_device: BlockDeviceObjectId,
        block_device_generation: Generation,
        depth: u32,
        entries: Vec<BlockRequestQueueEntryRef>,
        note: String,
    },
    RecordBlockDmaBuffer {
        block_dma_buffer: BlockDmaBufferId,
        backend: ContractObjectRef,
        block_request: BlockRequestObjectId,
        block_request_generation: Generation,
        dma_buffer: DmaBufferObjectId,
        dma_buffer_generation: Generation,
        buffer_digest: u64,
        note: String,
    },
    RecordBlockPageObject {
        block_page_object: BlockPageObjectId,
        block_dma_buffer: BlockDmaBufferId,
        block_dma_buffer_generation: Generation,
        block_completion: BlockCompletionObjectId,
        block_completion_generation: Generation,
        aspace: ContractObjectRef,
        vma_region: ContractObjectRef,
        page: ContractObjectRef,
        page_dirty_generation: Generation,
        page_backing: PageBacking,
        cow_state: CowState,
        page_state: PageObjectState,
        page_offset: u64,
        byte_len: u64,
        note: String,
    },
    RecordBufferCacheObject {
        buffer_cache_object: BufferCacheObjectId,
        block_page_object: BlockPageObjectId,
        block_page_object_generation: Generation,
        page: ContractObjectRef,
        page_dirty_generation: Generation,
        block_offset: u64,
        byte_len: u64,
        cache_state: BufferCacheObjectState,
        coherency_epoch: u64,
        note: String,
    },
    RecordFileObject {
        file_object: FileObjectId,
        buffer_cache_object: BufferCacheObjectId,
        buffer_cache_object_generation: Generation,
        namespace: String,
        file_key: String,
        path: String,
        file_offset: u64,
        byte_len: u64,
        file_size: u64,
        content_digest: u64,
        state: FileObjectState,
        note: String,
    },
    RecordDirectoryObject {
        directory_object: DirectoryObjectId,
        file_object: FileObjectId,
        file_object_generation: Generation,
        namespace: String,
        directory_key: String,
        directory_path: String,
        entry_name: String,
        child_file_key: String,
        child_path: String,
        entry_kind: DirectoryEntryKind,
        file_size: u64,
        content_digest: u64,
        state: DirectoryObjectState,
        note: String,
    },
    RecordFatAdapterObject {
        fat_adapter_object: FatAdapterObjectId,
        directory_object: DirectoryObjectId,
        directory_object_generation: Generation,
        file_object: FileObjectId,
        file_object_generation: Generation,
        block_device: BlockDeviceObjectId,
        block_device_generation: Generation,
        implementation: String,
        version: String,
        profile: String,
        volume_label: String,
        image_bytes: u64,
        adapter_path: String,
        semantic_path: String,
        bytes_written: u64,
        bytes_read: u64,
        write_digest: u64,
        read_digest: u64,
        file_content_digest: u64,
        state: FatAdapterObjectState,
        note: String,
    },
    RecordExt4AdapterObject {
        ext4_adapter_object: Ext4AdapterObjectId,
        directory_object: DirectoryObjectId,
        directory_object_generation: Generation,
        file_object: FileObjectId,
        file_object_generation: Generation,
        block_device: BlockDeviceObjectId,
        block_device_generation: Generation,
        implementation: String,
        version: String,
        profile: String,
        volume_label: String,
        image_bytes: u64,
        adapter_path: String,
        semantic_path: String,
        bytes_read: u64,
        read_digest: u64,
        file_content_digest: u64,
        directory_entries: u64,
        read_only_enforced: bool,
        state: Ext4AdapterObjectState,
        note: String,
    },
    RecordFileHandleCapability {
        file_handle_capability: FileHandleCapabilityId,
        owner_store: StoreId,
        owner_store_generation: Generation,
        file_object: FileObjectId,
        file_object_generation: Generation,
        directory_object: DirectoryObjectId,
        directory_object_generation: Generation,
        capability: CapabilityId,
        capability_generation: Generation,
        handle: CapabilityHandle,
        operation: String,
        file_offset: u64,
        byte_len: u64,
        content_digest: u64,
        note: String,
    },
    RecordFsWait {
        fs_wait: FsWaitId,
        wait: WaitId,
        wait_generation: Generation,
        file_handle_capability: FileHandleCapabilityId,
        file_handle_capability_generation: Generation,
        operation: String,
        sequence: u64,
        note: String,
    },
    ResolveFsWait {
        fs_wait: FsWaitId,
        fs_wait_generation: Generation,
        note: String,
    },
    CancelFsWait {
        fs_wait: FsWaitId,
        fs_wait_generation: Generation,
        errno: i32,
        reason: WaitCancelReason,
        note: String,
    },
    CleanupBlockDriver {
        cleanup: BlockDriverCleanupId,
        io_cleanup: IoCleanupId,
        block_device: BlockDeviceObjectId,
        block_device_generation: Generation,
        backend: ContractObjectRef,
        reason: String,
        note: String,
    },
    RecordVirtioNetBackendObject {
        virtio_net_backend: VirtioNetBackendObjectId,
        name: String,
        packet_device: PacketDeviceObjectId,
        packet_device_generation: Generation,
        driver_binding: DriverStoreBindingId,
        driver_binding_generation: Generation,
        provider: String,
        profile: String,
        model: String,
        mtu: u32,
        rx_queue_depth: u32,
        tx_queue_depth: u32,
        mac: [u8; 6],
        frame_format_version: u32,
        max_payload_len: u32,
        device_features: u64,
        driver_features: u64,
        negotiated_features: u64,
        rx_queue_index: u16,
        tx_queue_index: u16,
        queue_size: u16,
        irq_vector: u16,
        note: String,
    },
    RecordNetworkRxInterrupt {
        rx_interrupt: NetworkRxInterruptId,
        virtio_net_backend: VirtioNetBackendObjectId,
        virtio_net_backend_generation: Generation,
        irq_event: IrqEventId,
        irq_event_generation: Generation,
        packet_device: PacketDeviceObjectId,
        packet_device_generation: Generation,
        rx_queue: PacketQueueObjectId,
        rx_queue_generation: Generation,
        ready_descriptors: u16,
        sequence: u64,
        note: String,
    },
    ResolveNetworkRxWait {
        resolution: NetworkRxWaitResolutionId,
        io_wait: IoWaitId,
        io_wait_generation: Generation,
        rx_interrupt: NetworkRxInterruptId,
        rx_interrupt_generation: Generation,
        note: String,
    },
    RecordNetworkTxCapabilityGate {
        tx_gate: NetworkTxCapabilityGateId,
        driver_store: StoreId,
        driver_store_generation: Generation,
        packet_descriptor: PacketDescriptorObjectId,
        packet_descriptor_generation: Generation,
        device_capability: DeviceCapabilityId,
        device_capability_generation: Generation,
        handle: CapabilityHandle,
        note: String,
    },
    RecordNetworkTxCompletion {
        completion: NetworkTxCompletionId,
        tx_gate: NetworkTxCapabilityGateId,
        tx_gate_generation: Generation,
        backend: ContractObjectRef,
        completion_sequence: u64,
        note: String,
    },
    RecordNetworkStackAdapter {
        adapter: NetworkStackAdapterId,
        backend: ContractObjectRef,
        packet_device: PacketDeviceObjectId,
        packet_device_generation: Generation,
        rx_queue: PacketQueueObjectId,
        rx_queue_generation: Generation,
        tx_queue: PacketQueueObjectId,
        tx_queue_generation: Generation,
        implementation: String,
        implementation_version: String,
        profile: String,
        medium: String,
        mac: [u8; 6],
        ipv4_addr: [u8; 4],
        ipv4_prefix_len: u8,
        mtu: u32,
        rx_queue_depth: u32,
        tx_queue_depth: u32,
        max_payload_len: u32,
        socket_capacity: u16,
        note: String,
    },
    RecordSocketObject {
        socket: SocketObjectId,
        adapter: NetworkStackAdapterId,
        adapter_generation: Generation,
        owner_store: StoreId,
        owner_store_generation: Generation,
        domain: u32,
        socket_type: u32,
        protocol: u32,
        note: String,
    },
    RecordEndpointObject {
        endpoint: EndpointObjectId,
        socket: SocketObjectId,
        socket_generation: Generation,
        local_addr: [u8; 4],
        local_port: u16,
        remote_addr: [u8; 4],
        remote_port: u16,
        note: String,
    },
    BindSocketEndpoint {
        operation_id: SocketOperationId,
        endpoint: EndpointObjectId,
        endpoint_generation: Generation,
        local_addr: [u8; 4],
        local_port: u16,
        sequence: u64,
        note: String,
    },
    ListenSocketEndpoint {
        operation_id: SocketOperationId,
        endpoint: EndpointObjectId,
        endpoint_generation: Generation,
        backlog: u16,
        sequence: u64,
        note: String,
    },
    ConnectSocketEndpoint {
        operation_id: SocketOperationId,
        endpoint: EndpointObjectId,
        endpoint_generation: Generation,
        remote_addr: [u8; 4],
        remote_port: u16,
        sequence: u64,
        note: String,
    },
    SendSocket {
        operation_id: SocketOperationId,
        endpoint: EndpointObjectId,
        endpoint_generation: Generation,
        byte_len: u32,
        sequence: u64,
        note: String,
    },
    RecvSocket {
        operation_id: SocketOperationId,
        endpoint: EndpointObjectId,
        endpoint_generation: Generation,
        byte_len: u32,
        sequence: u64,
        note: String,
    },
    RecordSocketWait {
        socket_wait: SocketWaitId,
        wait: WaitId,
        wait_generation: Generation,
        endpoint: EndpointObjectId,
        endpoint_generation: Generation,
        wait_kind: SemanticWaitKind,
        blocker: ContractObjectRef,
        note: String,
    },
    ResolveSocketWait {
        socket_wait: SocketWaitId,
        socket_wait_generation: Generation,
        ready_sequence: u64,
        byte_len: u32,
        note: String,
    },
    CancelSocketWait {
        socket_wait: SocketWaitId,
        socket_wait_generation: Generation,
        errno: i32,
        reason: WaitCancelReason,
        note: String,
    },
    RecordNetworkBackpressure {
        backpressure: NetworkBackpressureId,
        adapter: NetworkStackAdapterId,
        adapter_generation: Generation,
        packet_device: PacketDeviceObjectId,
        packet_device_generation: Generation,
        packet_queue: PacketQueueObjectId,
        packet_queue_generation: Generation,
        endpoint: Option<EndpointObjectId>,
        endpoint_generation: Option<Generation>,
        direction: PacketBufferDirection,
        reason: NetworkBackpressureReason,
        action: NetworkBackpressureAction,
        queue_depth: u32,
        queue_limit: u32,
        dropped_packets: u32,
        dropped_bytes: u32,
        sequence: u64,
        note: String,
    },
    CleanupNetworkDriver {
        cleanup: NetworkDriverCleanupId,
        io_cleanup: IoCleanupId,
        adapter: NetworkStackAdapterId,
        adapter_generation: Generation,
        packet_device: PacketDeviceObjectId,
        packet_device_generation: Generation,
        backend: ContractObjectRef,
        reason: String,
        note: String,
    },
    RecordNetworkGenerationAudit {
        audit: NetworkGenerationAuditId,
        adapter: NetworkStackAdapterId,
        adapter_generation: Generation,
        packet_device: PacketDeviceObjectId,
        packet_device_generation: Generation,
        packet_queue: PacketQueueObjectId,
        packet_queue_generation: Generation,
        packet_descriptor: PacketDescriptorObjectId,
        packet_descriptor_generation: Generation,
        packet_buffer: PacketBufferObjectId,
        packet_buffer_generation: Generation,
        dma_buffer: ContractObjectRef,
        device_capability: ContractObjectRef,
        rejected_packet_generation_probes: u32,
        rejected_dma_generation_probes: u32,
        note: String,
    },
    RecordNetworkFaultInjection {
        injection: NetworkFaultInjectionId,
        adapter: NetworkStackAdapterId,
        adapter_generation: Generation,
        packet_device: PacketDeviceObjectId,
        packet_device_generation: Generation,
        packet_queue: PacketQueueObjectId,
        packet_queue_generation: Generation,
        packet_descriptor: Option<PacketDescriptorObjectId>,
        packet_descriptor_generation: Option<Generation>,
        packet_buffer: Option<PacketBufferObjectId>,
        packet_buffer_generation: Option<Generation>,
        endpoint: Option<EndpointObjectId>,
        endpoint_generation: Option<Generation>,
        direction: PacketBufferDirection,
        kind: NetworkFaultInjectionKind,
        effect: NetworkFaultInjectionEffect,
        injected_packets: u32,
        dropped_packets: u32,
        error_packets: u32,
        error_code: String,
        sequence: u64,
        note: String,
    },
    RecordNetworkBenchmark {
        benchmark: NetworkBenchmarkId,
        scenario: String,
        adapter: NetworkStackAdapterId,
        adapter_generation: Generation,
        packet_device: PacketDeviceObjectId,
        packet_device_generation: Generation,
        tx_queue: PacketQueueObjectId,
        tx_queue_generation: Generation,
        rx_queue: PacketQueueObjectId,
        rx_queue_generation: Generation,
        tx_completion: NetworkTxCompletionId,
        tx_completion_generation: Generation,
        rx_wait_resolution: NetworkRxWaitResolutionId,
        rx_wait_resolution_generation: Generation,
        endpoint: EndpointObjectId,
        endpoint_generation: Generation,
        backpressure: Option<NetworkBackpressureId>,
        backpressure_generation: Option<Generation>,
        sample_packets: u32,
        sample_bytes: u64,
        tx_completed_packets: u32,
        rx_resolved_packets: u32,
        dropped_packets: u32,
        measured_nanos: u64,
        budget_nanos: u64,
        p50_latency_nanos: u64,
        p99_latency_nanos: u64,
        note: String,
    },
    RecordNetworkRecoveryBenchmark {
        benchmark: NetworkRecoveryBenchmarkId,
        scenario: String,
        cleanup: NetworkDriverCleanupId,
        cleanup_generation: Generation,
        io_cleanup: IoCleanupId,
        io_cleanup_generation: Generation,
        fault_injection: Option<NetworkFaultInjectionId>,
        fault_injection_generation: Option<Generation>,
        recovery_start_event: EventId,
        recovery_complete_event: EventId,
        cancelled_socket_waits: u32,
        revoked_packet_capabilities: u32,
        recovery_nanos: u64,
        budget_nanos: u64,
        note: String,
    },
    RecordBlockDeviceObject {
        block_device: BlockDeviceObjectId,
        name: String,
        device: DeviceObjectId,
        device_generation: Generation,
        sector_size: u32,
        sector_count: u64,
        read_only: bool,
        max_transfer_sectors: u32,
        note: String,
    },
    RecordBlockRangeObject {
        block_range: BlockRangeObjectId,
        block_device: BlockDeviceObjectId,
        block_device_generation: Generation,
        start_sector: u64,
        sector_count: u64,
        note: String,
    },
    RecordBlockRequestObject {
        block_request: BlockRequestObjectId,
        block_device: BlockDeviceObjectId,
        block_device_generation: Generation,
        block_range: BlockRangeObjectId,
        block_range_generation: Generation,
        operation: BlockRequestOperation,
        sequence: u64,
        note: String,
    },
    RecordBlockCompletionObject {
        block_completion: BlockCompletionObjectId,
        block_request: BlockRequestObjectId,
        block_request_generation: Generation,
        sequence: u64,
        completed_bytes: u64,
        status: BlockCompletionStatus,
        note: String,
    },
    RecordBlockWait {
        block_wait: BlockWaitId,
        wait: WaitId,
        wait_generation: Generation,
        block_request: BlockRequestObjectId,
        block_request_generation: Generation,
        note: String,
    },
    ResolveBlockWait {
        block_wait: BlockWaitId,
        block_wait_generation: Generation,
        block_completion: BlockCompletionObjectId,
        block_completion_generation: Generation,
        note: String,
    },
    CancelBlockWait {
        block_wait: BlockWaitId,
        block_wait_generation: Generation,
        errno: i32,
        reason: WaitCancelReason,
        note: String,
    },
    ApplyBlockPendingIoPolicy {
        policy: BlockPendingIoPolicyId,
        block_wait: BlockWaitId,
        block_wait_generation: Generation,
        action: BlockPendingIoAction,
        retry_request: Option<BlockRequestObjectId>,
        retry_request_generation: Option<Generation>,
        errno: i32,
        retry_attempt: u32,
        max_retries: u32,
        note: String,
    },
    RecordBlockRequestGenerationAudit {
        audit: BlockRequestGenerationAuditId,
        block_device: BlockDeviceObjectId,
        block_device_generation: Generation,
        block_range: BlockRangeObjectId,
        block_range_generation: Generation,
        block_request: BlockRequestObjectId,
        block_request_generation: Generation,
        backend: ContractObjectRef,
        dma_buffer: ContractObjectRef,
        rejected_completion_generation_probes: u32,
        rejected_wait_generation_probes: u32,
        rejected_dma_generation_probes: u32,
        rejected_queue_generation_probes: u32,
        note: String,
    },
    RecordBlockBenchmark {
        benchmark: BlockBenchmarkId,
        scenario: String,
        backend: ContractObjectRef,
        block_device: BlockDeviceObjectId,
        block_device_generation: Generation,
        block_range: BlockRangeObjectId,
        block_range_generation: Generation,
        read_path: BlockReadPathId,
        read_path_generation: Generation,
        write_path: BlockWritePathId,
        write_path_generation: Generation,
        request_queue: BlockRequestQueueId,
        request_queue_generation: Generation,
        block_dma_buffer: BlockDmaBufferId,
        block_dma_buffer_generation: Generation,
        sample_requests: u32,
        sample_bytes: u64,
        read_completed_requests: u32,
        write_completed_requests: u32,
        queue_completed_requests: u32,
        measured_nanos: u64,
        budget_nanos: u64,
        p50_latency_nanos: u64,
        p99_latency_nanos: u64,
        note: String,
    },
    RecordBlockRecoveryBenchmark {
        benchmark: BlockRecoveryBenchmarkId,
        scenario: String,
        cleanup: BlockDriverCleanupId,
        cleanup_generation: Generation,
        io_cleanup: IoCleanupId,
        io_cleanup_generation: Generation,
        recovery_start_event: EventId,
        recovery_complete_event: EventId,
        cancelled_block_waits: u32,
        cancelled_wait_tokens: u32,
        released_dma_buffers: u32,
        revoked_device_capabilities: u32,
        recovery_nanos: u64,
        budget_nanos: u64,
        note: String,
    },
    RecordTargetFeatureSet {
        feature_set: TargetFeatureSetId,
        name: String,
        discovery_source: String,
        target_profile: String,
        target_arch: String,
        base_isa: String,
        simd_abi: String,
        simd_supported: bool,
        vector_register_count: u16,
        vector_register_bits: u16,
        scalar_fallback: bool,
        unsupported_reason: String,
        note: String,
    },
    RecordVectorState {
        vector_state: VectorStateId,
        owner_activation: ContractObjectRef,
        owner_store: ContractObjectRef,
        code_object: ContractObjectRef,
        target_feature_set: ContractObjectRef,
        simd_abi: String,
        vector_register_count: u16,
        vector_register_bits: u16,
        register_bytes: u32,
        state: VectorStateState,
        note: String,
    },
    RecordSimdFaultInjection {
        injection: SimdFaultInjectionId,
        activation: ContractObjectRef,
        code_object: ContractObjectRef,
        trap: ContractObjectRef,
        target_feature_set: ContractObjectRef,
        vector_state: Option<ContractObjectRef>,
        kind: SimdFaultInjectionKind,
        effect: SimdFaultInjectionEffect,
        required_abi: String,
        vector_register_count: u16,
        vector_register_bits: u16,
        injected_faults: u32,
        note: String,
    },
    RecordSimdBenchmark {
        benchmark: SimdBenchmarkId,
        target_feature_set: ContractObjectRef,
        scalar_code_object: ContractObjectRef,
        vector_code_object: ContractObjectRef,
        simd_abi: String,
        vector_register_count: u16,
        vector_register_bits: u16,
        workload_units: u64,
        scalar_nanos: u64,
        vector_nanos: u64,
        speedup_milli: u64,
        context_overhead_nanos: u64,
        note: String,
    },
    RecordSimdContextSwitchBenchmark {
        benchmark: SimdContextSwitchBenchmarkId,
        preemption: ContractObjectRef,
        activation_resume: ContractObjectRef,
        saved_vector_state: ContractObjectRef,
        restored_vector_state: ContractObjectRef,
        target_feature_set: ContractObjectRef,
        simd_abi: String,
        vector_register_count: u16,
        vector_register_bits: u16,
        sample_count: u64,
        scalar_context_switch_nanos: u64,
        vector_context_switch_nanos: u64,
        overhead_nanos: u64,
        budget_nanos: u64,
        note: String,
    },
    RecordFramebufferObject {
        framebuffer: FramebufferObjectId,
        name: String,
        resource: ResourceId,
        resource_generation: Generation,
        width: u32,
        height: u32,
        stride_bytes: u32,
        pixel_format: String,
        byte_len: u64,
        note: String,
    },
    RecordDisplayObject {
        display: DisplayObjectId,
        name: String,
        framebuffer: FramebufferObjectId,
        framebuffer_generation: Generation,
        mode_name: String,
        width: u32,
        height: u32,
        refresh_millihz: u32,
        note: String,
    },
    RecordDisplayCapability {
        display_capability: DisplayCapabilityId,
        owner_store: StoreId,
        owner_store_generation: Generation,
        display: DisplayObjectId,
        display_generation: Generation,
        capability: CapabilityId,
        capability_generation: Generation,
        handle: CapabilityHandle,
        operations: Vec<String>,
        note: String,
    },
    RecordFramebufferWindowLease {
        framebuffer_window_lease: FramebufferWindowLeaseId,
        owner_store: StoreId,
        owner_store_generation: Generation,
        display_capability: DisplayCapabilityId,
        display_capability_generation: Generation,
        display: DisplayObjectId,
        display_generation: Generation,
        framebuffer: FramebufferObjectId,
        framebuffer_generation: Generation,
        x: u32,
        y: u32,
        width: u32,
        height: u32,
        byte_offset: u64,
        byte_len: u64,
        access: String,
        note: String,
    },
    RecordFramebufferMapping {
        framebuffer_mapping: FramebufferMappingId,
        owner_store: StoreId,
        owner_store_generation: Generation,
        framebuffer_window_lease: FramebufferWindowLeaseId,
        framebuffer_window_lease_generation: Generation,
        map_handle_slot: u32,
        map_handle_generation: u32,
        map_handle_tag: u64,
        x: u32,
        y: u32,
        width: u32,
        height: u32,
        byte_offset: u64,
        byte_len: u64,
        access: String,
        mode: String,
        note: String,
    },
    RecordFramebufferWrite {
        framebuffer_write: FramebufferWriteId,
        owner_store: StoreId,
        owner_store_generation: Generation,
        framebuffer_mapping: FramebufferMappingId,
        framebuffer_mapping_generation: Generation,
        x: u32,
        y: u32,
        width: u32,
        height: u32,
        byte_offset: u64,
        byte_len: u64,
        payload_digest: u64,
        note: String,
    },
    RecordFramebufferFlushRegion {
        framebuffer_flush_region: FramebufferFlushRegionId,
        owner_store: StoreId,
        owner_store_generation: Generation,
        framebuffer_write: FramebufferWriteId,
        framebuffer_write_generation: Generation,
        x: u32,
        y: u32,
        width: u32,
        height: u32,
        byte_offset: u64,
        byte_len: u64,
        payload_digest: u64,
        note: String,
    },
    RecordFramebufferDirtyRegion {
        framebuffer_dirty_region: FramebufferDirtyRegionId,
        owner_store: StoreId,
        owner_store_generation: Generation,
        framebuffer_write: FramebufferWriteId,
        framebuffer_write_generation: Generation,
        framebuffer_flush_region: Option<FramebufferFlushRegionId>,
        framebuffer_flush_region_generation: Option<Generation>,
        state: FramebufferDirtyRegionState,
        x: u32,
        y: u32,
        width: u32,
        height: u32,
        byte_offset: u64,
        byte_len: u64,
        payload_digest: u64,
        note: String,
    },
    RecordDisplayEventLog {
        display_event_log: DisplayEventLogId,
        owner_store: StoreId,
        owner_store_generation: Generation,
        framebuffer_dirty_region: FramebufferDirtyRegionId,
        framebuffer_dirty_region_generation: Generation,
        first_event: EventId,
        last_event: EventId,
        event_count: u64,
        flush_count: u64,
        dirty_region_count: u64,
        note: String,
    },
    CleanupDisplay {
        cleanup: DisplayCleanupId,
        owner_store: StoreId,
        owner_store_generation: Generation,
        display_capability: DisplayCapabilityId,
        display_capability_generation: Generation,
        display: DisplayObjectId,
        display_generation: Generation,
        framebuffer: FramebufferObjectId,
        framebuffer_generation: Generation,
        reason: String,
        note: String,
    },
    ValidateDisplaySnapshotBarrier {
        barrier: DisplaySnapshotBarrierId,
        owner_store: StoreId,
        owner_store_generation: Generation,
        display: DisplayObjectId,
        display_generation: Generation,
        framebuffer: FramebufferObjectId,
        framebuffer_generation: Generation,
        display_cleanup: Option<DisplayCleanupId>,
        display_cleanup_generation: Option<Generation>,
        reason: String,
        note: String,
    },
    RecordDisplayPanicLastFrame {
        panic_last_frame: DisplayPanicLastFrameId,
        owner_store: StoreId,
        owner_store_generation: Generation,
        display_snapshot_barrier: DisplaySnapshotBarrierId,
        display_snapshot_barrier_generation: Generation,
        display_event_log: DisplayEventLogId,
        display_event_log_generation: Generation,
        framebuffer_write: FramebufferWriteId,
        framebuffer_write_generation: Generation,
        framebuffer_flush_region: FramebufferFlushRegionId,
        framebuffer_flush_region_generation: Generation,
        payload_digest: u64,
        summary_digest: u64,
        summary_record_bytes: u32,
        panic_epoch: u64,
        panic_record_kind: String,
        raw_framebuffer_bytes_exported: bool,
        note: String,
    },
    RecordFramebufferBenchmark {
        benchmark: FramebufferBenchmarkId,
        scenario: String,
        owner_store: StoreId,
        owner_store_generation: Generation,
        display_capability: DisplayCapabilityId,
        display_capability_generation: Generation,
        framebuffer_write: FramebufferWriteId,
        framebuffer_write_generation: Generation,
        framebuffer_flush_region: FramebufferFlushRegionId,
        framebuffer_flush_region_generation: Generation,
        display_event_log: DisplayEventLogId,
        display_event_log_generation: Generation,
        display_snapshot_barrier: DisplaySnapshotBarrierId,
        display_snapshot_barrier_generation: Generation,
        sample_frames: u32,
        sample_bytes: u64,
        frame_area_pixels: u64,
        write_nanos: u64,
        flush_nanos: u64,
        measured_nanos: u64,
        budget_nanos: u64,
        p50_latency_nanos: u64,
        p99_latency_nanos: u64,
        note: String,
    },
    RecordQueueObject {
        queue: QueueObjectId,
        name: String,
        role: QueueObjectRole,
        queue_index: u16,
        depth: u32,
        device: DeviceObjectId,
        device_generation: Generation,
        note: String,
    },
    RecordDescriptorObject {
        descriptor: DescriptorObjectId,
        queue: QueueObjectId,
        queue_generation: Generation,
        slot: u16,
        access: DescriptorObjectAccess,
        length: u32,
        note: String,
    },
    RecordDmaBufferObject {
        dma_buffer: DmaBufferObjectId,
        descriptor: DescriptorObjectId,
        descriptor_generation: Generation,
        resource: ResourceId,
        resource_generation: Generation,
        access: DmaBufferObjectAccess,
        length: u32,
        note: String,
    },
    RecordMmioRegionObject {
        mmio_region: MmioRegionObjectId,
        device: DeviceObjectId,
        device_generation: Generation,
        resource: ResourceId,
        resource_generation: Generation,
        region_index: u16,
        offset: u64,
        length: u64,
        access: MmioRegionObjectAccess,
        note: String,
    },
    RecordIrqLineObject {
        irq_line: IrqLineObjectId,
        device: DeviceObjectId,
        device_generation: Generation,
        resource: ResourceId,
        resource_generation: Generation,
        irq_number: u32,
        trigger: IrqLineTrigger,
        polarity: IrqLinePolarity,
        note: String,
    },
    RecordIrqEvent {
        irq_event: IrqEventId,
        irq_line: IrqLineObjectId,
        irq_line_generation: Generation,
        device: DeviceObjectId,
        device_generation: Generation,
        driver_store: StoreId,
        driver_store_generation: Generation,
        sequence: u64,
        note: String,
    },
    RecordDeviceCapability {
        device_capability: DeviceCapabilityId,
        driver_store: StoreId,
        driver_store_generation: Generation,
        target: ContractObjectRef,
        class: CapabilityClass,
        operation: String,
        handle: CapabilityHandle,
        note: String,
    },
    BindDriverStore {
        binding: DriverStoreBindingId,
        driver_store: StoreId,
        driver_store_generation: Generation,
        device: DeviceObjectId,
        device_generation: Generation,
        device_capability: DeviceCapabilityId,
        device_capability_generation: Generation,
        note: String,
    },
    RecordIoWait {
        io_wait: IoWaitId,
        wait: WaitId,
        wait_generation: Generation,
        driver_store: StoreId,
        driver_store_generation: Generation,
        device: DeviceObjectId,
        device_generation: Generation,
        driver_binding: DriverStoreBindingId,
        driver_binding_generation: Generation,
        blocker: ContractObjectRef,
        note: String,
    },
    ResolveIoWait {
        io_wait: IoWaitId,
        io_wait_generation: Generation,
        irq_event: IrqEventId,
        irq_event_generation: Generation,
        note: String,
    },
    CancelIoWait {
        io_wait: IoWaitId,
        io_wait_generation: Generation,
        errno: i32,
        reason: WaitCancelReason,
        note: String,
    },
    CleanupIoDriver {
        cleanup: IoCleanupId,
        driver_store: StoreId,
        driver_store_generation: Generation,
        device: DeviceObjectId,
        device_generation: Generation,
        driver_binding: DriverStoreBindingId,
        driver_binding_generation: Generation,
        reason: String,
        note: String,
    },
    InjectIoFault {
        fault: IoFaultInjectionId,
        cleanup: IoCleanupId,
        driver_store: StoreId,
        driver_store_generation: Generation,
        device: DeviceObjectId,
        device_generation: Generation,
        driver_binding: DriverStoreBindingId,
        driver_binding_generation: Generation,
        target: ContractObjectRef,
        kind: IoFaultInjectionKind,
        note: String,
    },
    ValidateIoRuntime {
        report: IoValidationReportId,
        note: String,
    },
    ResumeActivation {
        resume: ActivationResumeId,
        scheduler_decision: SchedulerDecisionId,
        scheduler_decision_generation: Generation,
        activation: ActivationId,
        activation_generation: Generation,
        note: String,
    },
    RecordPreemptionLatencySample {
        sample: PreemptionLatencySampleId,
        timer_interrupt: TimerInterruptId,
        timer_interrupt_generation: Generation,
        preemption: PreemptionId,
        preemption_generation: Generation,
        scheduler_decision: SchedulerDecisionId,
        scheduler_decision_generation: Generation,
        activation_resume: ActivationResumeId,
        activation_resume_generation: Generation,
        measured_nanos: u64,
        budget_nanos: u64,
        note: String,
    },
    BlockActivationOnWait {
        activation_wait: ActivationWaitId,
        activation: ActivationId,
        activation_generation: Generation,
        wait: WaitId,
        kind: SemanticWaitKind,
        blockers: Vec<ContractObjectRef>,
        deadline: Option<u64>,
        restart_policy: RestartPolicy,
        note: String,
    },
    CancelActivationWait {
        activation_wait: ActivationWaitId,
        activation_wait_generation: Generation,
        wait_generation: Generation,
        errno: i32,
        reason: WaitCancelReason,
        note: String,
    },
    CleanupActivationForStoreFault {
        cleanup: ActivationCleanupId,
        store: StoreId,
        store_generation: Generation,
        activation: ActivationId,
        activation_generation: Generation,
        wait: Option<WaitId>,
        wait_generation: Option<Generation>,
        reason: String,
        note: String,
    },
    GrantCapability {
        subject: String,
        debug_object_label: String,
        object_ref: AuthorityObjectRef,
        operations: Vec<String>,
        lifetime: String,
        owner_store: Option<StoreId>,
        owner_store_generation: Option<Generation>,
        owner_task: Option<TaskId>,
        source: String,
        manifest_decl: bool,
    },
    RevokeCapability {
        cap: CapabilityId,
    },
    CreateWait {
        wait: WaitId,
        owner_task: Option<TaskId>,
        owner_store: Option<StoreId>,
        owner_store_generation: Option<Generation>,
        kind: SemanticWaitKind,
        generation: Generation,
        blockers: Vec<ContractObjectRef>,
        deadline: Option<u64>,
        restart_policy: RestartPolicy,
        saved_context: Option<String>,
    },
    ResolveWait {
        wait: WaitId,
        reason: String,
    },
    CancelWait {
        wait: WaitId,
        errno: i32,
        reason: WaitCancelReason,
    },
    RecordTrap {
        store: Option<StoreId>,
        task: Option<TaskId>,
        trap: TrapClass,
        detail: String,
    },
    BeginCleanup {
        cleanup: TransactionId,
        store: StoreId,
        generation: Generation,
        reason: String,
    },
    ApplyCleanupStep {
        cleanup: TransactionId,
        step: CleanupStep,
        target: ContractObjectRef,
        observed_generation: Generation,
    },
    CommitCleanup {
        cleanup: TransactionId,
    },
}

impl SemanticCommand {
    pub const fn name(&self) -> &'static str {
        match self {
            Self::RegisterHart { .. } => "register-hart",
            Self::SetHartState { .. } => "set-hart-state",
            Self::BindHartCurrentActivation { .. } => "bind-hart-current-activation",
            Self::ClearHartCurrentActivation { .. } => "clear-hart-current-activation",
            Self::CreateRuntimeActivation { .. } => "create-runtime-activation",
            Self::CreateRunnableQueue { .. } => "create-runnable-queue",
            Self::BindRunnableQueueOwner { .. } => "bind-runnable-queue-owner",
            Self::EnqueueRunnable { .. } => "enqueue-runnable",
            Self::DequeueRunnable { .. } => "dequeue-runnable",
            Self::CreateActivationContext { .. } => "create-activation-context",
            Self::UpdateActivationContextVectorState { .. } => {
                "update-activation-context-vector-state"
            }
            Self::EnableLazyVectorState { .. } => "enable-lazy-vector-state",
            Self::CaptureSavedContext { .. } => "capture-saved-context",
            Self::SavePreemptedContext { .. } => "save-preempted-context",
            Self::SaveDirtyVectorStateOnPreempt { .. } => "save-dirty-vector-state-on-preempt",
            Self::RecordTimerInterrupt { .. } => "record-timer-interrupt",
            Self::RecordIpiEvent { .. } => "record-ipi-event",
            Self::RemotePreemptActivation { .. } => "remote-preempt-activation",
            Self::RemoteParkHart { .. } => "remote-park-hart",
            Self::PreemptActivation { .. } => "preempt-activation",
            Self::RecordSchedulerDecision { .. } => "record-scheduler-decision",
            Self::RecordCrossHartSchedulerDecision { .. } => "record-cross-hart-scheduler-decision",
            Self::MigrateRunnableActivation { .. } => "migrate-runnable-activation",
            Self::RecordSmpSafePoint { .. } => "record-smp-safe-point",
            Self::CompleteStopTheWorldRendezvous { .. } => "complete-stop-the-world-rendezvous",
            Self::ValidateSmpCodePublishBarrier { .. } => "validate-smp-code-publish-barrier",
            Self::ValidateSmpCleanupQuiescence { .. } => "validate-smp-cleanup-quiescence",
            Self::ValidateSmpSnapshotBarrier { .. } => "validate-smp-snapshot-barrier",
            Self::RecordSmpStressRun { .. } => "record-smp-stress-run",
            Self::RecordSmpScalingBenchmark { .. } => "record-smp-scaling-benchmark",
            Self::RecordIntegratedSmpPreemptionCleanup { .. } => {
                "record-integrated-smp-preemption-cleanup"
            }
            Self::RecordIntegratedSmpNetworkFault { .. } => "record-integrated-smp-network-fault",
            Self::RecordIntegratedDiskPreemptFault { .. } => "record-integrated-disk-preempt-fault",
            Self::RecordIntegratedSimdMigration { .. } => "record-integrated-simd-migration",
            Self::RecordIntegratedNetworkDiskIo { .. } => "record-integrated-network-disk-io",
            Self::RecordIntegratedDisplaySchedulerLoad { .. } => {
                "record-integrated-display-scheduler-load"
            }
            Self::RecordIntegratedSnapshotIoLeaseBarrier { .. } => {
                "record-integrated-snapshot-io-lease-barrier"
            }
            Self::RecordIntegratedCodePublishSmpWorkload { .. } => {
                "record-integrated-code-publish-smp-workload"
            }
            Self::RecordIntegratedDisplayPanic { .. } => "record-integrated-display-panic",
            Self::RecordIntegratedOsctlTraceReplay { .. } => "record-integrated-osctl-trace-replay",
            Self::RecordDeviceObject { .. } => "record-device-object",
            Self::RecordPacketDeviceObject { .. } => "record-packet-device-object",
            Self::RecordPacketBufferObject { .. } => "record-packet-buffer-object",
            Self::RecordPacketQueueObject { .. } => "record-packet-queue-object",
            Self::RecordPacketDescriptorObject { .. } => "record-packet-descriptor-object",
            Self::RecordFakeNetBackendObject { .. } => "record-fake-net-backend-object",
            Self::RecordFakeBlockBackendObject { .. } => "record-fake-block-backend-object",
            Self::RecordVirtioBlkBackendObject { .. } => "record-virtio-blk-backend-object",
            Self::RecordBlockReadPath { .. } => "record-block-read-path",
            Self::RecordBlockWritePath { .. } => "record-block-write-path",
            Self::RecordBlockRequestQueue { .. } => "record-block-request-queue",
            Self::RecordBlockDmaBuffer { .. } => "record-block-dma-buffer",
            Self::RecordBlockPageObject { .. } => "record-block-page-object",
            Self::RecordBufferCacheObject { .. } => "record-buffer-cache-object",
            Self::RecordFileObject { .. } => "record-file-object",
            Self::RecordDirectoryObject { .. } => "record-directory-object",
            Self::RecordFatAdapterObject { .. } => "record-fat-adapter-object",
            Self::RecordExt4AdapterObject { .. } => "record-ext4-adapter-object",
            Self::RecordFileHandleCapability { .. } => "record-file-handle-capability",
            Self::RecordFsWait { .. } => "record-fs-wait",
            Self::ResolveFsWait { .. } => "resolve-fs-wait",
            Self::CancelFsWait { .. } => "cancel-fs-wait",
            Self::CleanupBlockDriver { .. } => "cleanup-block-driver",
            Self::RecordVirtioNetBackendObject { .. } => "record-virtio-net-backend-object",
            Self::RecordNetworkRxInterrupt { .. } => "record-network-rx-interrupt",
            Self::ResolveNetworkRxWait { .. } => "resolve-network-rx-wait",
            Self::RecordNetworkTxCapabilityGate { .. } => "record-network-tx-capability-gate",
            Self::RecordNetworkTxCompletion { .. } => "record-network-tx-completion",
            Self::RecordNetworkStackAdapter { .. } => "record-network-stack-adapter",
            Self::RecordSocketObject { .. } => "record-socket-object",
            Self::RecordEndpointObject { .. } => "record-endpoint-object",
            Self::BindSocketEndpoint { .. } => "bind-socket-endpoint",
            Self::ListenSocketEndpoint { .. } => "listen-socket-endpoint",
            Self::ConnectSocketEndpoint { .. } => "connect-socket-endpoint",
            Self::SendSocket { .. } => "send-socket",
            Self::RecvSocket { .. } => "recv-socket",
            Self::RecordSocketWait { .. } => "record-socket-wait",
            Self::ResolveSocketWait { .. } => "resolve-socket-wait",
            Self::CancelSocketWait { .. } => "cancel-socket-wait",
            Self::RecordNetworkBackpressure { .. } => "record-network-backpressure",
            Self::CleanupNetworkDriver { .. } => "cleanup-network-driver",
            Self::RecordNetworkGenerationAudit { .. } => "record-network-generation-audit",
            Self::RecordNetworkFaultInjection { .. } => "record-network-fault-injection",
            Self::RecordNetworkBenchmark { .. } => "record-network-benchmark",
            Self::RecordNetworkRecoveryBenchmark { .. } => "record-network-recovery-benchmark",
            Self::RecordBlockDeviceObject { .. } => "record-block-device-object",
            Self::RecordBlockRangeObject { .. } => "record-block-range-object",
            Self::RecordBlockRequestObject { .. } => "record-block-request-object",
            Self::RecordBlockCompletionObject { .. } => "record-block-completion-object",
            Self::RecordBlockWait { .. } => "record-block-wait",
            Self::ResolveBlockWait { .. } => "resolve-block-wait",
            Self::CancelBlockWait { .. } => "cancel-block-wait",
            Self::ApplyBlockPendingIoPolicy { .. } => "apply-block-pending-io-policy",
            Self::RecordBlockRequestGenerationAudit { .. } => {
                "record-block-request-generation-audit"
            }
            Self::RecordBlockBenchmark { .. } => "record-block-benchmark",
            Self::RecordBlockRecoveryBenchmark { .. } => "record-block-recovery-benchmark",
            Self::RecordTargetFeatureSet { .. } => "record-target-feature-set",
            Self::RecordVectorState { .. } => "record-vector-state",
            Self::RecordSimdFaultInjection { .. } => "record-simd-fault-injection",
            Self::RecordSimdBenchmark { .. } => "record-simd-benchmark",
            Self::RecordSimdContextSwitchBenchmark { .. } => "record-simd-context-switch-benchmark",
            Self::RecordFramebufferObject { .. } => "record-framebuffer-object",
            Self::RecordDisplayObject { .. } => "record-display-object",
            Self::RecordDisplayCapability { .. } => "record-display-capability",
            Self::RecordFramebufferWindowLease { .. } => "record-framebuffer-window-lease",
            Self::RecordFramebufferMapping { .. } => "record-framebuffer-mapping",
            Self::RecordFramebufferWrite { .. } => "record-framebuffer-write",
            Self::RecordFramebufferFlushRegion { .. } => "record-framebuffer-flush-region",
            Self::RecordFramebufferDirtyRegion { .. } => "record-framebuffer-dirty-region",
            Self::RecordDisplayEventLog { .. } => "record-display-event-log",
            Self::CleanupDisplay { .. } => "cleanup-display",
            Self::ValidateDisplaySnapshotBarrier { .. } => "validate-display-snapshot-barrier",
            Self::RecordDisplayPanicLastFrame { .. } => "record-display-panic-last-frame",
            Self::RecordFramebufferBenchmark { .. } => "record-framebuffer-benchmark",
            Self::RecordQueueObject { .. } => "record-queue-object",
            Self::RecordDescriptorObject { .. } => "record-descriptor-object",
            Self::RecordDmaBufferObject { .. } => "record-dma-buffer-object",
            Self::RecordMmioRegionObject { .. } => "record-mmio-region-object",
            Self::RecordIrqLineObject { .. } => "record-irq-line-object",
            Self::RecordIrqEvent { .. } => "record-irq-event",
            Self::RecordDeviceCapability { .. } => "record-device-capability",
            Self::BindDriverStore { .. } => "bind-driver-store",
            Self::RecordIoWait { .. } => "record-io-wait",
            Self::ResolveIoWait { .. } => "resolve-io-wait",
            Self::CancelIoWait { .. } => "cancel-io-wait",
            Self::CleanupIoDriver { .. } => "cleanup-io-driver",
            Self::InjectIoFault { .. } => "inject-io-fault",
            Self::ValidateIoRuntime { .. } => "validate-io-runtime",
            Self::ResumeActivation { .. } => "resume-activation",
            Self::RecordPreemptionLatencySample { .. } => "record-preemption-latency-sample",
            Self::BlockActivationOnWait { .. } => "block-activation-on-wait",
            Self::CancelActivationWait { .. } => "cancel-activation-wait",
            Self::CleanupActivationForStoreFault { .. } => "cleanup-activation-for-store-fault",
            Self::GrantCapability { .. } => "grant-capability",
            Self::RevokeCapability { .. } => "revoke-capability",
            Self::CreateWait { .. } => "create-wait",
            Self::ResolveWait { .. } => "resolve-wait",
            Self::CancelWait { .. } => "cancel-wait",
            Self::RecordTrap { .. } => "record-trap",
            Self::BeginCleanup { .. } => "begin-cleanup",
            Self::ApplyCleanupStep { .. } => "apply-cleanup-step",
            Self::CommitCleanup { .. } => "commit-cleanup",
        }
    }
}
