use super::*;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ContractObjectKind {
    Hart,
    Task,
    RunnableQueue,
    ActivationContext,
    SavedContext,
    TimerInterrupt,
    IpiEvent,
    RemotePreempt,
    RemotePark,
    Preemption,
    SchedulerDecision,
    CrossHartSchedulerDecision,
    ActivationMigration,
    SmpSafePoint,
    StopTheWorldRendezvous,
    SmpCodePublishBarrier,
    SmpCleanupQuiescence,
    SmpSnapshotBarrier,
    SmpStressRun,
    SmpScalingBenchmark,
    IntegratedSmpPreemptionCleanup,
    IntegratedSmpNetworkFault,
    IntegratedDiskPreemptFault,
    IntegratedSimdMigration,
    IntegratedNetworkDiskIo,
    IntegratedDisplaySchedulerLoad,
    IntegratedSnapshotIoLeaseBarrier,
    IntegratedCodePublishSmpWorkload,
    IntegratedDisplayPanic,
    IntegratedOsctlTraceReplay,
    DeviceObject,
    QueueObject,
    DescriptorObject,
    DmaBufferObject,
    MmioRegionObject,
    IrqLineObject,
    IrqEvent,
    DeviceCapability,
    DriverStoreBinding,
    IoWait,
    IoCleanup,
    IoFaultInjection,
    IoValidationReport,
    PacketDeviceObject,
    PacketBufferObject,
    PacketQueueObject,
    PacketDescriptorObject,
    FakeNetBackendObject,
    VirtioNetBackendObject,
    NetworkRxInterrupt,
    NetworkRxWaitResolution,
    NetworkTxCapabilityGate,
    NetworkTxCompletion,
    NetworkStackAdapter,
    SocketObject,
    EndpointObject,
    SocketOperation,
    SocketWait,
    NetworkBackpressure,
    NetworkDriverCleanup,
    NetworkGenerationAudit,
    NetworkFaultInjection,
    NetworkBenchmark,
    NetworkRecoveryBenchmark,
    BlockDeviceObject,
    BlockRangeObject,
    BlockRequestObject,
    BlockCompletionObject,
    BlockWait,
    FakeBlockBackendObject,
    VirtioBlkBackendObject,
    BlockReadPath,
    BlockWritePath,
    BlockRequestQueue,
    BlockDmaBuffer,
    BlockPageObject,
    BufferCacheObject,
    FileObject,
    DirectoryObject,
    FatAdapterObject,
    Ext4AdapterObject,
    FileHandleCapability,
    FsWait,
    BlockDriverCleanup,
    BlockPendingIoPolicy,
    BlockRequestGenerationAudit,
    BlockBenchmark,
    BlockRecoveryBenchmark,
    TargetFeatureSet,
    VectorState,
    SimdFaultInjection,
    SimdBenchmark,
    SimdContextSwitchBenchmark,
    FramebufferObject,
    DisplayObject,
    DisplayCapability,
    FramebufferWindowLease,
    FramebufferMapping,
    FramebufferWrite,
    FramebufferFlushRegion,
    FramebufferDirtyRegion,
    DisplayEventLog,
    DisplayCleanup,
    DisplaySnapshotBarrier,
    DisplayPanicLastFrame,
    FramebufferBenchmark,
    ActivationResume,
    ActivationWait,
    ActivationCleanup,
    PreemptionLatencySample,
    HartEventAttribution,
    Resource,
    Artifact,
    CodeObject,
    Store,
    FaultDomain,
    Activation,
    Trap,
    Hostcall,
    Capability,
    WaitToken,
    CleanupTransaction,
    MemoryObject,
    GuestAddressSpace,
    VmaRegion,
    PageObject,
    EventLog,
    Tombstone,
    ExternalObject,
}

impl ContractObjectKind {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Hart => "hart",
            Self::Task => "task",
            Self::RunnableQueue => "runnable-queue",
            Self::ActivationContext => "activation-context",
            Self::SavedContext => "saved-context",
            Self::TimerInterrupt => "timer-interrupt",
            Self::IpiEvent => "ipi-event",
            Self::RemotePreempt => "remote-preempt",
            Self::RemotePark => "remote-park",
            Self::Preemption => "preemption",
            Self::SchedulerDecision => "scheduler-decision",
            Self::CrossHartSchedulerDecision => "cross-hart-scheduler-decision",
            Self::ActivationMigration => "activation-migration",
            Self::SmpSafePoint => "smp-safe-point",
            Self::StopTheWorldRendezvous => "stop-the-world-rendezvous",
            Self::SmpCodePublishBarrier => "smp-code-publish-barrier",
            Self::SmpCleanupQuiescence => "smp-cleanup-quiescence",
            Self::SmpSnapshotBarrier => "smp-snapshot-barrier",
            Self::SmpStressRun => "smp-stress-run",
            Self::SmpScalingBenchmark => "smp-scaling-benchmark",
            Self::IntegratedSmpPreemptionCleanup => "integrated-smp-preemption-cleanup",
            Self::IntegratedSmpNetworkFault => "integrated-smp-network-fault",
            Self::IntegratedDiskPreemptFault => "integrated-disk-preempt-fault",
            Self::IntegratedSimdMigration => "integrated-simd-migration",
            Self::IntegratedNetworkDiskIo => "integrated-network-disk-io",
            Self::IntegratedDisplaySchedulerLoad => "integrated-display-scheduler-load",
            Self::IntegratedSnapshotIoLeaseBarrier => "integrated-snapshot-io-lease-barrier",
            Self::IntegratedCodePublishSmpWorkload => "integrated-code-publish-smp-workload",
            Self::IntegratedDisplayPanic => "integrated-display-panic",
            Self::IntegratedOsctlTraceReplay => "integrated-osctl-trace-replay",
            Self::DeviceObject => "device-object",
            Self::QueueObject => "queue-object",
            Self::DescriptorObject => "descriptor-object",
            Self::DmaBufferObject => "dma-buffer-object",
            Self::MmioRegionObject => "mmio-region-object",
            Self::IrqLineObject => "irq-line-object",
            Self::IrqEvent => "irq-event",
            Self::DeviceCapability => "device-capability",
            Self::DriverStoreBinding => "driver-store-binding",
            Self::IoWait => "io-wait",
            Self::IoCleanup => "io-cleanup",
            Self::IoFaultInjection => "io-fault-injection",
            Self::IoValidationReport => "io-validation-report",
            Self::PacketDeviceObject => "packet-device-object",
            Self::PacketBufferObject => "packet-buffer-object",
            Self::PacketQueueObject => "packet-queue-object",
            Self::PacketDescriptorObject => "packet-descriptor-object",
            Self::FakeNetBackendObject => "fake-net-backend-object",
            Self::VirtioNetBackendObject => "virtio-net-backend-object",
            Self::NetworkRxInterrupt => "network-rx-interrupt",
            Self::NetworkRxWaitResolution => "network-rx-wait-resolution",
            Self::NetworkTxCapabilityGate => "network-tx-capability-gate",
            Self::NetworkTxCompletion => "network-tx-completion",
            Self::NetworkStackAdapter => "network-stack-adapter",
            Self::SocketObject => "socket-object",
            Self::EndpointObject => "endpoint-object",
            Self::SocketOperation => "socket-operation",
            Self::SocketWait => "socket-wait",
            Self::NetworkBackpressure => "network-backpressure",
            Self::NetworkDriverCleanup => "network-driver-cleanup",
            Self::NetworkGenerationAudit => "network-generation-audit",
            Self::NetworkFaultInjection => "network-fault-injection",
            Self::NetworkBenchmark => "network-benchmark",
            Self::NetworkRecoveryBenchmark => "network-recovery-benchmark",
            Self::BlockDeviceObject => "block-device-object",
            Self::BlockRangeObject => "block-range-object",
            Self::BlockRequestObject => "block-request-object",
            Self::BlockCompletionObject => "block-completion-object",
            Self::BlockWait => "block-wait",
            Self::FakeBlockBackendObject => "fake-block-backend-object",
            Self::VirtioBlkBackendObject => "virtio-blk-backend-object",
            Self::BlockReadPath => "block-read-path",
            Self::BlockWritePath => "block-write-path",
            Self::BlockRequestQueue => "block-request-queue",
            Self::BlockDmaBuffer => "block-dma-buffer",
            Self::BlockPageObject => "block-page-object",
            Self::BufferCacheObject => "buffer-cache-object",
            Self::FileObject => "file-object",
            Self::DirectoryObject => "directory-object",
            Self::FatAdapterObject => "fat-adapter-object",
            Self::Ext4AdapterObject => "ext4-adapter-object",
            Self::FileHandleCapability => "file-handle-capability",
            Self::FsWait => "fs-wait",
            Self::BlockDriverCleanup => "block-driver-cleanup",
            Self::BlockPendingIoPolicy => "block-pending-io-policy",
            Self::BlockRequestGenerationAudit => "block-request-generation-audit",
            Self::BlockBenchmark => "block-benchmark",
            Self::BlockRecoveryBenchmark => "block-recovery-benchmark",
            Self::TargetFeatureSet => "target-feature-set",
            Self::VectorState => "vector-state",
            Self::SimdFaultInjection => "simd-fault-injection",
            Self::SimdBenchmark => "simd-benchmark",
            Self::SimdContextSwitchBenchmark => "simd-context-switch-benchmark",
            Self::FramebufferObject => "framebuffer-object",
            Self::DisplayObject => "display-object",
            Self::DisplayCapability => "display-capability",
            Self::FramebufferWindowLease => "framebuffer-window-lease",
            Self::FramebufferMapping => "framebuffer-mapping",
            Self::FramebufferWrite => "framebuffer-write",
            Self::FramebufferFlushRegion => "framebuffer-flush-region",
            Self::FramebufferDirtyRegion => "framebuffer-dirty-region",
            Self::DisplayEventLog => "display-event-log",
            Self::DisplayCleanup => "display-cleanup",
            Self::DisplaySnapshotBarrier => "display-snapshot-barrier",
            Self::DisplayPanicLastFrame => "display-panic-last-frame",
            Self::FramebufferBenchmark => "framebuffer-benchmark",
            Self::ActivationResume => "activation-resume",
            Self::ActivationWait => "activation-wait",
            Self::ActivationCleanup => "activation-cleanup",
            Self::PreemptionLatencySample => "preemption-latency",
            Self::HartEventAttribution => "hart-event-attribution",
            Self::Resource => "resource",
            Self::Artifact => "artifact",
            Self::CodeObject => "code-object",
            Self::Store => "store",
            Self::FaultDomain => "fault-domain",
            Self::Activation => "activation",
            Self::Trap => "trap",
            Self::Hostcall => "hostcall",
            Self::Capability => "capability",
            Self::WaitToken => "wait-token",
            Self::CleanupTransaction => "cleanup-transaction",
            Self::MemoryObject => "memory-object",
            Self::GuestAddressSpace => "guest-address-space",
            Self::VmaRegion => "vma-region",
            Self::PageObject => "page-object",
            Self::EventLog => "event-log",
            Self::Tombstone => "tombstone",
            Self::ExternalObject => "external-object",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ContractObjectRef {
    pub kind: ContractObjectKind,
    pub id: u64,
    pub generation: Generation,
}

impl ContractObjectRef {
    pub const fn new(kind: ContractObjectKind, id: u64, generation: Generation) -> Self {
        Self { kind, id, generation }
    }

    pub fn summary(self) -> String {
        format!("{}:{}@{}", self.kind.as_str(), self.id, self.generation)
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TombstoneRecord {
    pub kind: ContractObjectKind,
    pub id: u64,
    pub generation: Generation,
    pub died_at: EventId,
    pub reason: String,
}

impl TombstoneRecord {
    pub fn new(
        kind: ContractObjectKind,
        id: u64,
        generation: Generation,
        died_at: EventId,
        reason: &str,
    ) -> Self {
        Self { kind, id, generation, died_at, reason: reason.to_string() }
    }

    pub const fn object_ref(&self) -> ContractObjectRef {
        ContractObjectRef::new(self.kind, self.id, self.generation)
    }

    pub fn summary(&self) -> String {
        format!(
            "tombstone kind={} id={} generation={} died_at={} reason={}",
            self.kind.as_str(),
            self.id,
            self.generation,
            self.died_at,
            self.reason
        )
    }
}
