[unstable]
bindeps = true

[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "target-feature=-bulk-memory,-multivalue,-reference-types,-sign-ext,-nontrapping-fptoint",
]

[alias]
kernel = "build -p kernel --target x86_64-unknown-none"
run-vm = "run -p runner --"
check-wasm = "check -p console_service -p devfs_service -p driver_virtio_net -p epoll_service -p futex_service -p handoff-component -p linux_socket_service -p linux_syscall -p net_core -p procfs_service -p vfs_service --target wasm32-unknown-unknown"
wasm = "build -p console_service -p devfs_service -p driver_virtio_net -p epoll_service -p futex_service -p handoff-component -p linux_socket_service -p linux_syscall -p net_core -p procfs_service -p vfs_service --target wasm32-unknown-unknown"
