//! Digest-pinned, non-authoritative bootstrap input for `visa-ownershipd`.
//!
//! The bootstrap file is an explicit launch input, not a release trust root.
//! Release installation/provenance and exact-tag evidence remain separate
//! gates. The daemon accepts this input only when its exact RFC 8785 JCS bytes
//! match a lowercase SHA-256 supplied separately on argv.

use std::{
    fmt,
    fs::File,
    io::{self, Read},
    path::{Component, Path, PathBuf},
};

use joint_handoff_core::{Identity, JointIssuerSet, ReceiptIssuerIdentity};
use rustix::{
    fs::{FileType, Mode, OFlags, fstat, open},
    process::geteuid,
};
use serde::{Deserialize, Deserializer, Serialize, Serializer, de};
use serde_json_canonicalizer::to_vec as to_jcs_vec;
use sha2::{Digest as _, Sha256};
use visa_local_rpc::{
    MAX_INNER_REQUEST_BYTES, WireValidation,
    common::{
        AgentBinding, AgentRole, BootId, CohortId, IssuerId, IssuerKeyId, IssuerLogId,
        LogicalIncarnation, ProcessNonce, ProductVersion, RuntimeSessionId, ServiceIncarnation,
    },
};
use visa_ownership_service::{
    OwnershipServiceIdentity, PinnedLocalReceiptAuthenticator, StoreBinding, StoreBootstrap,
    StoreLimits,
};

/// Exact schema accepted by this O2 bootstrap reader.
pub const BOOTSTRAP_SCHEMA: &str = "visa.ownershipd.bootstrap.v1";

/// Hard cap applied before JSON parsing.
pub const MAX_BOOTSTRAP_BYTES: usize = 1024 * 1024;

const SQLITE_PAGE_SIZE: u64 = 4096;
const MAX_DATABASE_PATH_BYTES: usize = 4096;

/// Whether this process may create the exact configured store when it is absent.
///
/// `CreateIfMissingExact` does not perform adoption. The caller must first use
/// `symlink_metadata`: only `NotFound` may select O1 create-new, while an existing
/// path selects reopen and every create/reopen race fails in O1.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StoreOpenPolicy {
    /// Create with the pinned identity only after an exact `NotFound` observation.
    CreateIfMissingExact,
    /// Refuse creation and reopen the already initialized store only.
    ReopenExisting,
}

/// Exact process identity and executable digest admitted for one agent role.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PinnedAgent {
    pub binding: AgentBinding,
    pub executable_sha256: [u8; 32],
}

/// Typed bootstrap values used to construct the O1 store and peer-admission policy.
///
/// This value is a digest-pinned launch input. It is intentionally not described
/// as a release trust root or as executable provenance.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RuntimeConfig {
    pub store_open_policy: StoreOpenPolicy,
    pub database_path: PathBuf,
    pub store_binding: StoreBinding,
    pub ownership_identity: OwnershipServiceIdentity,
    pub store_limits: StoreLimits,
    pub joint_issuers: JointIssuerSet,
    pub source_agent: PinnedAgent,
    pub destination_agent: PinnedAgent,
}

impl RuntimeConfig {
    /// Returns the exact configured identity for an agent role.
    pub const fn allowed_agent(&self, role: AgentRole) -> &PinnedAgent {
        match role {
            AgentRole::Source => &self.source_agent,
            AgentRole::Destination => &self.destination_agent,
        }
    }

    /// Builds an O1 bootstrap using the fresh nonce generated by this process.
    ///
    /// `create_identity` must be `None` for reopen, or the exact pinned identity
    /// after a caller has observed `NotFound` under `CreateIfMissingExact`.
    pub fn store_bootstrap(
        &self,
        process_nonce: ProcessNonce,
        create_identity: Option<OwnershipServiceIdentity>,
    ) -> Result<StoreBootstrap, ConfigError> {
        process_nonce
            .validate()
            .map_err(|_| ConfigError::InvalidField("ownership process nonce"))?;
        if create_identity.is_some_and(|identity| identity != self.ownership_identity) {
            return Err(ConfigError::InvalidField("ownership create identity"));
        }
        if self.store_open_policy == StoreOpenPolicy::ReopenExisting && create_identity.is_some() {
            return Err(ConfigError::InvalidField("store open policy"));
        }
        Ok(StoreBootstrap {
            binding: self.store_binding,
            create_identity,
            process_nonce,
            limits: self.store_limits,
        })
    }

    /// Reconstructs the validated same-UID local receipt policy.
    pub fn receipt_authenticator(&self) -> Result<PinnedLocalReceiptAuthenticator, ConfigError> {
        PinnedLocalReceiptAuthenticator::new(self.joint_issuers)
            .ok_or(ConfigError::InvalidField("joint issuers"))
    }
}

/// A validated runtime configuration and the digest of its exact canonical bytes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LoadedRuntimeConfig {
    pub runtime: RuntimeConfig,
    pub canonical_sha256: [u8; 32],
}

/// Bootstrap loading failure.
#[derive(Debug)]
pub enum ConfigError {
    InvalidDigestPin,
    Io { operation: &'static str, source: io::Error },
    InsecureFile,
    TooLarge,
    SizeChanged,
    DigestMismatch { expected: [u8; 32], observed: [u8; 32] },
    Json(serde_json::Error),
    NonCanonical,
    WrongSchema,
    InvalidField(&'static str),
}

impl fmt::Display for ConfigError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidDigestPin => {
                formatter.write_str("bootstrap SHA-256 argv pin is not 64 lowercase hex digits")
            }
            Self::Io { operation, source } => {
                write!(formatter, "cannot {operation} bootstrap file: {source}")
            }
            Self::InsecureFile => formatter
                .write_str("bootstrap must be one regular euid-owned single-link mode-0600 file"),
            Self::TooLarge => {
                write!(formatter, "bootstrap exceeds the {MAX_BOOTSTRAP_BYTES}-byte input limit")
            }
            Self::SizeChanged => {
                formatter.write_str("bootstrap size changed while it was being read")
            }
            Self::DigestMismatch { expected, observed } => write!(
                formatter,
                "bootstrap SHA-256 mismatch: expected {}, observed {}",
                encode_lower_hex(expected),
                encode_lower_hex(observed)
            ),
            Self::Json(source) => write!(formatter, "bootstrap JSON is invalid: {source}"),
            Self::NonCanonical => formatter.write_str("bootstrap is not exact RFC 8785 JCS JSON"),
            Self::WrongSchema => {
                write!(formatter, "bootstrap schema must be exactly {BOOTSTRAP_SCHEMA}")
            }
            Self::InvalidField(field) => write!(formatter, "invalid bootstrap {field}"),
        }
    }
}

impl std::error::Error for ConfigError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::Json(source) => Some(source),
            Self::InvalidDigestPin
            | Self::InsecureFile
            | Self::TooLarge
            | Self::SizeChanged
            | Self::DigestMismatch { .. }
            | Self::NonCanonical
            | Self::WrongSchema
            | Self::InvalidField(_) => None,
        }
    }
}

/// Securely loads one exact canonical bootstrap file pinned by an argv digest.
pub fn load_digest_pinned(
    path: impl AsRef<Path>,
    expected_sha256_argv: &str,
) -> Result<LoadedRuntimeConfig, ConfigError> {
    let expected =
        parse_lower_hex::<32>(expected_sha256_argv).map_err(|_| ConfigError::InvalidDigestPin)?;
    let bytes = read_secure_bootstrap(path.as_ref())?;
    let observed: [u8; 32] = Sha256::digest(&bytes).into();
    if observed != expected {
        return Err(ConfigError::DigestMismatch { expected, observed });
    }

    let document: BootstrapDocument = serde_json::from_slice(&bytes).map_err(ConfigError::Json)?;
    let canonical = to_jcs_vec(&document).map_err(ConfigError::Json)?;
    if canonical != bytes {
        return Err(ConfigError::NonCanonical);
    }
    let runtime = document.into_runtime()?;
    Ok(LoadedRuntimeConfig { runtime, canonical_sha256: observed })
}

fn read_secure_bootstrap(path: &Path) -> Result<Vec<u8>, ConfigError> {
    let descriptor = open(
        path,
        OFlags::RDONLY | OFlags::CLOEXEC | OFlags::NOFOLLOW | OFlags::NONBLOCK,
        Mode::empty(),
    )
    .map_err(|source| ConfigError::Io { operation: "open", source: source.into() })?;
    let initial_size = verify_private_regular_fd(&descriptor)?;
    if initial_size > MAX_BOOTSTRAP_BYTES as u64 {
        return Err(ConfigError::TooLarge);
    }

    let mut file: File = descriptor.into();
    let mut bytes = Vec::with_capacity(initial_size as usize);
    (&mut file)
        .take(MAX_BOOTSTRAP_BYTES as u64 + 1)
        .read_to_end(&mut bytes)
        .map_err(|source| ConfigError::Io { operation: "read", source })?;
    if bytes.len() > MAX_BOOTSTRAP_BYTES {
        return Err(ConfigError::TooLarge);
    }
    let final_size = verify_private_regular_fd(&file)?;
    if initial_size != final_size || final_size != bytes.len() as u64 {
        return Err(ConfigError::SizeChanged);
    }
    Ok(bytes)
}

fn verify_private_regular_fd(fd: &impl std::os::fd::AsFd) -> Result<u64, ConfigError> {
    let metadata = fstat(fd)
        .map_err(|source| ConfigError::Io { operation: "inspect", source: source.into() })?;
    let permissions = Mode::from_raw_mode(metadata.st_mode)
        & (Mode::RWXU | Mode::RWXG | Mode::RWXO | Mode::SUID | Mode::SGID | Mode::SVTX);
    if FileType::from_raw_mode(metadata.st_mode) != FileType::RegularFile
        || metadata.st_uid != geteuid().as_raw()
        || metadata.st_nlink != 1
        || permissions != Mode::RUSR | Mode::WUSR
    {
        return Err(ConfigError::InsecureFile);
    }
    u64::try_from(metadata.st_size).map_err(|_| ConfigError::InsecureFile)
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct BootstrapDocument {
    schema: String,
    store_open_policy: StoreOpenPolicy,
    database_path: String,
    store_binding: StoreBindingDocument,
    ownership_identity: OwnershipIdentityDocument,
    store_limits: StoreLimitsDocument,
    joint_issuers: JointIssuerSetDocument,
    source_agent: AgentDocument,
    destination_agent: AgentDocument,
}

impl BootstrapDocument {
    fn into_runtime(self) -> Result<RuntimeConfig, ConfigError> {
        if self.schema != BOOTSTRAP_SCHEMA {
            return Err(ConfigError::WrongSchema);
        }
        let database_path = validate_database_path(&self.database_path)?;
        let store_binding = self.store_binding.into_typed()?;
        let ownership_identity = self.ownership_identity.into_typed()?;
        let store_limits = self.store_limits.into_typed()?;
        let joint_issuers = self.joint_issuers.into_typed();
        let authenticator = PinnedLocalReceiptAuthenticator::new(joint_issuers)
            .ok_or(ConfigError::InvalidField("joint issuers"))?;
        let expected_ownership_issuer = ReceiptIssuerIdentity {
            issuer: Identity::from_bytes(ownership_identity.issuer.0),
            issuer_incarnation: Identity::from_bytes(ownership_identity.service_incarnation.0),
            key_id: Identity::from_bytes(ownership_identity.key_id.0),
            log_id: Identity::from_bytes(ownership_identity.log_namespace.0),
        };
        if authenticator.ownership_namespace() != expected_ownership_issuer {
            return Err(ConfigError::InvalidField("ownership issuer binding"));
        }

        let source_agent = self.source_agent.into_typed()?;
        let destination_agent = self.destination_agent.into_typed()?;
        validate_agent(&source_agent, AgentRole::Source, store_binding)?;
        validate_agent(&destination_agent, AgentRole::Destination, store_binding)?;

        Ok(RuntimeConfig {
            store_open_policy: self.store_open_policy,
            database_path,
            store_binding,
            ownership_identity,
            store_limits,
            joint_issuers,
            source_agent,
            destination_agent,
        })
    }
}

fn validate_database_path(value: &str) -> Result<PathBuf, ConfigError> {
    if value.is_empty() || value.len() > MAX_DATABASE_PATH_BYTES || value.as_bytes().contains(&0) {
        return Err(ConfigError::InvalidField("database path"));
    }
    let path = PathBuf::from(value);
    if !path.is_absolute()
        || path.file_name().is_none()
        || !path.components().all(|part| matches!(part, Component::RootDir | Component::Normal(_)))
    {
        return Err(ConfigError::InvalidField("database path"));
    }
    Ok(path)
}

fn validate_agent(
    agent: &PinnedAgent,
    expected_role: AgentRole,
    store_binding: StoreBinding,
) -> Result<(), ConfigError> {
    agent.binding.validate().map_err(|_| ConfigError::InvalidField("agent binding"))?;
    if agent.binding.role != expected_role {
        return Err(ConfigError::InvalidField("agent role"));
    }
    if agent.binding.cohort != store_binding.cohort
        || agent.binding.boot != store_binding.boot
        || agent.binding.runtime_session != store_binding.runtime_session
    {
        return Err(ConfigError::InvalidField("agent store binding"));
    }
    if agent.executable_sha256 == [0; 32] {
        return Err(ConfigError::InvalidField("agent executable sha256"));
    }
    Ok(())
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct StoreBindingDocument {
    cohort: LowerHex<16>,
    boot: LowerHex<16>,
    runtime_session: LowerHex<16>,
}

impl StoreBindingDocument {
    fn into_typed(self) -> Result<StoreBinding, ConfigError> {
        let binding = StoreBinding {
            cohort: CohortId::from_bytes(self.cohort.0),
            boot: BootId::from_bytes(self.boot.0),
            runtime_session: RuntimeSessionId::from_bytes(self.runtime_session.0),
        };
        binding
            .cohort
            .validate()
            .and_then(|()| binding.boot.validate())
            .and_then(|()| binding.runtime_session.validate())
            .map_err(|_| ConfigError::InvalidField("store binding"))?;
        Ok(binding)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct OwnershipIdentityDocument {
    service_incarnation: LowerHex<16>,
    issuer: LowerHex<16>,
    key_id: LowerHex<16>,
    log_namespace: LowerHex<16>,
}

impl OwnershipIdentityDocument {
    fn into_typed(self) -> Result<OwnershipServiceIdentity, ConfigError> {
        let identity = OwnershipServiceIdentity {
            service_incarnation: ServiceIncarnation::from_bytes(self.service_incarnation.0),
            issuer: IssuerId::from_bytes(self.issuer.0),
            key_id: IssuerKeyId::from_bytes(self.key_id.0),
            log_namespace: IssuerLogId::from_bytes(self.log_namespace.0),
        };
        identity
            .service_incarnation
            .validate()
            .and_then(|()| identity.issuer.validate())
            .and_then(|()| identity.key_id.validate())
            .and_then(|()| identity.log_namespace.validate())
            .map_err(|_| ConfigError::InvalidField("ownership identity"))?;
        Ok(identity)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct StoreLimitsDocument {
    max_exchanges: u64,
    max_exchange_bytes: u64,
    max_database_bytes: u64,
}

impl StoreLimitsDocument {
    fn into_typed(self) -> Result<StoreLimits, ConfigError> {
        if self.max_exchanges == 0
            || self.max_exchange_bytes < 2 * MAX_INNER_REQUEST_BYTES as u64
            || self.max_database_bytes < 1024 * 1024
            || !self.max_database_bytes.is_multiple_of(SQLITE_PAGE_SIZE)
            || self.max_exchanges > i64::MAX as u64
            || self.max_exchange_bytes > i64::MAX as u64
            || self.max_database_bytes > i64::MAX as u64
        {
            return Err(ConfigError::InvalidField("store limits"));
        }
        Ok(StoreLimits {
            max_exchanges: self.max_exchanges,
            max_exchange_bytes: self.max_exchange_bytes,
            max_database_bytes: self.max_database_bytes,
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct JointIssuerSetDocument {
    ownership: ReceiptIssuerDocument,
    visa_source: ReceiptIssuerDocument,
    visa_destination: ReceiptIssuerDocument,
    effect_closure: ReceiptIssuerDocument,
}

impl JointIssuerSetDocument {
    fn into_typed(self) -> JointIssuerSet {
        JointIssuerSet {
            ownership: self.ownership.into_typed(),
            visa_source: self.visa_source.into_typed(),
            visa_destination: self.visa_destination.into_typed(),
            effect_closure: self.effect_closure.into_typed(),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct ReceiptIssuerDocument {
    issuer: LowerHex<16>,
    issuer_incarnation: LowerHex<16>,
    key_id: LowerHex<16>,
    log_id: LowerHex<16>,
}

impl ReceiptIssuerDocument {
    fn into_typed(self) -> ReceiptIssuerIdentity {
        ReceiptIssuerIdentity {
            issuer: Identity::from_bytes(self.issuer.0),
            issuer_incarnation: Identity::from_bytes(self.issuer_incarnation.0),
            key_id: Identity::from_bytes(self.key_id.0),
            log_id: Identity::from_bytes(self.log_id.0),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct AgentDocument {
    binding: AgentBindingDocument,
    executable_sha256: LowerHex<32>,
}

impl AgentDocument {
    fn into_typed(self) -> Result<PinnedAgent, ConfigError> {
        Ok(PinnedAgent {
            binding: self.binding.into_typed()?,
            executable_sha256: self.executable_sha256.0,
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct AgentBindingDocument {
    product_version: ProductVersionDocument,
    cohort: LowerHex<16>,
    boot: LowerHex<16>,
    runtime_session: LowerHex<16>,
    role: AgentRoleDocument,
    logical_incarnation: LowerHex<16>,
    process_nonce: LowerHex<16>,
    process_generation: u64,
}

impl AgentBindingDocument {
    fn into_typed(self) -> Result<AgentBinding, ConfigError> {
        let binding = AgentBinding {
            product_version: self.product_version.into_typed(),
            cohort: CohortId::from_bytes(self.cohort.0),
            boot: BootId::from_bytes(self.boot.0),
            runtime_session: RuntimeSessionId::from_bytes(self.runtime_session.0),
            role: self.role.into_typed(),
            logical_incarnation: LogicalIncarnation::from_bytes(self.logical_incarnation.0),
            process_nonce: ProcessNonce::from_bytes(self.process_nonce.0),
            process_generation: self.process_generation,
        };
        binding.validate().map_err(|_| ConfigError::InvalidField("agent binding"))?;
        Ok(binding)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct ProductVersionDocument {
    major: u16,
    minor: u16,
    patch: u16,
}

impl ProductVersionDocument {
    const fn into_typed(self) -> ProductVersion {
        ProductVersion { major: self.major, minor: self.minor, patch: self.patch }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
enum AgentRoleDocument {
    Source,
    Destination,
}

impl AgentRoleDocument {
    const fn into_typed(self) -> AgentRole {
        match self {
            Self::Source => AgentRole::Source,
            Self::Destination => AgentRole::Destination,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct LowerHex<const N: usize>([u8; N]);

impl<const N: usize> Serialize for LowerHex<N> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&encode_lower_hex(&self.0))
    }
}

impl<'de, const N: usize> Deserialize<'de> for LowerHex<N> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        parse_lower_hex(&value).map(Self).map_err(de::Error::custom)
    }
}

fn parse_lower_hex<const N: usize>(value: &str) -> Result<[u8; N], &'static str> {
    if value.len() != N.checked_mul(2).ok_or("hex length overflow")? {
        return Err("wrong lowercase hex length");
    }
    let mut output = [0_u8; N];
    for (index, pair) in value.as_bytes().chunks_exact(2).enumerate() {
        output[index] = decode_lower_nibble(pair[0])? * 16 + decode_lower_nibble(pair[1])?;
    }
    Ok(output)
}

fn decode_lower_nibble(value: u8) -> Result<u8, &'static str> {
    match value {
        b'0'..=b'9' => Ok(value - b'0'),
        b'a'..=b'f' => Ok(value - b'a' + 10),
        _ => Err("hex must use lowercase ASCII digits"),
    }
}

fn encode_lower_hex(bytes: &[u8]) -> String {
    const DIGITS: &[u8; 16] = b"0123456789abcdef";
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        encoded.push(char::from(DIGITS[usize::from(byte >> 4)]));
        encoded.push(char::from(DIGITS[usize::from(byte & 0x0f)]));
    }
    encoded
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        io::{Seek, SeekFrom, Write},
        os::unix::fs::{PermissionsExt, symlink},
    };

    use serde_json::Value;
    use tempfile::{NamedTempFile, tempdir};
    use visa_local_rpc::common::PRODUCT_VERSION;

    use super::*;

    fn lower16(value: u8) -> LowerHex<16> {
        LowerHex([value; 16])
    }

    fn issuer(base: u8) -> ReceiptIssuerDocument {
        ReceiptIssuerDocument {
            issuer: lower16(base),
            issuer_incarnation: lower16(base + 1),
            key_id: lower16(base + 2),
            log_id: lower16(base + 3),
        }
    }

    fn agent(role: AgentRoleDocument, logical: u8, nonce: u8) -> AgentDocument {
        AgentDocument {
            binding: AgentBindingDocument {
                product_version: ProductVersionDocument {
                    major: PRODUCT_VERSION.major,
                    minor: PRODUCT_VERSION.minor,
                    patch: PRODUCT_VERSION.patch,
                },
                cohort: lower16(1),
                boot: lower16(2),
                runtime_session: lower16(3),
                role,
                logical_incarnation: lower16(logical),
                process_nonce: lower16(nonce),
                process_generation: 1,
            },
            executable_sha256: LowerHex([0x9a; 32]),
        }
    }

    fn document(policy: StoreOpenPolicy) -> BootstrapDocument {
        let ownership = issuer(10);
        BootstrapDocument {
            schema: BOOTSTRAP_SCHEMA.to_owned(),
            store_open_policy: policy,
            database_path: "/home/test/.local/state/visa/0.1/ownership.sqlite".to_owned(),
            store_binding: StoreBindingDocument {
                cohort: lower16(1),
                boot: lower16(2),
                runtime_session: lower16(3),
            },
            ownership_identity: OwnershipIdentityDocument {
                service_incarnation: ownership.issuer_incarnation,
                issuer: ownership.issuer,
                key_id: ownership.key_id,
                log_namespace: ownership.log_id,
            },
            store_limits: StoreLimitsDocument {
                max_exchanges: 65_536,
                max_exchange_bytes: 256 * 1024 * 1024,
                max_database_bytes: 512 * 1024 * 1024,
            },
            joint_issuers: JointIssuerSetDocument {
                ownership,
                visa_source: issuer(30),
                visa_destination: issuer(50),
                effect_closure: issuer(70),
            },
            source_agent: agent(AgentRoleDocument::Source, 90, 91),
            destination_agent: agent(AgentRoleDocument::Destination, 92, 93),
        }
    }

    fn canonical(document: &BootstrapDocument) -> Vec<u8> {
        to_jcs_vec(document).expect("canonical bootstrap")
    }

    fn pin(bytes: &[u8]) -> String {
        encode_lower_hex(&<[u8; 32]>::from(Sha256::digest(bytes)))
    }

    fn write_private(bytes: &[u8]) -> NamedTempFile {
        let mut file = NamedTempFile::new().expect("temporary bootstrap");
        file.write_all(bytes).expect("write bootstrap");
        file.as_file_mut().flush().expect("flush bootstrap");
        file.as_file_mut().seek(SeekFrom::Start(0)).expect("rewind bootstrap");
        fs::set_permissions(file.path(), fs::Permissions::from_mode(0o600))
            .expect("private bootstrap mode");
        file
    }

    #[test]
    fn loads_exact_jcs_and_builds_create_or_reopen_bootstrap_with_fresh_nonce() {
        let bytes = canonical(&document(StoreOpenPolicy::CreateIfMissingExact));
        let file = write_private(&bytes);
        let loaded = load_digest_pinned(file.path(), &pin(&bytes)).expect("load bootstrap");

        assert_eq!(loaded.canonical_sha256, <[u8; 32]>::from(Sha256::digest(&bytes)));
        assert_eq!(loaded.runtime.allowed_agent(AgentRole::Source).binding.role, AgentRole::Source);
        assert_eq!(
            loaded.runtime.allowed_agent(AgentRole::Destination).executable_sha256,
            [0x9a; 32]
        );
        assert!(loaded.runtime.receipt_authenticator().is_ok());

        let create = loaded
            .runtime
            .store_bootstrap(ProcessNonce::from_u128(100), Some(loaded.runtime.ownership_identity))
            .expect("create bootstrap");
        assert_eq!(create.create_identity, Some(loaded.runtime.ownership_identity));
        assert_eq!(create.process_nonce, ProcessNonce::from_u128(100));

        let reopen = loaded
            .runtime
            .store_bootstrap(ProcessNonce::from_u128(101), None)
            .expect("reopen bootstrap");
        assert_eq!(reopen.create_identity, None);
        assert_eq!(reopen.process_nonce, ProcessNonce::from_u128(101));
    }

    #[test]
    fn reopen_policy_rejects_creation_and_create_identity_must_be_exact() {
        let bytes = canonical(&document(StoreOpenPolicy::ReopenExisting));
        let file = write_private(&bytes);
        let loaded = load_digest_pinned(file.path(), &pin(&bytes)).expect("load bootstrap");
        assert!(matches!(
            loaded.runtime.store_bootstrap(
                ProcessNonce::from_u128(100),
                Some(loaded.runtime.ownership_identity)
            ),
            Err(ConfigError::InvalidField("store open policy"))
        ));

        let mut substituted = loaded.runtime.ownership_identity;
        substituted.issuer = IssuerId::from_u128(999);
        assert!(matches!(
            loaded.runtime.store_bootstrap(ProcessNonce::from_u128(100), Some(substituted)),
            Err(ConfigError::InvalidField("ownership create identity"))
        ));
        assert!(matches!(
            loaded.runtime.store_bootstrap(ProcessNonce::ZERO, None),
            Err(ConfigError::InvalidField("ownership process nonce"))
        ));
    }

    #[test]
    fn rejects_wrong_pin_and_noncanonical_or_unknown_json() {
        let bytes = canonical(&document(StoreOpenPolicy::CreateIfMissingExact));
        let file = write_private(&bytes);
        assert!(matches!(
            load_digest_pinned(file.path(), &"0".repeat(64)),
            Err(ConfigError::DigestMismatch { .. })
        ));
        assert!(matches!(
            load_digest_pinned(file.path(), &"A".repeat(64)),
            Err(ConfigError::InvalidDigestPin)
        ));

        let mut with_newline = bytes.clone();
        with_newline.push(b'\n');
        let file = write_private(&with_newline);
        assert!(matches!(
            load_digest_pinned(file.path(), &pin(&with_newline)),
            Err(ConfigError::NonCanonical)
        ));

        let mut value: Value = serde_json::from_slice(&bytes).expect("bootstrap value");
        value
            .as_object_mut()
            .expect("bootstrap object")
            .insert("unexpected".to_owned(), Value::Bool(true));
        let unknown = to_jcs_vec(&value).expect("canonical unknown-field input");
        let file = write_private(&unknown);
        assert!(matches!(
            load_digest_pinned(file.path(), &pin(&unknown)),
            Err(ConfigError::Json(_))
        ));
    }

    #[test]
    fn rejects_uppercase_identity_and_wrong_schema_or_binding() {
        let bytes = canonical(&document(StoreOpenPolicy::CreateIfMissingExact));
        let mut value: Value = serde_json::from_slice(&bytes).expect("bootstrap value");
        value["store_binding"]["cohort"] = Value::String("AA".repeat(16));
        let uppercase = to_jcs_vec(&value).expect("canonical uppercase input");
        let file = write_private(&uppercase);
        assert!(matches!(
            load_digest_pinned(file.path(), &pin(&uppercase)),
            Err(ConfigError::Json(_))
        ));

        let mut wrong_schema = document(StoreOpenPolicy::CreateIfMissingExact);
        wrong_schema.schema = "visa.ownershipd.bootstrap.v2".to_owned();
        let bytes = canonical(&wrong_schema);
        let file = write_private(&bytes);
        assert!(matches!(
            load_digest_pinned(file.path(), &pin(&bytes)),
            Err(ConfigError::WrongSchema)
        ));

        let mut wrong_binding = document(StoreOpenPolicy::CreateIfMissingExact);
        wrong_binding.destination_agent.binding.boot = lower16(99);
        let bytes = canonical(&wrong_binding);
        let file = write_private(&bytes);
        assert!(matches!(
            load_digest_pinned(file.path(), &pin(&bytes)),
            Err(ConfigError::InvalidField("agent store binding"))
        ));
    }

    #[test]
    fn rejects_insecure_symlink_hardlink_mode_and_oversize_inputs() {
        let bytes = canonical(&document(StoreOpenPolicy::CreateIfMissingExact));

        let mode = write_private(&bytes);
        fs::set_permissions(mode.path(), fs::Permissions::from_mode(0o640)).expect("weaken mode");
        assert!(matches!(
            load_digest_pinned(mode.path(), &pin(&bytes)),
            Err(ConfigError::InsecureFile)
        ));

        let special_mode = write_private(&bytes);
        fs::set_permissions(special_mode.path(), fs::Permissions::from_mode(0o4600))
            .expect("set special mode");
        assert!(matches!(
            load_digest_pinned(special_mode.path(), &pin(&bytes)),
            Err(ConfigError::InsecureFile)
        ));

        let source = write_private(&bytes);
        let root = tempdir().expect("temporary link directory");
        let hardlink = root.path().join("hardlink.json");
        fs::hard_link(source.path(), &hardlink).expect("create hardlink");
        assert!(matches!(
            load_digest_pinned(source.path(), &pin(&bytes)),
            Err(ConfigError::InsecureFile)
        ));

        let target = write_private(&bytes);
        let symlink_path = root.path().join("symlink.json");
        symlink(target.path(), &symlink_path).expect("create symlink");
        assert!(matches!(
            load_digest_pinned(&symlink_path, &pin(&bytes)),
            Err(ConfigError::Io { operation: "open", .. })
        ));

        let oversized = vec![b' '; MAX_BOOTSTRAP_BYTES + 1];
        let file = write_private(&oversized);
        assert!(matches!(
            load_digest_pinned(file.path(), &pin(&oversized)),
            Err(ConfigError::TooLarge)
        ));
    }
}
