use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;

use super::*;

#[derive(Clone, Debug)]
pub struct SemanticGraph {
    harts: Vec<HartRecord>,
    tasks: Vec<TaskRecord>,
    runtime_activations: Vec<RuntimeActivationRecord>,
    runnable_queues: Vec<RunnableQueueRecord>,
    activation_contexts: Vec<ActivationContextRecord>,
    saved_contexts: Vec<SavedContextRecord>,
    timer_interrupts: Vec<TimerInterruptRecord>,
    ipi_events: Vec<IpiEventRecord>,
    remote_preempts: Vec<RemotePreemptRecord>,
    remote_parks: Vec<RemoteParkRecord>,
    preemptions: Vec<PreemptionRecord>,
    scheduler_decisions: Vec<SchedulerDecisionRecord>,
    cross_hart_scheduler_decisions: Vec<CrossHartSchedulerDecisionRecord>,
    activation_migrations: Vec<ActivationMigrationRecord>,
    smp_safe_points: Vec<SmpSafePointRecord>,
    stop_the_world_rendezvous: Vec<StopTheWorldRendezvousRecord>,
    smp_code_publish_barriers: Vec<SmpCodePublishBarrierRecord>,
    smp_cleanup_quiescence: Vec<SmpCleanupQuiescenceRecord>,
    smp_snapshot_barriers: Vec<SmpSnapshotBarrierRecord>,
    smp_stress_runs: Vec<SmpStressRunRecord>,
    smp_scaling_benchmarks: Vec<SmpScalingBenchmarkRecord>,
    device_objects: Vec<DeviceObjectRecord>,
    queue_objects: Vec<QueueObjectRecord>,
    descriptor_objects: Vec<DescriptorObjectRecord>,
    dma_buffer_objects: Vec<DmaBufferObjectRecord>,
    mmio_region_objects: Vec<MmioRegionObjectRecord>,
    irq_line_objects: Vec<IrqLineObjectRecord>,
    irq_events: Vec<IrqEventRecord>,
    device_capabilities: Vec<DeviceCapabilityRecord>,
    driver_store_bindings: Vec<DriverStoreBindingRecord>,
    io_waits: Vec<IoWaitRecord>,
    io_cleanups: Vec<IoCleanupRecord>,
    io_fault_injections: Vec<IoFaultInjectionRecord>,
    io_validation_reports: Vec<IoValidationReportRecord>,
    packet_device_objects: Vec<PacketDeviceObjectRecord>,
    packet_buffer_objects: Vec<PacketBufferObjectRecord>,
    packet_queue_objects: Vec<PacketQueueObjectRecord>,
    packet_descriptors: Vec<PacketDescriptorObjectRecord>,
    fake_net_backends: Vec<FakeNetBackendObjectRecord>,
    virtio_net_backends: Vec<VirtioNetBackendObjectRecord>,
    network_rx_interrupts: Vec<NetworkRxInterruptRecord>,
    network_rx_wait_resolutions: Vec<NetworkRxWaitResolutionRecord>,
    network_tx_capability_gates: Vec<NetworkTxCapabilityGateRecord>,
    network_tx_completions: Vec<NetworkTxCompletionRecord>,
    network_stack_adapters: Vec<NetworkStackAdapterRecord>,
    socket_objects: Vec<SocketObjectRecord>,
    endpoint_objects: Vec<EndpointObjectRecord>,
    socket_operations: Vec<SocketOperationRecord>,
    socket_waits: Vec<SocketWaitRecord>,
    network_backpressures: Vec<NetworkBackpressureRecord>,
    network_benchmarks: Vec<NetworkBenchmarkRecord>,
    network_recovery_benchmarks: Vec<NetworkRecoveryBenchmarkRecord>,
    network_driver_cleanups: Vec<NetworkDriverCleanupRecord>,
    network_generation_audits: Vec<NetworkGenerationAuditRecord>,
    network_fault_injections: Vec<NetworkFaultInjectionRecord>,
    block_device_objects: Vec<BlockDeviceObjectRecord>,
    block_range_objects: Vec<BlockRangeObjectRecord>,
    block_request_objects: Vec<BlockRequestObjectRecord>,
    block_completion_objects: Vec<BlockCompletionObjectRecord>,
    block_waits: Vec<BlockWaitRecord>,
    fake_block_backends: Vec<FakeBlockBackendObjectRecord>,
    virtio_blk_backends: Vec<VirtioBlkBackendObjectRecord>,
    block_read_paths: Vec<BlockReadPathRecord>,
    block_write_paths: Vec<BlockWritePathRecord>,
    block_request_queues: Vec<BlockRequestQueueRecord>,
    block_dma_buffers: Vec<BlockDmaBufferRecord>,
    block_page_objects: Vec<BlockPageObjectRecord>,
    buffer_cache_objects: Vec<BufferCacheObjectRecord>,
    file_objects: Vec<FileObjectRecord>,
    directory_objects: Vec<DirectoryObjectRecord>,
    fat_adapter_objects: Vec<FatAdapterObjectRecord>,
    ext4_adapter_objects: Vec<Ext4AdapterObjectRecord>,
    file_handle_capabilities: Vec<FileHandleCapabilityRecord>,
    fs_waits: Vec<FsWaitRecord>,
    block_driver_cleanups: Vec<BlockDriverCleanupRecord>,
    block_pending_io_policies: Vec<BlockPendingIoPolicyRecord>,
    block_request_generation_audits: Vec<BlockRequestGenerationAuditRecord>,
    block_benchmarks: Vec<BlockBenchmarkRecord>,
    block_recovery_benchmarks: Vec<BlockRecoveryBenchmarkRecord>,
    target_feature_sets: Vec<TargetFeatureSetRecord>,
    vector_states: Vec<VectorStateRecord>,
    simd_fault_injections: Vec<SimdFaultInjectionRecord>,
    simd_benchmarks: Vec<SimdBenchmarkRecord>,
    simd_context_switch_benchmarks: Vec<SimdContextSwitchBenchmarkRecord>,
    framebuffer_objects: Vec<FramebufferObjectRecord>,
    display_objects: Vec<DisplayObjectRecord>,
    display_capabilities: Vec<DisplayCapabilityRecord>,
    framebuffer_window_leases: Vec<FramebufferWindowLeaseRecord>,
    framebuffer_mappings: Vec<FramebufferMappingRecord>,
    framebuffer_writes: Vec<FramebufferWriteRecord>,
    framebuffer_flush_regions: Vec<FramebufferFlushRegionRecord>,
    framebuffer_dirty_regions: Vec<FramebufferDirtyRegionRecord>,
    display_event_logs: Vec<DisplayEventLogRecord>,
    activation_resumes: Vec<ActivationResumeRecord>,
    activation_waits: Vec<ActivationWaitRecord>,
    activation_cleanups: Vec<ActivationCleanupRecord>,
    preemption_latency_samples: Vec<PreemptionLatencySampleRecord>,
    hart_event_attributions: Vec<HartEventAttributionRecord>,
    resources: Vec<ResourceRecord>,
    authority_bindings: Vec<AuthorityBindingRecord>,
    waits: Vec<WaitRecord>,
    fault_domains: Vec<FaultDomainRecord>,
    stores: Vec<StoreRecord>,
    transactions: Vec<SemanticTransactionRecord>,
    fast_path_plans: Vec<FastPathPlanRecord>,
    boundaries: Vec<BoundaryRecord>,
    artifact_verifications: Vec<ArtifactVerificationRecord>,
    store_activations: Vec<StoreActivationRecord>,
    command_results: Vec<CommandResult>,
    capabilities: CapabilityLedger,
    event_log: EventLog,
    next_resource_id: ResourceId,
    next_runtime_activation_id: ActivationId,
    next_runnable_queue_id: RunnableQueueId,
    next_activation_context_id: ActivationContextId,
    next_saved_context_id: SavedContextId,
    next_timer_interrupt_id: TimerInterruptId,
    next_ipi_event_id: IpiEventId,
    next_remote_preempt_id: RemotePreemptId,
    next_remote_park_id: RemoteParkId,
    next_preemption_id: PreemptionId,
    next_scheduler_decision_id: SchedulerDecisionId,
    next_cross_hart_scheduler_decision_id: CrossHartSchedulerDecisionId,
    next_activation_migration_id: ActivationMigrationId,
    next_smp_safe_point_id: SmpSafePointId,
    next_stop_the_world_rendezvous_id: StopTheWorldRendezvousId,
    next_smp_code_publish_barrier_id: SmpCodePublishBarrierId,
    next_smp_cleanup_quiescence_id: SmpCleanupQuiescenceId,
    next_smp_snapshot_barrier_id: SmpSnapshotBarrierId,
    next_smp_stress_run_id: SmpStressRunId,
    next_smp_scaling_benchmark_id: SmpScalingBenchmarkId,
    next_device_object_id: DeviceObjectId,
    next_queue_object_id: QueueObjectId,
    next_descriptor_object_id: DescriptorObjectId,
    next_dma_buffer_object_id: DmaBufferObjectId,
    next_mmio_region_object_id: MmioRegionObjectId,
    next_irq_line_object_id: IrqLineObjectId,
    next_irq_event_id: IrqEventId,
    next_device_capability_id: DeviceCapabilityId,
    next_driver_store_binding_id: DriverStoreBindingId,
    next_io_wait_id: IoWaitId,
    next_io_cleanup_id: IoCleanupId,
    next_io_fault_injection_id: IoFaultInjectionId,
    next_io_validation_report_id: IoValidationReportId,
    next_packet_device_object_id: PacketDeviceObjectId,
    next_packet_buffer_object_id: PacketBufferObjectId,
    next_packet_queue_object_id: PacketQueueObjectId,
    next_packet_descriptor_object_id: PacketDescriptorObjectId,
    next_fake_net_backend_object_id: FakeNetBackendObjectId,
    next_virtio_net_backend_object_id: VirtioNetBackendObjectId,
    next_network_rx_interrupt_id: NetworkRxInterruptId,
    next_network_rx_wait_resolution_id: NetworkRxWaitResolutionId,
    next_network_tx_capability_gate_id: NetworkTxCapabilityGateId,
    next_network_tx_completion_id: NetworkTxCompletionId,
    next_network_stack_adapter_id: NetworkStackAdapterId,
    next_socket_object_id: SocketObjectId,
    next_endpoint_object_id: EndpointObjectId,
    next_socket_operation_id: SocketOperationId,
    next_socket_wait_id: SocketWaitId,
    next_network_backpressure_id: NetworkBackpressureId,
    next_network_benchmark_id: NetworkBenchmarkId,
    next_network_recovery_benchmark_id: NetworkRecoveryBenchmarkId,
    next_network_driver_cleanup_id: NetworkDriverCleanupId,
    next_network_generation_audit_id: NetworkGenerationAuditId,
    next_network_fault_injection_id: NetworkFaultInjectionId,
    next_block_device_object_id: BlockDeviceObjectId,
    next_block_range_object_id: BlockRangeObjectId,
    next_block_request_object_id: BlockRequestObjectId,
    next_block_completion_object_id: BlockCompletionObjectId,
    next_block_wait_id: BlockWaitId,
    next_fake_block_backend_object_id: FakeBlockBackendObjectId,
    next_virtio_blk_backend_object_id: VirtioBlkBackendObjectId,
    next_block_read_path_id: BlockReadPathId,
    next_block_write_path_id: BlockWritePathId,
    next_block_request_queue_id: BlockRequestQueueId,
    next_block_dma_buffer_id: BlockDmaBufferId,
    next_block_page_object_id: BlockPageObjectId,
    next_buffer_cache_object_id: BufferCacheObjectId,
    next_file_object_id: FileObjectId,
    next_directory_object_id: DirectoryObjectId,
    next_fat_adapter_object_id: FatAdapterObjectId,
    next_ext4_adapter_object_id: Ext4AdapterObjectId,
    next_file_handle_capability_id: FileHandleCapabilityId,
    next_fs_wait_id: FsWaitId,
    next_block_driver_cleanup_id: BlockDriverCleanupId,
    next_block_pending_io_policy_id: BlockPendingIoPolicyId,
    next_block_request_generation_audit_id: BlockRequestGenerationAuditId,
    next_block_benchmark_id: BlockBenchmarkId,
    next_block_recovery_benchmark_id: BlockRecoveryBenchmarkId,
    next_target_feature_set_id: TargetFeatureSetId,
    next_vector_state_id: VectorStateId,
    next_simd_fault_injection_id: SimdFaultInjectionId,
    next_simd_benchmark_id: SimdBenchmarkId,
    next_simd_context_switch_benchmark_id: SimdContextSwitchBenchmarkId,
    next_framebuffer_object_id: FramebufferObjectId,
    next_display_object_id: DisplayObjectId,
    next_display_capability_id: DisplayCapabilityId,
    next_framebuffer_window_lease_id: FramebufferWindowLeaseId,
    next_framebuffer_mapping_id: FramebufferMappingId,
    next_framebuffer_write_id: FramebufferWriteId,
    next_framebuffer_flush_region_id: FramebufferFlushRegionId,
    next_framebuffer_dirty_region_id: FramebufferDirtyRegionId,
    next_display_event_log_id: DisplayEventLogId,
    next_activation_resume_id: ActivationResumeId,
    next_activation_wait_id: ActivationWaitId,
    next_activation_cleanup_id: ActivationCleanupId,
    next_preemption_latency_sample_id: PreemptionLatencySampleId,
    next_hart_event_attribution_id: HartEventAttributionId,
    next_authority_id: AuthorityId,
    next_fault_domain_id: FaultDomainId,
    next_store_id: StoreId,
    next_transaction_id: TransactionId,
    next_plan_id: PlanId,
    next_boundary_id: BoundaryId,
    next_artifact_id: ArtifactId,
    next_activation_id: StoreActivationId,
}

mod activation_migration;
mod authority;
mod block_benchmark;
mod block_completion_object;
mod block_device_object;
mod block_dma_buffer;
mod block_driver_cleanup;
mod block_page_object;
mod block_pending_io_policy;
mod block_range_object;
mod block_read_path;
mod block_recovery_benchmark;
mod block_request_generation_audit;
mod block_request_object;
mod block_request_queue;
mod block_wait;
mod block_write_path;
mod boundary;
mod buffer_cache_object;
mod capability;
mod cleanup;
mod command;
mod context;
mod cross_scheduler;
mod descriptor_object;
mod device_capability;
mod device_object;
mod directory_object;
mod display_capability;
mod display_event_log;
mod display_object;
mod dma_buffer_object;
mod driver_store_binding;
mod endpoint_object;
mod ext4_adapter_object;
mod fake_block_backend_object;
mod fake_net_backend_object;
mod fat_adapter_object;
mod file_handle_capability;
mod file_object;
mod framebuffer_dirty_region;
mod framebuffer_flush_region;
mod framebuffer_mapping;
mod framebuffer_object;
mod framebuffer_window_lease;
mod framebuffer_write;
mod fs_wait;
mod hart;
mod hart_event;
mod interface;
mod io_cleanup;
mod io_fault_injection;
mod io_validator;
mod io_wait;
mod ipi;
mod irq_event;
mod irq_line_object;
mod latency;
mod mmio_region_object;
mod network;
mod network_backpressure;
mod network_benchmark;
mod network_driver_cleanup;
mod network_fault_injection;
mod network_generation_audit;
mod network_recovery_benchmark;
mod network_rx_interrupt;
mod network_rx_wait;
mod network_stack_adapter;
mod network_tx_completion;
mod network_tx_gate;
mod packet_buffer_object;
mod packet_descriptor_object;
mod packet_device_object;
mod packet_queue_object;
mod query;
mod queue_object;
mod remote;
mod remote_park;
mod resource;
mod scheduler;
mod simd_benchmark;
mod simd_context_switch_benchmark;
mod simd_fault_injection;
mod smp_cleanup_quiescence;
mod smp_code_publish;
mod smp_safe_point;
mod smp_scaling;
mod smp_snapshot_barrier;
mod smp_stress;
mod snapshot;
mod socket_object;
mod socket_operation;
mod socket_wait;
mod stop_the_world;
mod store;
mod substrate;
mod target_feature_set;
mod task;
mod timer;
mod transaction;
mod vector_state;
mod virtio_blk_backend_object;
mod virtio_net_backend_object;
mod wait;

pub use command::*;

impl SemanticGraph {
    pub fn new() -> Self {
        Self::with_runtime_mode(RuntimeMode::Research)
    }
    pub fn with_runtime_mode(runtime_mode: RuntimeMode) -> Self {
        Self {
            harts: Vec::new(),
            tasks: Vec::new(),
            runtime_activations: Vec::new(),
            runnable_queues: Vec::new(),
            activation_contexts: Vec::new(),
            saved_contexts: Vec::new(),
            timer_interrupts: Vec::new(),
            ipi_events: Vec::new(),
            remote_preempts: Vec::new(),
            remote_parks: Vec::new(),
            preemptions: Vec::new(),
            scheduler_decisions: Vec::new(),
            cross_hart_scheduler_decisions: Vec::new(),
            activation_migrations: Vec::new(),
            smp_safe_points: Vec::new(),
            stop_the_world_rendezvous: Vec::new(),
            smp_code_publish_barriers: Vec::new(),
            smp_cleanup_quiescence: Vec::new(),
            smp_snapshot_barriers: Vec::new(),
            smp_stress_runs: Vec::new(),
            smp_scaling_benchmarks: Vec::new(),
            device_objects: Vec::new(),
            queue_objects: Vec::new(),
            descriptor_objects: Vec::new(),
            dma_buffer_objects: Vec::new(),
            mmio_region_objects: Vec::new(),
            irq_line_objects: Vec::new(),
            irq_events: Vec::new(),
            device_capabilities: Vec::new(),
            driver_store_bindings: Vec::new(),
            io_waits: Vec::new(),
            io_cleanups: Vec::new(),
            io_fault_injections: Vec::new(),
            io_validation_reports: Vec::new(),
            packet_device_objects: Vec::new(),
            packet_buffer_objects: Vec::new(),
            packet_queue_objects: Vec::new(),
            packet_descriptors: Vec::new(),
            fake_net_backends: Vec::new(),
            virtio_net_backends: Vec::new(),
            network_rx_interrupts: Vec::new(),
            network_rx_wait_resolutions: Vec::new(),
            network_tx_capability_gates: Vec::new(),
            network_tx_completions: Vec::new(),
            network_stack_adapters: Vec::new(),
            socket_objects: Vec::new(),
            endpoint_objects: Vec::new(),
            socket_operations: Vec::new(),
            socket_waits: Vec::new(),
            network_backpressures: Vec::new(),
            network_benchmarks: Vec::new(),
            network_recovery_benchmarks: Vec::new(),
            network_driver_cleanups: Vec::new(),
            network_generation_audits: Vec::new(),
            network_fault_injections: Vec::new(),
            block_device_objects: Vec::new(),
            block_range_objects: Vec::new(),
            block_request_objects: Vec::new(),
            block_completion_objects: Vec::new(),
            block_waits: Vec::new(),
            fake_block_backends: Vec::new(),
            virtio_blk_backends: Vec::new(),
            block_read_paths: Vec::new(),
            block_write_paths: Vec::new(),
            block_request_queues: Vec::new(),
            block_dma_buffers: Vec::new(),
            block_page_objects: Vec::new(),
            buffer_cache_objects: Vec::new(),
            file_objects: Vec::new(),
            directory_objects: Vec::new(),
            fat_adapter_objects: Vec::new(),
            ext4_adapter_objects: Vec::new(),
            file_handle_capabilities: Vec::new(),
            fs_waits: Vec::new(),
            block_driver_cleanups: Vec::new(),
            block_pending_io_policies: Vec::new(),
            block_request_generation_audits: Vec::new(),
            block_benchmarks: Vec::new(),
            block_recovery_benchmarks: Vec::new(),
            target_feature_sets: Vec::new(),
            vector_states: Vec::new(),
            simd_fault_injections: Vec::new(),
            simd_benchmarks: Vec::new(),
            simd_context_switch_benchmarks: Vec::new(),
            framebuffer_objects: Vec::new(),
            display_objects: Vec::new(),
            display_capabilities: Vec::new(),
            framebuffer_window_leases: Vec::new(),
            framebuffer_mappings: Vec::new(),
            framebuffer_writes: Vec::new(),
            framebuffer_flush_regions: Vec::new(),
            framebuffer_dirty_regions: Vec::new(),
            display_event_logs: Vec::new(),
            activation_resumes: Vec::new(),
            activation_waits: Vec::new(),
            activation_cleanups: Vec::new(),
            preemption_latency_samples: Vec::new(),
            hart_event_attributions: Vec::new(),
            resources: Vec::new(),
            authority_bindings: Vec::new(),
            waits: Vec::new(),
            fault_domains: Vec::new(),
            stores: Vec::new(),
            transactions: Vec::new(),
            fast_path_plans: Vec::new(),
            boundaries: Vec::new(),
            artifact_verifications: Vec::new(),
            store_activations: Vec::new(),
            command_results: Vec::new(),
            capabilities: CapabilityLedger::new(),
            event_log: EventLog::with_runtime_mode(runtime_mode),
            next_resource_id: 1,
            next_runtime_activation_id: 1,
            next_runnable_queue_id: 1,
            next_activation_context_id: 1,
            next_saved_context_id: 1,
            next_timer_interrupt_id: 1,
            next_ipi_event_id: 1,
            next_remote_preempt_id: 1,
            next_remote_park_id: 1,
            next_preemption_id: 1,
            next_scheduler_decision_id: 1,
            next_cross_hart_scheduler_decision_id: 1,
            next_activation_migration_id: 1,
            next_smp_safe_point_id: 1,
            next_stop_the_world_rendezvous_id: 1,
            next_smp_code_publish_barrier_id: 1,
            next_smp_cleanup_quiescence_id: 1,
            next_smp_snapshot_barrier_id: 1,
            next_smp_stress_run_id: 1,
            next_smp_scaling_benchmark_id: 1,
            next_device_object_id: 1,
            next_queue_object_id: 1,
            next_descriptor_object_id: 1,
            next_dma_buffer_object_id: 1,
            next_mmio_region_object_id: 1,
            next_irq_line_object_id: 1,
            next_irq_event_id: 1,
            next_device_capability_id: 1,
            next_driver_store_binding_id: 1,
            next_io_wait_id: 1,
            next_io_cleanup_id: 1,
            next_io_fault_injection_id: 1,
            next_io_validation_report_id: 1,
            next_packet_device_object_id: 1,
            next_packet_buffer_object_id: 1,
            next_packet_queue_object_id: 1,
            next_packet_descriptor_object_id: 1,
            next_fake_net_backend_object_id: 1,
            next_virtio_net_backend_object_id: 1,
            next_network_rx_interrupt_id: 1,
            next_network_rx_wait_resolution_id: 1,
            next_network_tx_capability_gate_id: 1,
            next_network_tx_completion_id: 1,
            next_network_stack_adapter_id: 1,
            next_socket_object_id: 1,
            next_endpoint_object_id: 1,
            next_socket_operation_id: 1,
            next_socket_wait_id: 1,
            next_network_backpressure_id: 1,
            next_network_benchmark_id: 1,
            next_network_recovery_benchmark_id: 1,
            next_network_driver_cleanup_id: 1,
            next_network_generation_audit_id: 1,
            next_network_fault_injection_id: 1,
            next_block_device_object_id: 1,
            next_block_range_object_id: 1,
            next_block_request_object_id: 1,
            next_block_completion_object_id: 1,
            next_block_wait_id: 1,
            next_fake_block_backend_object_id: 1,
            next_virtio_blk_backend_object_id: 1,
            next_block_read_path_id: 1,
            next_block_write_path_id: 1,
            next_block_request_queue_id: 1,
            next_block_dma_buffer_id: 1,
            next_block_page_object_id: 1,
            next_buffer_cache_object_id: 1,
            next_file_object_id: 1,
            next_directory_object_id: 1,
            next_fat_adapter_object_id: 1,
            next_ext4_adapter_object_id: 1,
            next_file_handle_capability_id: 1,
            next_fs_wait_id: 1,
            next_block_driver_cleanup_id: 1,
            next_block_pending_io_policy_id: 1,
            next_block_request_generation_audit_id: 1,
            next_block_benchmark_id: 1,
            next_block_recovery_benchmark_id: 1,
            next_target_feature_set_id: 1,
            next_vector_state_id: 1,
            next_simd_fault_injection_id: 1,
            next_simd_benchmark_id: 1,
            next_simd_context_switch_benchmark_id: 1,
            next_framebuffer_object_id: 1,
            next_display_object_id: 1,
            next_display_capability_id: 1,
            next_framebuffer_window_lease_id: 1,
            next_framebuffer_mapping_id: 1,
            next_framebuffer_write_id: 1,
            next_framebuffer_flush_region_id: 1,
            next_framebuffer_dirty_region_id: 1,
            next_display_event_log_id: 1,
            next_activation_resume_id: 1,
            next_activation_wait_id: 1,
            next_activation_cleanup_id: 1,
            next_preemption_latency_sample_id: 1,
            next_hart_event_attribution_id: 1,
            next_authority_id: 1,
            next_fault_domain_id: 1,
            next_store_id: 1,
            next_transaction_id: 1,
            next_plan_id: 1,
            next_boundary_id: 1,
            next_artifact_id: 1,
            next_activation_id: 1,
        }
    }
    pub fn runtime_mode(&self) -> RuntimeMode {
        self.event_log.runtime_mode()
    }
}

impl Default for SemanticGraph {
    fn default() -> Self {
        Self::new()
    }
}
