use alloc::{
    format,
    string::{String, ToString},
};

use super::super::{super::*, kind::EventKind};

pub(super) fn summary(kind: &EventKind) -> Option<String> {
    let summary = match kind {
        EventKind::BlockDeviceObjectRecorded {
            block_device,
            device,
            device_generation,
            sector_size,
            sector_count,
            read_only,
            max_transfer_sectors,
            generation,
        } => format!(
            "BlockDeviceObjectRecorded block_device={block_device} device={device}@{device_generation} sector_size={sector_size} sector_count={sector_count} read_only={read_only} max_transfer_sectors={max_transfer_sectors} generation={generation}"
        ),
        EventKind::BlockRangeObjectRecorded {
            block_range,
            block_device,
            block_device_generation,
            start_sector,
            sector_count,
            byte_offset,
            byte_len,
            generation,
        } => format!(
            "BlockRangeObjectRecorded block_range={block_range} block_device={block_device}@{block_device_generation} start_sector={start_sector} sector_count={sector_count} byte_offset={byte_offset} byte_len={byte_len} generation={generation}"
        ),
        EventKind::BlockRequestObjectRecorded {
            block_request,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            operation,
            sequence,
            byte_len,
            generation,
        } => format!(
            "BlockRequestObjectRecorded block_request={block_request} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} operation={} sequence={sequence} byte_len={byte_len} generation={generation}",
            operation.as_str()
        ),
        EventKind::BlockCompletionObjectRecorded {
            block_completion,
            block_request,
            block_request_generation,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            sequence,
            completed_bytes,
            status,
            generation,
        } => format!(
            "BlockCompletionObjectRecorded block_completion={block_completion} block_request={block_request}@{block_request_generation} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} sequence={sequence} completed_bytes={completed_bytes} status={} generation={generation}",
            status.as_str()
        ),
        EventKind::BlockWaitCreated {
            block_wait,
            wait,
            wait_generation,
            block_request,
            block_request_generation,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            operation,
            sequence,
            byte_len,
            generation,
        } => format!(
            "BlockWaitCreated block_wait={block_wait} wait={wait}@{wait_generation} block_request={block_request}@{block_request_generation} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} operation={} sequence={sequence} byte_len={byte_len} generation={generation}",
            operation.as_str()
        ),
        EventKind::BlockWaitResolved {
            block_wait,
            wait,
            wait_generation,
            block_completion,
            block_completion_generation,
            generation,
        } => format!(
            "BlockWaitResolved block_wait={block_wait} wait={wait}@{wait_generation} block_completion={block_completion}@{block_completion_generation} generation={generation}"
        ),
        EventKind::BlockWaitCancelled { block_wait, wait, wait_generation, reason, generation } => {
            format!(
                "BlockWaitCancelled block_wait={block_wait} wait={wait}@{wait_generation} reason={} generation={generation}",
                reason.as_str()
            )
        }
        EventKind::BlockPendingIoPolicyApplied {
            policy,
            block_wait,
            block_wait_generation,
            wait,
            wait_generation,
            block_request,
            block_request_generation,
            retry_request,
            retry_request_generation,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            action,
            errno,
            retry_attempt,
            max_retries,
            generation,
        } => format!(
            "BlockPendingIoPolicyApplied policy={policy} block_wait={block_wait}@{block_wait_generation} wait={wait}@{wait_generation} block_request={block_request}@{block_request_generation} retry_request={} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} action={} errno={errno} retry_attempt={retry_attempt} max_retries={max_retries} generation={generation}",
            retry_request
                .zip(*retry_request_generation)
                .map(|(id, generation)| format!("{id}@{generation}"))
                .unwrap_or_else(|| "none".to_string()),
            action.as_str()
        ),
        EventKind::BlockRequestGenerationAuditRecorded {
            audit,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            block_request,
            block_request_generation,
            backend,
            dma_buffer,
            rejected_completion_generation_probes,
            rejected_wait_generation_probes,
            rejected_dma_generation_probes,
            rejected_queue_generation_probes,
            generation,
        } => format!(
            "BlockRequestGenerationAuditRecorded audit={audit} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} block_request={block_request}@{block_request_generation} backend={}:{}@{} dma_buffer={}:{}@{} rejected_completion_generation_probes={rejected_completion_generation_probes} rejected_wait_generation_probes={rejected_wait_generation_probes} rejected_dma_generation_probes={rejected_dma_generation_probes} rejected_queue_generation_probes={rejected_queue_generation_probes} generation={generation}",
            backend.kind.as_str(),
            backend.id,
            backend.generation,
            dma_buffer.kind.as_str(),
            dma_buffer.id,
            dma_buffer.generation
        ),
        EventKind::BlockBenchmarkRecorded {
            benchmark,
            backend,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            read_path,
            read_path_generation,
            write_path,
            write_path_generation,
            request_queue,
            request_queue_generation,
            block_dma_buffer,
            block_dma_buffer_generation,
            sample_requests,
            sample_bytes,
            read_completed_requests,
            write_completed_requests,
            queue_completed_requests,
            measured_nanos,
            budget_nanos,
            iops,
            throughput_bytes_per_sec,
            p50_latency_nanos,
            p99_latency_nanos,
            generation,
        } => format!(
            "BlockBenchmarkRecorded benchmark={benchmark} backend={}:{}@{} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} read_path={read_path}@{read_path_generation} write_path={write_path}@{write_path_generation} request_queue={request_queue}@{request_queue_generation} block_dma_buffer={block_dma_buffer}@{block_dma_buffer_generation} sample_requests={sample_requests} sample_bytes={sample_bytes} read_completed_requests={read_completed_requests} write_completed_requests={write_completed_requests} queue_completed_requests={queue_completed_requests} measured_nanos={measured_nanos} budget_nanos={budget_nanos} iops={iops} throughput_bytes_per_sec={throughput_bytes_per_sec} p50_latency_nanos={p50_latency_nanos} p99_latency_nanos={p99_latency_nanos} generation={generation}",
            backend.kind.as_str(),
            backend.id,
            backend.generation
        ),
        EventKind::BlockRecoveryBenchmarkRecorded {
            benchmark,
            cleanup,
            cleanup_generation,
            io_cleanup,
            io_cleanup_generation,
            backend,
            block_device,
            block_device_generation,
            driver_store,
            driver_store_generation,
            device,
            device_generation,
            driver_binding,
            driver_binding_generation,
            recovery_start_event,
            recovery_complete_event,
            cancelled_block_waits,
            cancelled_wait_tokens,
            released_dma_buffers,
            revoked_device_capabilities,
            recovery_nanos,
            budget_nanos,
            generation,
        } => format!(
            "BlockRecoveryBenchmarkRecorded benchmark={benchmark} cleanup={cleanup}@{cleanup_generation} io_cleanup={io_cleanup}@{io_cleanup_generation} backend={}:{}@{} block_device={block_device}@{block_device_generation} driver_store={driver_store}@{driver_store_generation} device={device}@{device_generation} driver_binding={driver_binding}@{driver_binding_generation} recovery_start_event={recovery_start_event} recovery_complete_event={recovery_complete_event} cancelled_block_waits={cancelled_block_waits} cancelled_wait_tokens={cancelled_wait_tokens} released_dma_buffers={released_dma_buffers} revoked_device_capabilities={revoked_device_capabilities} recovery_nanos={recovery_nanos} budget_nanos={budget_nanos} generation={generation}",
            backend.kind.as_str(),
            backend.id,
            backend.generation
        ),
        EventKind::FakeBlockBackendObjectBound {
            fake_block_backend,
            block_device,
            block_device_generation,
            sector_size,
            sector_count,
            read_only,
            max_transfer_sectors,
            deterministic_seed,
            generation,
        } => format!(
            "FakeBlockBackendObjectBound fake_block_backend={fake_block_backend} block_device={block_device}@{block_device_generation} sector_size={sector_size} sector_count={sector_count} read_only={read_only} max_transfer_sectors={max_transfer_sectors} deterministic_seed={deterministic_seed} generation={generation}"
        ),
        EventKind::VirtioBlkBackendSkeletonBound {
            virtio_blk_backend,
            block_device,
            block_device_generation,
            driver_binding,
            driver_binding_generation,
            device,
            device_generation,
            queue_size,
            request_queue_index,
            negotiated_features,
            generation,
        } => format!(
            "VirtioBlkBackendSkeletonBound virtio_blk_backend={virtio_blk_backend} block_device={block_device}@{block_device_generation} driver_binding={driver_binding}@{driver_binding_generation} device={device}@{device_generation} queue_size={queue_size} request_queue_index={request_queue_index} negotiated_features={negotiated_features} generation={generation}"
        ),
        EventKind::BlockReadPathRecorded {
            read_path,
            backend,
            block_request,
            block_request_generation,
            block_completion,
            block_completion_generation,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            sequence,
            completed_bytes,
            data_digest,
            generation,
        } => format!(
            "BlockReadPathRecorded read_path={read_path} backend={} block_request={block_request}@{block_request_generation} block_completion={block_completion}@{block_completion_generation} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} sequence={sequence} completed_bytes={completed_bytes} data_digest={data_digest} generation={generation}",
            backend.summary()
        ),
        EventKind::BlockWritePathRecorded {
            write_path,
            backend,
            block_request,
            block_request_generation,
            block_completion,
            block_completion_generation,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            sequence,
            completed_bytes,
            payload_digest,
            generation,
        } => format!(
            "BlockWritePathRecorded write_path={write_path} backend={} block_request={block_request}@{block_request_generation} block_completion={block_completion}@{block_completion_generation} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} sequence={sequence} completed_bytes={completed_bytes} payload_digest={payload_digest} generation={generation}",
            backend.summary()
        ),
        EventKind::BlockRequestQueueRecorded {
            queue,
            backend,
            block_device,
            block_device_generation,
            depth,
            request_count,
            pending_count,
            completed_count,
            first_sequence,
            last_sequence,
            generation,
        } => format!(
            "BlockRequestQueueRecorded queue={queue} backend={} block_device={block_device}@{block_device_generation} depth={depth} request_count={request_count} pending_count={pending_count} completed_count={completed_count} first_sequence={first_sequence} last_sequence={last_sequence} generation={generation}",
            backend.summary()
        ),
        EventKind::BlockDmaBufferBound {
            block_dma_buffer,
            backend,
            block_request,
            block_request_generation,
            dma_buffer,
            dma_buffer_generation,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            descriptor,
            descriptor_generation,
            queue,
            queue_generation,
            operation,
            access,
            byte_len,
            buffer_len,
            buffer_digest,
            generation,
        } => format!(
            "BlockDmaBufferBound block_dma_buffer={block_dma_buffer} backend={} block_request={block_request}@{block_request_generation} dma_buffer={dma_buffer}@{dma_buffer_generation} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} descriptor={descriptor}@{descriptor_generation} queue={queue}@{queue_generation} operation={} access={} byte_len={byte_len} buffer_len={buffer_len} buffer_digest={buffer_digest} generation={generation}",
            backend.summary(),
            operation.as_str(),
            access.as_str()
        ),
        EventKind::BlockPageObjectIntegrated {
            block_page_object,
            block_dma_buffer,
            block_dma_buffer_generation,
            block_request,
            block_request_generation,
            block_completion,
            block_completion_generation,
            dma_buffer,
            dma_buffer_generation,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            aspace,
            vma_region,
            page,
            page_dirty_generation,
            page_offset,
            byte_len,
            operation,
            generation,
        } => format!(
            "BlockPageObjectIntegrated block_page_object={block_page_object} block_dma_buffer={block_dma_buffer}@{block_dma_buffer_generation} block_request={block_request}@{block_request_generation} block_completion={block_completion}@{block_completion_generation} dma_buffer={dma_buffer}@{dma_buffer_generation} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} aspace={} vma_region={} page={} page_dirty_generation={page_dirty_generation} page_offset={page_offset} byte_len={byte_len} operation={} generation={generation}",
            aspace.summary(),
            vma_region.summary(),
            page.summary(),
            operation.as_str()
        ),
        EventKind::BufferCacheObjectRecorded {
            buffer_cache_object,
            block_page_object,
            block_page_object_generation,
            block_dma_buffer,
            block_dma_buffer_generation,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            aspace,
            vma_region,
            page,
            page_dirty_generation,
            page_offset,
            block_offset,
            byte_len,
            operation,
            cache_state,
            coherency_epoch,
            generation,
        } => format!(
            "BufferCacheObjectRecorded buffer_cache_object={buffer_cache_object} block_page_object={block_page_object}@{block_page_object_generation} block_dma_buffer={block_dma_buffer}@{block_dma_buffer_generation} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} aspace={} vma_region={} page={} page_dirty_generation={page_dirty_generation} page_offset={page_offset} block_offset={block_offset} byte_len={byte_len} operation={} cache_state={} coherency_epoch={coherency_epoch} generation={generation}",
            aspace.summary(),
            vma_region.summary(),
            page.summary(),
            operation.as_str(),
            cache_state.as_str()
        ),
        EventKind::FileObjectRecorded {
            file_object,
            buffer_cache_object,
            buffer_cache_object_generation,
            block_device,
            block_device_generation,
            block_range,
            block_range_generation,
            page,
            page_dirty_generation,
            namespace,
            file_key,
            path,
            file_offset,
            byte_len,
            file_size,
            content_digest,
            cache_state,
            state,
            generation,
        } => format!(
            "FileObjectRecorded file_object={file_object} buffer_cache_object={buffer_cache_object}@{buffer_cache_object_generation} block_device={block_device}@{block_device_generation} block_range={block_range}@{block_range_generation} page={} page_dirty_generation={page_dirty_generation} namespace={namespace} file_key={file_key} path={path} file_offset={file_offset} byte_len={byte_len} file_size={file_size} content_digest={content_digest} cache_state={} state={} generation={generation}",
            page.summary(),
            cache_state.as_str(),
            state.as_str()
        ),
        EventKind::DirectoryObjectRecorded {
            directory_object,
            file_object,
            file_object_generation,
            namespace,
            directory_key,
            directory_path,
            entry_name,
            child_file_key,
            child_path,
            entry_kind,
            file_size,
            content_digest,
            state,
            generation,
        } => format!(
            "DirectoryObjectRecorded directory_object={directory_object} file_object={file_object}@{file_object_generation} namespace={namespace} directory_key={directory_key} directory_path={directory_path} entry_name={entry_name} child_file_key={child_file_key} child_path={child_path} entry_kind={} file_size={file_size} content_digest={content_digest} state={} generation={generation}",
            entry_kind.as_str(),
            state.as_str()
        ),
        EventKind::FatAdapterObjectRecorded {
            fat_adapter_object,
            directory_object,
            directory_object_generation,
            file_object,
            file_object_generation,
            block_device,
            block_device_generation,
            implementation,
            version,
            profile,
            volume_label,
            image_bytes,
            adapter_path,
            semantic_path,
            bytes_written,
            bytes_read,
            write_digest,
            read_digest,
            file_content_digest,
            state,
            generation,
        } => format!(
            "FatAdapterObjectRecorded fat_adapter_object={fat_adapter_object} directory_object={directory_object}@{directory_object_generation} file_object={file_object}@{file_object_generation} block_device={block_device}@{block_device_generation} implementation={implementation} version={version} profile={profile} volume_label={volume_label} image_bytes={image_bytes} adapter_path={adapter_path} semantic_path={semantic_path} bytes_written={bytes_written} bytes_read={bytes_read} write_digest={write_digest} read_digest={read_digest} file_content_digest={file_content_digest} state={} generation={generation}",
            state.as_str()
        ),
        EventKind::Ext4AdapterObjectRecorded {
            ext4_adapter_object,
            directory_object,
            directory_object_generation,
            file_object,
            file_object_generation,
            block_device,
            block_device_generation,
            implementation,
            version,
            profile,
            volume_label,
            image_bytes,
            adapter_path,
            semantic_path,
            bytes_read,
            read_digest,
            file_content_digest,
            directory_entries,
            read_only_enforced,
            state,
            generation,
        } => format!(
            "Ext4AdapterObjectRecorded ext4_adapter_object={ext4_adapter_object} directory_object={directory_object}@{directory_object_generation} file_object={file_object}@{file_object_generation} block_device={block_device}@{block_device_generation} implementation={implementation} version={version} profile={profile} volume_label={volume_label} image_bytes={image_bytes} adapter_path={adapter_path} semantic_path={semantic_path} bytes_read={bytes_read} read_digest={read_digest} file_content_digest={file_content_digest} directory_entries={directory_entries} read_only_enforced={read_only_enforced} state={} generation={generation}",
            state.as_str()
        ),
        EventKind::FileHandleCapabilityRecorded {
            file_handle_capability,
            owner_store,
            owner_store_generation,
            file_object,
            file_object_generation,
            directory_object,
            directory_object_generation,
            capability,
            capability_generation,
            handle_slot,
            handle_generation,
            handle_tag,
            operation,
            file_offset,
            byte_len,
            content_digest,
            state,
            generation,
        } => format!(
            "FileHandleCapabilityRecorded file_handle_capability={file_handle_capability} owner_store={owner_store}@{owner_store_generation} file_object={file_object}@{file_object_generation} directory_object={directory_object}@{directory_object_generation} capability={capability}@{capability_generation} handle_slot={handle_slot} handle_generation={handle_generation} handle_tag={handle_tag} operation={operation} file_offset={file_offset} byte_len={byte_len} content_digest={content_digest} state={} generation={generation}",
            state.as_str()
        ),
        EventKind::FsWaitCreated {
            fs_wait,
            wait,
            wait_generation,
            owner_store,
            owner_store_generation,
            file_object,
            file_object_generation,
            directory_object,
            directory_object_generation,
            file_handle_capability,
            file_handle_capability_generation,
            operation,
            blocker,
            sequence,
            byte_len,
            generation,
        } => format!(
            "FsWaitCreated fs_wait={fs_wait} wait={wait}@{wait_generation} owner_store={owner_store}@{owner_store_generation} file_object={file_object}@{file_object_generation} directory_object={directory_object}@{directory_object_generation} file_handle_capability={file_handle_capability}@{file_handle_capability_generation} operation={operation} blocker={} sequence={sequence} byte_len={byte_len} generation={generation}",
            blocker.summary()
        ),
        EventKind::FsWaitResolved { fs_wait, wait, wait_generation, generation } => format!(
            "FsWaitResolved fs_wait={fs_wait} wait={wait}@{wait_generation} generation={generation}"
        ),
        EventKind::FsWaitCancelled { fs_wait, wait, wait_generation, reason, generation } => {
            format!(
                "FsWaitCancelled fs_wait={fs_wait} wait={wait}@{wait_generation} reason={} generation={generation}",
                reason.as_str()
            )
        }
        EventKind::BlockDriverCleanupStarted {
            cleanup,
            io_cleanup,
            driver_store,
            driver_store_generation,
            device,
            device_generation,
            driver_binding,
            driver_binding_generation,
            block_device,
            block_device_generation,
            backend,
            generation,
        } => format!(
            "BlockDriverCleanupStarted cleanup={cleanup} io_cleanup={io_cleanup} driver_store={driver_store}@{driver_store_generation} device={device}@{device_generation} driver_binding={driver_binding}@{driver_binding_generation} block_device={block_device}@{block_device_generation} backend={}:{}@{} generation={generation}",
            backend.kind.as_str(),
            backend.id,
            backend.generation
        ),
        EventKind::BlockDriverCleanupCompleted {
            cleanup,
            io_cleanup,
            io_cleanup_generation,
            cancelled_block_waits,
            released_dma_buffers,
            revoked_device_capabilities,
            generation,
        } => format!(
            "BlockDriverCleanupCompleted cleanup={cleanup} io_cleanup={io_cleanup}@{io_cleanup_generation} cancelled_block_waits={cancelled_block_waits} released_dma_buffers={released_dma_buffers} revoked_device_capabilities={revoked_device_capabilities} generation={generation}"
        ),
        _ => return None,
    };
    Some(summary)
}
