use alloc::{format, string::String};

use super::super::{super::*, kind::EventKind};

pub(super) fn summary(kind: &EventKind) -> Option<String> {
    let summary = match kind {
        EventKind::IntegratedSmpPreemptionCleanupRecorded {
            scenario,
            integrated,
            stress_run,
            stress_run_generation,
            preemption,
            preemption_generation,
            remote_preempt,
            remote_preempt_generation,
            activation_cleanup,
            activation_cleanup_generation,
            smp_cleanup_quiescence,
            smp_cleanup_quiescence_generation,
            cleanup_store,
            target_store_generation,
            result_store_generation,
            hart_count,
            invariant_checks,
            generation,
        } => format!(
            "IntegratedSmpPreemptionCleanupRecorded integrated={integrated} scenario={scenario} stress_run={stress_run}@{stress_run_generation} preemption={preemption}@{preemption_generation} remote_preempt={remote_preempt}@{remote_preempt_generation} activation_cleanup={activation_cleanup}@{activation_cleanup_generation} smp_cleanup_quiescence={smp_cleanup_quiescence}@{smp_cleanup_quiescence_generation} cleanup_store={cleanup_store}@{target_store_generation}->{result_store_generation} harts={hart_count} invariant_checks={invariant_checks} generation={generation}"
        ),
        EventKind::IntegratedSmpNetworkFaultRecorded {
            scenario,
            integrated,
            network_driver_cleanup,
            network_driver_cleanup_generation,
            smp_stress_run,
            smp_stress_run_generation,
            remote_preempt,
            remote_preempt_generation,
            smp_cleanup_quiescence,
            smp_cleanup_quiescence_generation,
            driver_store,
            driver_store_generation,
            packet_device,
            packet_device_generation,
            hart_count,
            cancelled_socket_waits,
            revoked_packet_capabilities,
            invariant_checks,
            generation,
        } => format!(
            "IntegratedSmpNetworkFaultRecorded integrated={integrated} scenario={scenario} cleanup={network_driver_cleanup}@{network_driver_cleanup_generation} stress_run={smp_stress_run}@{smp_stress_run_generation} remote_preempt={remote_preempt}@{remote_preempt_generation} smp_cleanup_quiescence={smp_cleanup_quiescence}@{smp_cleanup_quiescence_generation} driver_store={driver_store}@{driver_store_generation} packet_device={packet_device}@{packet_device_generation} harts={hart_count} cancelled_socket_waits={cancelled_socket_waits} revoked_packet_capabilities={revoked_packet_capabilities} invariant_checks={invariant_checks} generation={generation}"
        ),
        EventKind::IntegratedDiskPreemptFaultRecorded {
            scenario,
            integrated,
            preemption,
            preemption_generation,
            timer_interrupt,
            timer_interrupt_generation,
            block_pending_io_policy,
            block_pending_io_policy_generation,
            block_wait,
            block_wait_generation,
            wait,
            wait_generation,
            block_request,
            block_request_generation,
            block_device,
            block_device_generation,
            action,
            errno,
            preempted_activation,
            preempted_activation_generation_after,
            invariant_checks,
            generation,
        } => format!(
            "IntegratedDiskPreemptFaultRecorded integrated={integrated} scenario={scenario} preemption={preemption}@{preemption_generation} timer_interrupt={timer_interrupt}@{timer_interrupt_generation} policy={block_pending_io_policy}@{block_pending_io_policy_generation} block_wait={block_wait}@{block_wait_generation} wait={wait}@{wait_generation} block_request={block_request}@{block_request_generation} block_device={block_device}@{block_device_generation} action={} errno={errno} activation={preempted_activation}@{preempted_activation_generation_after} invariant_checks={invariant_checks} generation={generation}",
            action.as_str()
        ),
        EventKind::IntegratedSimdMigrationRecorded {
            scenario,
            integrated,
            activation_migration,
            activation_migration_generation,
            target_feature_set,
            target_feature_set_generation,
            source_vector_state,
            migrated_vector_state,
            activation,
            activation_generation_before,
            activation_generation_after,
            source_hart,
            source_hart_generation,
            target_hart,
            target_hart_generation,
            simd_abi,
            invariant_checks,
            generation,
        } => format!(
            "IntegratedSimdMigrationRecorded integrated={integrated} scenario={scenario} migration={activation_migration}@{activation_migration_generation} target_feature_set={target_feature_set}@{target_feature_set_generation} source_vector_state={} migrated_vector_state={} activation={activation}@{activation_generation_before}->{activation_generation_after} source_hart={source_hart}@{source_hart_generation} target_hart={target_hart}@{target_hart_generation} simd_abi={simd_abi} invariant_checks={invariant_checks} generation={generation}",
            source_vector_state.summary(),
            migrated_vector_state.summary()
        ),
        EventKind::IntegratedNetworkDiskIoRecorded {
            scenario,
            integrated,
            network_benchmark,
            network_benchmark_generation,
            block_benchmark,
            block_benchmark_generation,
            network_owner_store,
            network_owner_store_generation,
            packet_device,
            packet_device_generation,
            block_device,
            block_device_generation,
            network_sample_bytes,
            block_sample_bytes,
            concurrent_window_nanos,
            combined_throughput_bytes_per_sec,
            max_p99_latency_nanos,
            invariant_checks,
            generation,
        } => format!(
            "IntegratedNetworkDiskIoRecorded integrated={integrated} scenario={scenario} network_benchmark={network_benchmark}@{network_benchmark_generation} block_benchmark={block_benchmark}@{block_benchmark_generation} network_owner_store={network_owner_store}@{network_owner_store_generation} packet_device={packet_device}@{packet_device_generation} block_device={block_device}@{block_device_generation} network_bytes={network_sample_bytes} block_bytes={block_sample_bytes} window_nanos={concurrent_window_nanos} combined_throughput={combined_throughput_bytes_per_sec} max_p99_latency={max_p99_latency_nanos} invariant_checks={invariant_checks} generation={generation}"
        ),
        EventKind::IntegratedDisplaySchedulerLoadRecorded {
            scenario,
            integrated,
            framebuffer_benchmark,
            framebuffer_benchmark_generation,
            scheduler_decision,
            scheduler_decision_generation,
            owner_store,
            owner_store_generation,
            queue,
            queue_generation,
            selected_activation,
            selected_activation_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            sample_frames,
            sample_bytes,
            scheduler_load_units,
            display_measured_nanos,
            invariant_checks,
            generation,
        } => format!(
            "IntegratedDisplaySchedulerLoadRecorded integrated={integrated} scenario={scenario} framebuffer_benchmark={framebuffer_benchmark}@{framebuffer_benchmark_generation} scheduler_decision={scheduler_decision}@{scheduler_decision_generation} owner_store={owner_store}@{owner_store_generation} queue={queue}@{queue_generation} activation={selected_activation}@{selected_activation_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} sample_frames={sample_frames} sample_bytes={sample_bytes} scheduler_load_units={scheduler_load_units} display_measured_nanos={display_measured_nanos} invariant_checks={invariant_checks} generation={generation}"
        ),
        EventKind::IntegratedSnapshotIoLeaseBarrierRecorded {
            scenario,
            integrated,
            smp_snapshot_barrier,
            smp_snapshot_barrier_generation,
            io_cleanup,
            io_cleanup_generation,
            display_snapshot_barrier,
            display_snapshot_barrier_generation,
            released_dma_buffers,
            released_mmio_regions,
            released_irq_lines,
            released_framebuffer_window_leases,
            active_dmw_lease_count,
            in_flight_dma_count,
            active_framebuffer_window_lease_count,
            invariant_checks,
            generation,
        } => format!(
            "IntegratedSnapshotIoLeaseBarrierRecorded integrated={integrated} scenario={scenario} smp_snapshot_barrier={smp_snapshot_barrier}@{smp_snapshot_barrier_generation} io_cleanup={io_cleanup}@{io_cleanup_generation} display_snapshot_barrier={display_snapshot_barrier}@{display_snapshot_barrier_generation} released_dma_buffers={released_dma_buffers} released_mmio_regions={released_mmio_regions} released_irq_lines={released_irq_lines} released_framebuffer_window_leases={released_framebuffer_window_leases} active_dmw_leases={active_dmw_lease_count} in_flight_dma={in_flight_dma_count} active_framebuffer_window_leases={active_framebuffer_window_lease_count} invariant_checks={invariant_checks} generation={generation}"
        ),
        EventKind::IntegratedCodePublishSmpWorkloadRecorded {
            scenario,
            integrated,
            smp_stress_run,
            smp_stress_run_generation,
            smp_code_publish_barrier,
            smp_code_publish_barrier_generation,
            publish_rendezvous,
            publish_rendezvous_generation,
            publish_safe_point,
            publish_safe_point_generation,
            code_publish_epoch_before,
            code_publish_epoch_after,
            hart_count,
            workload_iterations,
            invariant_checks,
            generation,
        } => format!(
            "IntegratedCodePublishSmpWorkloadRecorded integrated={integrated} scenario={scenario} stress_run={smp_stress_run}@{smp_stress_run_generation} code_publish_barrier={smp_code_publish_barrier}@{smp_code_publish_barrier_generation} rendezvous={publish_rendezvous}@{publish_rendezvous_generation} safe_point={publish_safe_point}@{publish_safe_point_generation} code_publish_epoch={code_publish_epoch_before}->{code_publish_epoch_after} harts={hart_count} iterations={workload_iterations} invariant_checks={invariant_checks} generation={generation}"
        ),
        EventKind::IntegratedDisplayPanicRecorded {
            scenario,
            integrated,
            substrate_panic_event,
            display_panic_last_frame,
            display_panic_last_frame_generation,
            panic_ring_record_count,
            panic_ring_lost_count,
            jsonl_frame_count,
            contract_panic_summary_records,
            last_frame_summary_records,
            corrupt_record_count,
            truncated_record_count,
            invariant_checks,
            generation,
        } => format!(
            "IntegratedDisplayPanicRecorded integrated={integrated} scenario={scenario} substrate_panic_event={substrate_panic_event} display_panic_last_frame={display_panic_last_frame}@{display_panic_last_frame_generation} panic_ring_records={panic_ring_record_count} lost={panic_ring_lost_count} jsonl_frames={jsonl_frame_count} contract_panic_summary_records={contract_panic_summary_records} last_frame_summary_records={last_frame_summary_records} corrupt_records={corrupt_record_count} truncated_records={truncated_record_count} invariant_checks={invariant_checks} generation={generation}"
        ),
        EventKind::IntegratedOsctlTraceReplayRecorded {
            scenario,
            integrated,
            replay_event_cursor,
            integrated_scenario_count,
            replayed_root_count,
            stable_view_count,
            historical_edge_count,
            replay_fixture_count,
            contract_validation_ok,
            replay_validation_ok,
            graph_history_ok,
            roots_match_counts,
            invariant_checks,
            generation,
        } => format!(
            "IntegratedOsctlTraceReplayRecorded integrated={integrated} scenario={scenario} replay_event_cursor={replay_event_cursor} integrated_scenarios={integrated_scenario_count} replayed_roots={replayed_root_count} stable_views={stable_view_count} historical_edges={historical_edge_count} replay_fixtures={replay_fixture_count} contract_validation_ok={contract_validation_ok} replay_validation_ok={replay_validation_ok} graph_history_ok={graph_history_ok} roots_match_counts={roots_match_counts} invariant_checks={invariant_checks} generation={generation}"
        ),
        _ => return None,
    };
    Some(summary)
}
