use alloc::{
    format,
    string::{String, ToString},
};

use super::super::{super::*, kind::EventKind};

pub(super) fn summary(kind: &EventKind) -> Option<String> {
    let summary = match kind {
        EventKind::TargetFeatureSetDiscovered {
            feature_set,
            target_profile,
            target_arch,
            base_isa,
            simd_abi,
            simd_supported,
            vector_register_count,
            vector_register_bits,
            scalar_fallback,
            generation,
        } => format!(
            "TargetFeatureSetDiscovered feature_set={feature_set} target_profile={target_profile} target_arch={target_arch} base_isa={base_isa} simd_abi={simd_abi} simd_supported={simd_supported} vector_register_count={vector_register_count} vector_register_bits={vector_register_bits} scalar_fallback={scalar_fallback} generation={generation}"
        ),
        EventKind::VectorStateRecorded {
            vector_state,
            owner_activation,
            owner_store,
            code_object,
            target_feature_set,
            simd_abi,
            vector_register_count,
            vector_register_bits,
            register_bytes,
            state,
            generation,
        } => format!(
            "VectorStateRecorded vector_state={vector_state} activation={}:{}@{} store={}:{}@{} code_object={}:{}@{} target_feature_set={}:{}@{} simd_abi={simd_abi} vector_register_count={vector_register_count} vector_register_bits={vector_register_bits} register_bytes={register_bytes} state={} generation={generation}",
            owner_activation.kind.as_str(),
            owner_activation.id,
            owner_activation.generation,
            owner_store.kind.as_str(),
            owner_store.id,
            owner_store.generation,
            code_object.kind.as_str(),
            code_object.id,
            code_object.generation,
            target_feature_set.kind.as_str(),
            target_feature_set.id,
            target_feature_set.generation,
            state.as_str()
        ),
        EventKind::SimdFaultInjectionRecorded {
            injection,
            activation,
            code_object,
            trap,
            target_feature_set,
            vector_state,
            kind,
            effect,
            generation,
        } => format!(
            "SimdFaultInjectionRecorded injection={injection} activation={} code_object={} trap={} target_feature_set={} vector_state={} kind={} effect={} generation={generation}",
            activation.summary(),
            code_object.summary(),
            trap.summary(),
            target_feature_set.summary(),
            vector_state.map(|record| record.summary()).unwrap_or_else(|| "none".to_string()),
            kind.as_str(),
            effect.as_str()
        ),
        EventKind::SimdBenchmarkRecorded {
            benchmark,
            target_feature_set,
            scalar_code_object,
            vector_code_object,
            simd_abi,
            vector_register_count,
            vector_register_bits,
            workload_units,
            scalar_nanos,
            vector_nanos,
            speedup_milli,
            context_overhead_nanos,
            generation,
        } => format!(
            "SimdBenchmarkRecorded benchmark={benchmark} target_feature_set={} scalar_code_object={} vector_code_object={} simd_abi={simd_abi} vector_register_count={vector_register_count} vector_register_bits={vector_register_bits} workload_units={workload_units} scalar_nanos={scalar_nanos} vector_nanos={vector_nanos} speedup_milli={speedup_milli} context_overhead_nanos={context_overhead_nanos} generation={generation}",
            target_feature_set.summary(),
            scalar_code_object.summary(),
            vector_code_object.summary()
        ),
        EventKind::SimdContextSwitchBenchmarkRecorded {
            benchmark,
            preemption,
            activation_resume,
            saved_vector_state,
            restored_vector_state,
            target_feature_set,
            simd_abi,
            vector_register_count,
            vector_register_bits,
            sample_count,
            scalar_context_switch_nanos,
            vector_context_switch_nanos,
            overhead_nanos,
            budget_nanos,
            generation,
        } => format!(
            "SimdContextSwitchBenchmarkRecorded benchmark={benchmark} preemption={} activation_resume={} saved_vector_state={} restored_vector_state={} target_feature_set={} simd_abi={simd_abi} vector_register_count={vector_register_count} vector_register_bits={vector_register_bits} sample_count={sample_count} scalar_context_switch_nanos={scalar_context_switch_nanos} vector_context_switch_nanos={vector_context_switch_nanos} overhead_nanos={overhead_nanos} budget_nanos={budget_nanos} generation={generation}",
            preemption.summary(),
            activation_resume.summary(),
            saved_vector_state.summary(),
            restored_vector_state.summary(),
            target_feature_set.summary()
        ),
        EventKind::FramebufferObjectRecorded {
            framebuffer,
            resource,
            resource_generation,
            width,
            height,
            stride_bytes,
            pixel_format,
            byte_len,
            generation,
        } => format!(
            "FramebufferObjectRecorded framebuffer={framebuffer} resource={resource}@{resource_generation} width={width} height={height} stride_bytes={stride_bytes} pixel_format={pixel_format} byte_len={byte_len} generation={generation}"
        ),
        EventKind::DisplayObjectRecorded {
            display,
            framebuffer,
            framebuffer_generation,
            mode_name,
            width,
            height,
            refresh_millihz,
            generation,
        } => format!(
            "DisplayObjectRecorded display={display} framebuffer={framebuffer}@{framebuffer_generation} mode_name={mode_name} width={width} height={height} refresh_millihz={refresh_millihz} generation={generation}"
        ),
        EventKind::DisplayCapabilityRecorded {
            display_capability,
            owner_store,
            owner_store_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            capability,
            capability_generation,
            handle_slot,
            handle_generation,
            handle_tag,
            operations,
            state,
            generation,
        } => format!(
            "DisplayCapabilityRecorded display_capability={display_capability} owner_store={owner_store}@{owner_store_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} capability={capability}@{capability_generation} handle_slot={handle_slot} handle_generation={handle_generation} handle_tag={handle_tag} operations={} state={} generation={generation}",
            operations.join("|"),
            state.as_str()
        ),
        EventKind::FramebufferWindowLeaseRecorded {
            framebuffer_window_lease,
            owner_store,
            owner_store_generation,
            display_capability,
            display_capability_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            x,
            y,
            width,
            height,
            byte_offset,
            byte_len,
            access,
            state,
            generation,
        } => format!(
            "FramebufferWindowLeaseRecorded framebuffer_window_lease={framebuffer_window_lease} owner_store={owner_store}@{owner_store_generation} display_capability={display_capability}@{display_capability_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} window={x},{y} {width}x{height} byte_range={byte_offset}+{byte_len} access={access} state={} generation={generation}",
            state.as_str()
        ),
        EventKind::FramebufferMappingRecorded {
            framebuffer_mapping,
            owner_store,
            owner_store_generation,
            framebuffer_window_lease,
            framebuffer_window_lease_generation,
            display_capability,
            display_capability_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            map_handle_slot,
            map_handle_generation,
            map_handle_tag,
            x,
            y,
            width,
            height,
            byte_offset,
            byte_len,
            access,
            mode,
            state,
            generation,
        } => format!(
            "FramebufferMappingRecorded framebuffer_mapping={framebuffer_mapping} owner_store={owner_store}@{owner_store_generation} framebuffer_window_lease={framebuffer_window_lease}@{framebuffer_window_lease_generation} display_capability={display_capability}@{display_capability_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} map_handle_slot={map_handle_slot} map_handle_generation={map_handle_generation} map_handle_tag={map_handle_tag} window={x},{y} {width}x{height} byte_range={byte_offset}+{byte_len} access={access} mode={mode} state={} generation={generation}",
            state.as_str()
        ),
        EventKind::FramebufferWriteRecorded {
            framebuffer_write,
            owner_store,
            owner_store_generation,
            framebuffer_mapping,
            framebuffer_mapping_generation,
            framebuffer_window_lease,
            framebuffer_window_lease_generation,
            display_capability,
            display_capability_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            map_handle_slot,
            map_handle_generation,
            map_handle_tag,
            x,
            y,
            width,
            height,
            byte_offset,
            byte_len,
            pixel_format,
            payload_digest,
            state,
            generation,
        } => format!(
            "FramebufferWriteRecorded framebuffer_write={framebuffer_write} owner_store={owner_store}@{owner_store_generation} framebuffer_mapping={framebuffer_mapping}@{framebuffer_mapping_generation} framebuffer_window_lease={framebuffer_window_lease}@{framebuffer_window_lease_generation} display_capability={display_capability}@{display_capability_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} map_handle_slot={map_handle_slot} map_handle_generation={map_handle_generation} map_handle_tag={map_handle_tag} region={x},{y} {width}x{height} byte_range={byte_offset}+{byte_len} pixel_format={pixel_format} payload_digest={payload_digest} state={} generation={generation}",
            state.as_str()
        ),
        EventKind::FramebufferFlushRegionRecorded {
            framebuffer_flush_region,
            owner_store,
            owner_store_generation,
            framebuffer_write,
            framebuffer_write_generation,
            display_capability,
            display_capability_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            x,
            y,
            width,
            height,
            byte_offset,
            byte_len,
            pixel_format,
            payload_digest,
            state,
            generation,
        } => format!(
            "FramebufferFlushRegionRecorded framebuffer_flush_region={framebuffer_flush_region} owner_store={owner_store}@{owner_store_generation} framebuffer_write={framebuffer_write}@{framebuffer_write_generation} display_capability={display_capability}@{display_capability_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} region={x},{y} {width}x{height} byte_range={byte_offset}+{byte_len} pixel_format={pixel_format} payload_digest={payload_digest} state={} generation={generation}",
            state.as_str()
        ),
        EventKind::FramebufferDirtyRegionTracked {
            framebuffer_dirty_region,
            owner_store,
            owner_store_generation,
            framebuffer_write,
            framebuffer_write_generation,
            framebuffer_flush_region,
            framebuffer_flush_region_generation,
            display_capability,
            display_capability_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            x,
            y,
            width,
            height,
            byte_offset,
            byte_len,
            pixel_format,
            payload_digest,
            state,
            generation,
        } => format!(
            "FramebufferDirtyRegionTracked framebuffer_dirty_region={framebuffer_dirty_region} owner_store={owner_store}@{owner_store_generation} framebuffer_write={framebuffer_write}@{framebuffer_write_generation} framebuffer_flush_region={}:{} display_capability={display_capability}@{display_capability_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} region={x},{y} {width}x{height} byte_range={byte_offset}+{byte_len} pixel_format={pixel_format} payload_digest={payload_digest} state={} generation={generation}",
            framebuffer_flush_region.map(|id| id.to_string()).unwrap_or_else(|| "none".to_string()),
            framebuffer_flush_region_generation
                .map(|generation| generation.to_string())
                .unwrap_or_else(|| "none".to_string()),
            state.as_str()
        ),
        EventKind::DisplayEventLogRecorded {
            display_event_log,
            owner_store,
            owner_store_generation,
            display_capability,
            display_capability_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            framebuffer_dirty_region,
            framebuffer_dirty_region_generation,
            first_event,
            last_event,
            event_count,
            flush_count,
            dirty_region_count,
            state,
            generation,
        } => format!(
            "DisplayEventLogRecorded display_event_log={display_event_log} owner_store={owner_store}@{owner_store_generation} display_capability={display_capability}@{display_capability_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} framebuffer_dirty_region={framebuffer_dirty_region}@{framebuffer_dirty_region_generation} events={first_event}..{last_event} event_count={event_count} flush_count={flush_count} dirty_region_count={dirty_region_count} state={} generation={generation}",
            state.as_str()
        ),
        EventKind::DisplayCleanupStarted {
            cleanup,
            owner_store,
            owner_store_generation,
            display_capability,
            display_capability_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            generation,
        } => format!(
            "DisplayCleanupStarted cleanup={cleanup} owner_store={owner_store}@{owner_store_generation} display_capability={display_capability}@{display_capability_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} generation={generation}"
        ),
        EventKind::DisplayCleanupCompleted {
            cleanup,
            owner_store,
            owner_store_generation,
            display_capability,
            display_capability_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            unmapped_framebuffer_mappings,
            released_framebuffer_window_leases,
            revoked_display_capabilities,
            generation,
        } => format!(
            "DisplayCleanupCompleted cleanup={cleanup} owner_store={owner_store}@{owner_store_generation} display_capability={display_capability}@{display_capability_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} unmapped_framebuffer_mappings={unmapped_framebuffer_mappings} released_framebuffer_window_leases={released_framebuffer_window_leases} revoked_display_capabilities={revoked_display_capabilities} generation={generation}"
        ),
        EventKind::DisplaySnapshotBarrierValidated {
            barrier,
            owner_store,
            owner_store_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            display_cleanup,
            display_cleanup_generation,
            active_framebuffer_window_lease_count,
            active_framebuffer_mapping_count,
            dirty_framebuffer_region_count,
            generation,
        } => format!(
            "DisplaySnapshotBarrierValidated barrier={barrier} owner_store={owner_store}@{owner_store_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} display_cleanup={}:{} active_framebuffer_window_leases={active_framebuffer_window_lease_count} active_framebuffer_mappings={active_framebuffer_mapping_count} dirty_framebuffer_regions={dirty_framebuffer_region_count} generation={generation}",
            display_cleanup.map(|id| id.to_string()).unwrap_or_else(|| "none".to_string()),
            display_cleanup_generation
                .map(|generation| generation.to_string())
                .unwrap_or_else(|| "none".to_string())
        ),
        EventKind::DisplayPanicLastFrameRecorded {
            panic_last_frame,
            owner_store,
            owner_store_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            display_snapshot_barrier,
            display_snapshot_barrier_generation,
            display_event_log,
            display_event_log_generation,
            framebuffer_write,
            framebuffer_write_generation,
            framebuffer_flush_region,
            framebuffer_flush_region_generation,
            payload_digest,
            summary_digest,
            summary_record_bytes,
            panic_epoch,
            panic_cpu,
            panic_reason_code,
            raw_framebuffer_bytes_exported,
            generation,
        } => format!(
            "DisplayPanicLastFrameRecorded panic_last_frame={panic_last_frame} owner_store={owner_store}@{owner_store_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} barrier={display_snapshot_barrier}@{display_snapshot_barrier_generation} display_event_log={display_event_log}@{display_event_log_generation} framebuffer_write={framebuffer_write}@{framebuffer_write_generation} framebuffer_flush_region={framebuffer_flush_region}@{framebuffer_flush_region_generation} payload_digest={payload_digest} summary_digest={summary_digest} summary_record_bytes={summary_record_bytes} panic_epoch={panic_epoch} panic_cpu={panic_cpu} panic_reason_code={panic_reason_code} raw_framebuffer_bytes_exported={raw_framebuffer_bytes_exported} generation={generation}"
        ),
        EventKind::FramebufferBenchmarkRecorded {
            benchmark,
            owner_store,
            owner_store_generation,
            display,
            display_generation,
            framebuffer,
            framebuffer_generation,
            display_capability,
            display_capability_generation,
            framebuffer_write,
            framebuffer_write_generation,
            framebuffer_flush_region,
            framebuffer_flush_region_generation,
            display_event_log,
            display_event_log_generation,
            display_snapshot_barrier,
            display_snapshot_barrier_generation,
            sample_frames,
            sample_bytes,
            frame_area_pixels,
            write_nanos,
            flush_nanos,
            measured_nanos,
            budget_nanos,
            throughput_bytes_per_sec,
            flushes_per_sec_milli,
            p50_latency_nanos,
            p99_latency_nanos,
            generation,
        } => format!(
            "FramebufferBenchmarkRecorded benchmark={benchmark} owner_store={owner_store}@{owner_store_generation} display={display}@{display_generation} framebuffer={framebuffer}@{framebuffer_generation} display_capability={display_capability}@{display_capability_generation} framebuffer_write={framebuffer_write}@{framebuffer_write_generation} framebuffer_flush_region={framebuffer_flush_region}@{framebuffer_flush_region_generation} display_event_log={display_event_log}@{display_event_log_generation} display_snapshot_barrier={display_snapshot_barrier}@{display_snapshot_barrier_generation} sample_frames={sample_frames} sample_bytes={sample_bytes} frame_area_pixels={frame_area_pixels} write_nanos={write_nanos} flush_nanos={flush_nanos} measured_nanos={measured_nanos} budget_nanos={budget_nanos} throughput_bytes_per_sec={throughput_bytes_per_sec} flushes_per_sec_milli={flushes_per_sec_milli} p50_latency_nanos={p50_latency_nanos} p99_latency_nanos={p99_latency_nanos} generation={generation}"
        ),
        _ => return None,
    };
    Some(summary)
}
