use alloc::{
    format,
    string::{String, ToString},
    vec::Vec,
};

use super::*;

#[derive(Clone, Debug)]
pub struct SemanticGraph {
    integrated_smp_preemption_cleanups: Vec<IntegratedSmpPreemptionCleanupRecord>,
    integrated_smp_network_faults: Vec<IntegratedSmpNetworkFaultRecord>,
    integrated_disk_preempt_faults: Vec<IntegratedDiskPreemptFaultRecord>,
    integrated_simd_migrations: Vec<IntegratedSimdMigrationRecord>,
    integrated_network_disk_ios: Vec<IntegratedNetworkDiskIoRecord>,
    integrated_display_scheduler_loads: Vec<IntegratedDisplaySchedulerLoadRecord>,
    integrated_snapshot_io_lease_barriers: Vec<IntegratedSnapshotIoLeaseBarrierRecord>,
    integrated_code_publish_smp_workloads: Vec<IntegratedCodePublishSmpWorkloadRecord>,
    integrated_display_panics: Vec<IntegratedDisplayPanicRecord>,
    integrated_osctl_trace_replays: Vec<IntegratedOsctlTraceReplayRecord>,
    device_objects: Vec<DeviceObjectRecord>,
    queue_objects: Vec<QueueObjectRecord>,
    descriptor_objects: Vec<DescriptorObjectRecord>,
    dma_buffer_objects: Vec<DmaBufferObjectRecord>,
    mmio_region_objects: Vec<MmioRegionObjectRecord>,
    irq_line_objects: Vec<IrqLineObjectRecord>,
    irq_events: Vec<IrqEventRecord>,
    device_capabilities: Vec<DeviceCapabilityRecord>,
    driver_store_bindings: Vec<DriverStoreBindingRecord>,
    packet_device_objects: Vec<PacketDeviceObjectRecord>,
    packet_buffer_objects: Vec<PacketBufferObjectRecord>,
    packet_queue_objects: Vec<PacketQueueObjectRecord>,
    packet_descriptors: Vec<PacketDescriptorObjectRecord>,
    fake_net_backends: Vec<FakeNetBackendObjectRecord>,
    virtio_net_backends: Vec<VirtioNetBackendObjectRecord>,
    network_rx_interrupts: Vec<NetworkRxInterruptRecord>,
    network_rx_wait_resolutions: Vec<NetworkRxWaitResolutionRecord>,
    network_tx_capability_gates: Vec<NetworkTxCapabilityGateRecord>,
    network_tx_completions: Vec<NetworkTxCompletionRecord>,
    network_stack_adapters: Vec<NetworkStackAdapterRecord>,
    socket_objects: Vec<SocketObjectRecord>,
    endpoint_objects: Vec<EndpointObjectRecord>,
    socket_operations: Vec<SocketOperationRecord>,
    socket_waits: Vec<SocketWaitRecord>,
    network_backpressures: Vec<NetworkBackpressureRecord>,
    network_benchmarks: Vec<NetworkBenchmarkRecord>,
    network_recovery_benchmarks: Vec<NetworkRecoveryBenchmarkRecord>,
    network_driver_cleanups: Vec<NetworkDriverCleanupRecord>,
    network_generation_audits: Vec<NetworkGenerationAuditRecord>,
    network_fault_injections: Vec<NetworkFaultInjectionRecord>,
    block_device_objects: Vec<BlockDeviceObjectRecord>,
    block_range_objects: Vec<BlockRangeObjectRecord>,
    block_request_objects: Vec<BlockRequestObjectRecord>,
    block_completion_objects: Vec<BlockCompletionObjectRecord>,
    block_waits: Vec<BlockWaitRecord>,
    fake_block_backends: Vec<FakeBlockBackendObjectRecord>,
    virtio_blk_backends: Vec<VirtioBlkBackendObjectRecord>,
    block_read_paths: Vec<BlockReadPathRecord>,
    block_write_paths: Vec<BlockWritePathRecord>,
    block_request_queues: Vec<BlockRequestQueueRecord>,
    block_dma_buffers: Vec<BlockDmaBufferRecord>,
    block_page_objects: Vec<BlockPageObjectRecord>,
    buffer_cache_objects: Vec<BufferCacheObjectRecord>,
    file_objects: Vec<FileObjectRecord>,
    directory_objects: Vec<DirectoryObjectRecord>,
    fat_adapter_objects: Vec<FatAdapterObjectRecord>,
    ext4_adapter_objects: Vec<Ext4AdapterObjectRecord>,
    file_handle_capabilities: Vec<FileHandleCapabilityRecord>,
    fs_waits: Vec<FsWaitRecord>,
    block_driver_cleanups: Vec<BlockDriverCleanupRecord>,
    block_pending_io_policies: Vec<BlockPendingIoPolicyRecord>,
    block_request_generation_audits: Vec<BlockRequestGenerationAuditRecord>,
    block_benchmarks: Vec<BlockBenchmarkRecord>,
    block_recovery_benchmarks: Vec<BlockRecoveryBenchmarkRecord>,
    command_results: Vec<CommandResult>,
    domains: SemanticDomains,
    event_log: EventLog,
    next_integrated_smp_preemption_cleanup_id: IntegratedSmpPreemptionCleanupId,
    next_integrated_smp_network_fault_id: IntegratedSmpNetworkFaultId,
    next_integrated_disk_preempt_fault_id: IntegratedDiskPreemptFaultId,
    next_integrated_simd_migration_id: IntegratedSimdMigrationId,
    next_integrated_network_disk_io_id: IntegratedNetworkDiskIoId,
    next_integrated_display_scheduler_load_id: IntegratedDisplaySchedulerLoadId,
    next_integrated_snapshot_io_lease_barrier_id: IntegratedSnapshotIoLeaseBarrierId,
    next_integrated_code_publish_smp_workload_id: IntegratedCodePublishSmpWorkloadId,
    next_integrated_display_panic_id: IntegratedDisplayPanicId,
    next_integrated_osctl_trace_replay_id: IntegratedOsctlTraceReplayId,
    next_device_object_id: DeviceObjectId,
    next_queue_object_id: QueueObjectId,
    next_descriptor_object_id: DescriptorObjectId,
    next_dma_buffer_object_id: DmaBufferObjectId,
    next_mmio_region_object_id: MmioRegionObjectId,
    next_irq_line_object_id: IrqLineObjectId,
    next_irq_event_id: IrqEventId,
    next_device_capability_id: DeviceCapabilityId,
    next_driver_store_binding_id: DriverStoreBindingId,
    next_packet_device_object_id: PacketDeviceObjectId,
    next_packet_buffer_object_id: PacketBufferObjectId,
    next_packet_queue_object_id: PacketQueueObjectId,
    next_packet_descriptor_object_id: PacketDescriptorObjectId,
    next_fake_net_backend_object_id: FakeNetBackendObjectId,
    next_virtio_net_backend_object_id: VirtioNetBackendObjectId,
    next_network_rx_interrupt_id: NetworkRxInterruptId,
    next_network_rx_wait_resolution_id: NetworkRxWaitResolutionId,
    next_network_tx_capability_gate_id: NetworkTxCapabilityGateId,
    next_network_tx_completion_id: NetworkTxCompletionId,
    next_network_stack_adapter_id: NetworkStackAdapterId,
    next_socket_object_id: SocketObjectId,
    next_endpoint_object_id: EndpointObjectId,
    next_socket_operation_id: SocketOperationId,
    next_socket_wait_id: SocketWaitId,
    next_network_backpressure_id: NetworkBackpressureId,
    next_network_benchmark_id: NetworkBenchmarkId,
    next_network_recovery_benchmark_id: NetworkRecoveryBenchmarkId,
    next_network_driver_cleanup_id: NetworkDriverCleanupId,
    next_network_generation_audit_id: NetworkGenerationAuditId,
    next_network_fault_injection_id: NetworkFaultInjectionId,
    next_block_device_object_id: BlockDeviceObjectId,
    next_block_range_object_id: BlockRangeObjectId,
    next_block_request_object_id: BlockRequestObjectId,
    next_block_completion_object_id: BlockCompletionObjectId,
    next_block_wait_id: BlockWaitId,
    next_fake_block_backend_object_id: FakeBlockBackendObjectId,
    next_virtio_blk_backend_object_id: VirtioBlkBackendObjectId,
    next_block_read_path_id: BlockReadPathId,
    next_block_write_path_id: BlockWritePathId,
    next_block_request_queue_id: BlockRequestQueueId,
    next_block_dma_buffer_id: BlockDmaBufferId,
    next_block_page_object_id: BlockPageObjectId,
    next_buffer_cache_object_id: BufferCacheObjectId,
    next_file_object_id: FileObjectId,
    next_directory_object_id: DirectoryObjectId,
    next_fat_adapter_object_id: FatAdapterObjectId,
    next_ext4_adapter_object_id: Ext4AdapterObjectId,
    next_file_handle_capability_id: FileHandleCapabilityId,
    next_fs_wait_id: FsWaitId,
    next_block_driver_cleanup_id: BlockDriverCleanupId,
    next_block_pending_io_policy_id: BlockPendingIoPolicyId,
    next_block_request_generation_audit_id: BlockRequestGenerationAuditId,
    next_block_benchmark_id: BlockBenchmarkId,
    next_block_recovery_benchmark_id: BlockRecoveryBenchmarkId,
}

mod activation_migration;
mod authority;
mod block_benchmark;
mod block_completion_object;
mod block_device_object;
mod block_dma_buffer;
mod block_driver_cleanup;
mod block_page_object;
mod block_pending_io_policy;
mod block_range_object;
mod block_read_path;
mod block_recovery_benchmark;
mod block_request_generation_audit;
mod block_request_object;
mod block_request_queue;
mod block_wait;
mod block_write_path;
mod boundary;
mod buffer_cache_object;
mod capability;
mod cleanup;
mod command;
mod context;
mod cross_scheduler;
mod descriptor_object;
mod device_capability;
mod device_object;
mod directory_object;
mod display_capability;
mod display_cleanup;
mod display_event_log;
mod display_object;
mod display_panic_last_frame;
mod display_snapshot_barrier;
mod dma_buffer_object;
mod domains;
mod driver_store_binding;
mod endpoint_object;
mod ext4_adapter_object;
mod fake_block_backend_object;
mod fake_net_backend_object;
mod fat_adapter_object;
mod file_handle_capability;
mod file_object;
mod framebuffer_benchmark;
mod framebuffer_dirty_region;
mod framebuffer_flush_region;
mod framebuffer_mapping;
mod framebuffer_object;
mod framebuffer_window_lease;
mod framebuffer_write;
mod fs_wait;
mod hart;
mod hart_event;
mod integrated_code_publish_smp_workload;
mod integrated_disk_preempt_fault;
mod integrated_display_panic;
mod integrated_display_scheduler_load;
mod integrated_network_disk_io;
mod integrated_osctl_trace_replay;
mod integrated_simd_migration;
mod integrated_smp_network_fault;
mod integrated_smp_preemption_cleanup;
mod integrated_snapshot_io_lease_barrier;
mod interface;
mod io_cleanup;
mod io_fault_injection;
mod io_validator;
mod io_wait;
mod ipi;
mod irq_event;
mod irq_line_object;
mod latency;
mod mmio_region_object;
mod network;
mod network_backpressure;
mod network_benchmark;
mod network_driver_cleanup;
mod network_fault_injection;
mod network_generation_audit;
mod network_recovery_benchmark;
mod network_rx_interrupt;
mod network_rx_wait;
mod network_stack_adapter;
mod network_tx_completion;
mod network_tx_gate;
mod packet_buffer_object;
mod packet_descriptor_object;
mod packet_device_object;
mod packet_queue_object;
mod query;
mod queue_object;
mod remote;
mod remote_park;
mod resource;
mod scheduler;
mod simd_benchmark;
mod simd_context_switch_benchmark;
mod simd_fault_injection;
mod smp_cleanup_quiescence;
mod smp_code_publish;
mod smp_safe_point;
mod smp_scaling;
mod smp_snapshot_barrier;
mod smp_stress;
mod snapshot;
mod socket_object;
mod socket_operation;
mod socket_wait;
mod stop_the_world;
mod store;
mod substrate;
mod target_feature_set;
mod task;
mod timer;
mod transaction;
mod vector_state;
mod virtio_blk_backend_object;
mod virtio_net_backend_object;
mod wait;

pub use command::*;
use domains::SemanticDomains;

impl SemanticGraph {
    pub fn new() -> Self {
        Self::with_runtime_mode(RuntimeMode::Research)
    }
    pub fn with_runtime_mode(runtime_mode: RuntimeMode) -> Self {
        Self {
            integrated_smp_preemption_cleanups: Vec::new(),
            integrated_smp_network_faults: Vec::new(),
            integrated_disk_preempt_faults: Vec::new(),
            integrated_simd_migrations: Vec::new(),
            integrated_network_disk_ios: Vec::new(),
            integrated_display_scheduler_loads: Vec::new(),
            integrated_snapshot_io_lease_barriers: Vec::new(),
            integrated_code_publish_smp_workloads: Vec::new(),
            integrated_display_panics: Vec::new(),
            integrated_osctl_trace_replays: Vec::new(),
            device_objects: Vec::new(),
            queue_objects: Vec::new(),
            descriptor_objects: Vec::new(),
            dma_buffer_objects: Vec::new(),
            mmio_region_objects: Vec::new(),
            irq_line_objects: Vec::new(),
            irq_events: Vec::new(),
            device_capabilities: Vec::new(),
            driver_store_bindings: Vec::new(),
            packet_device_objects: Vec::new(),
            packet_buffer_objects: Vec::new(),
            packet_queue_objects: Vec::new(),
            packet_descriptors: Vec::new(),
            fake_net_backends: Vec::new(),
            virtio_net_backends: Vec::new(),
            network_rx_interrupts: Vec::new(),
            network_rx_wait_resolutions: Vec::new(),
            network_tx_capability_gates: Vec::new(),
            network_tx_completions: Vec::new(),
            network_stack_adapters: Vec::new(),
            socket_objects: Vec::new(),
            endpoint_objects: Vec::new(),
            socket_operations: Vec::new(),
            socket_waits: Vec::new(),
            network_backpressures: Vec::new(),
            network_benchmarks: Vec::new(),
            network_recovery_benchmarks: Vec::new(),
            network_driver_cleanups: Vec::new(),
            network_generation_audits: Vec::new(),
            network_fault_injections: Vec::new(),
            block_device_objects: Vec::new(),
            block_range_objects: Vec::new(),
            block_request_objects: Vec::new(),
            block_completion_objects: Vec::new(),
            block_waits: Vec::new(),
            fake_block_backends: Vec::new(),
            virtio_blk_backends: Vec::new(),
            block_read_paths: Vec::new(),
            block_write_paths: Vec::new(),
            block_request_queues: Vec::new(),
            block_dma_buffers: Vec::new(),
            block_page_objects: Vec::new(),
            buffer_cache_objects: Vec::new(),
            file_objects: Vec::new(),
            directory_objects: Vec::new(),
            fat_adapter_objects: Vec::new(),
            ext4_adapter_objects: Vec::new(),
            file_handle_capabilities: Vec::new(),
            fs_waits: Vec::new(),
            block_driver_cleanups: Vec::new(),
            block_pending_io_policies: Vec::new(),
            block_request_generation_audits: Vec::new(),
            block_benchmarks: Vec::new(),
            block_recovery_benchmarks: Vec::new(),
            command_results: Vec::new(),
            domains: SemanticDomains::new(),
            event_log: EventLog::with_runtime_mode(runtime_mode),
            next_integrated_smp_preemption_cleanup_id: 1,
            next_integrated_smp_network_fault_id: 1,
            next_integrated_disk_preempt_fault_id: 1,
            next_integrated_simd_migration_id: 1,
            next_integrated_network_disk_io_id: 1,
            next_integrated_display_scheduler_load_id: 1,
            next_integrated_snapshot_io_lease_barrier_id: 1,
            next_integrated_code_publish_smp_workload_id: 1,
            next_integrated_display_panic_id: 1,
            next_integrated_osctl_trace_replay_id: 1,
            next_device_object_id: 1,
            next_queue_object_id: 1,
            next_descriptor_object_id: 1,
            next_dma_buffer_object_id: 1,
            next_mmio_region_object_id: 1,
            next_irq_line_object_id: 1,
            next_irq_event_id: 1,
            next_device_capability_id: 1,
            next_driver_store_binding_id: 1,
            next_packet_device_object_id: 1,
            next_packet_buffer_object_id: 1,
            next_packet_queue_object_id: 1,
            next_packet_descriptor_object_id: 1,
            next_fake_net_backend_object_id: 1,
            next_virtio_net_backend_object_id: 1,
            next_network_rx_interrupt_id: 1,
            next_network_rx_wait_resolution_id: 1,
            next_network_tx_capability_gate_id: 1,
            next_network_tx_completion_id: 1,
            next_network_stack_adapter_id: 1,
            next_socket_object_id: 1,
            next_endpoint_object_id: 1,
            next_socket_operation_id: 1,
            next_socket_wait_id: 1,
            next_network_backpressure_id: 1,
            next_network_benchmark_id: 1,
            next_network_recovery_benchmark_id: 1,
            next_network_driver_cleanup_id: 1,
            next_network_generation_audit_id: 1,
            next_network_fault_injection_id: 1,
            next_block_device_object_id: 1,
            next_block_range_object_id: 1,
            next_block_request_object_id: 1,
            next_block_completion_object_id: 1,
            next_block_wait_id: 1,
            next_fake_block_backend_object_id: 1,
            next_virtio_blk_backend_object_id: 1,
            next_block_read_path_id: 1,
            next_block_write_path_id: 1,
            next_block_request_queue_id: 1,
            next_block_dma_buffer_id: 1,
            next_block_page_object_id: 1,
            next_buffer_cache_object_id: 1,
            next_file_object_id: 1,
            next_directory_object_id: 1,
            next_fat_adapter_object_id: 1,
            next_ext4_adapter_object_id: 1,
            next_file_handle_capability_id: 1,
            next_fs_wait_id: 1,
            next_block_driver_cleanup_id: 1,
            next_block_pending_io_policy_id: 1,
            next_block_request_generation_audit_id: 1,
            next_block_benchmark_id: 1,
            next_block_recovery_benchmark_id: 1,
        }
    }
    pub fn runtime_mode(&self) -> RuntimeMode {
        self.event_log.runtime_mode()
    }
}

impl Default for SemanticGraph {
    fn default() -> Self {
        Self::new()
    }
}
