use super::{super::super::*, *};

pub(crate) fn integrated_smp_preemption_cleanup_manifest(
    record: &semantic_core::IntegratedSmpPreemptionCleanupRecord,
) -> IntegratedSmpPreemptionCleanupManifest {
    IntegratedSmpPreemptionCleanupManifest {
        id: record.id,
        scenario: record.scenario.clone(),
        stress_run: record.stress_run,
        stress_run_generation: record.stress_run_generation,
        preemption: record.preemption,
        preemption_generation: record.preemption_generation,
        timer_interrupt: record.timer_interrupt,
        timer_interrupt_generation: record.timer_interrupt_generation,
        saved_context: record.saved_context,
        saved_context_generation: record.saved_context_generation,
        remote_preempt: record.remote_preempt,
        remote_preempt_generation: record.remote_preempt_generation,
        activation_cleanup: record.activation_cleanup,
        activation_cleanup_generation: record.activation_cleanup_generation,
        smp_cleanup_quiescence: record.smp_cleanup_quiescence,
        smp_cleanup_quiescence_generation: record.smp_cleanup_quiescence_generation,
        cleanup_store: record.cleanup_store,
        target_store_generation: record.target_store_generation,
        result_store_generation: record.result_store_generation,
        cleanup_activation: record.cleanup_activation,
        cleanup_activation_generation_after: record.cleanup_activation_generation_after,
        hart_count: record.hart_count,
        invariant_checks: record.invariant_checks,
        generation: record.generation,
        state: record.state.as_str().to_owned(),
        recorded_at_event: record.recorded_at_event,
        note: record.note.clone(),
    }
}

pub(crate) fn integrated_smp_network_fault_manifest(
    record: &semantic_core::IntegratedSmpNetworkFaultRecord,
) -> IntegratedSmpNetworkFaultManifest {
    IntegratedSmpNetworkFaultManifest {
        id: record.id,
        scenario: record.scenario.clone(),
        network_driver_cleanup: record.network_driver_cleanup,
        network_driver_cleanup_generation: record.network_driver_cleanup_generation,
        smp_stress_run: record.smp_stress_run,
        smp_stress_run_generation: record.smp_stress_run_generation,
        remote_preempt: record.remote_preempt,
        remote_preempt_generation: record.remote_preempt_generation,
        smp_cleanup_quiescence: record.smp_cleanup_quiescence,
        smp_cleanup_quiescence_generation: record.smp_cleanup_quiescence_generation,
        driver_store: record.driver_store,
        driver_store_generation: record.driver_store_generation,
        packet_device: record.packet_device,
        packet_device_generation: record.packet_device_generation,
        adapter: record.adapter,
        adapter_generation: record.adapter_generation,
        backend: contract_object_ref_manifest(record.backend),
        io_cleanup: record.io_cleanup,
        io_cleanup_generation: record.io_cleanup_generation,
        cancelled_socket_wait_count: record.cancelled_socket_wait_count,
        cancelled_wait_token_count: record.cancelled_wait_token_count,
        revoked_packet_capability_count: record.revoked_packet_capability_count,
        hart_count: record.hart_count,
        invariant_checks: record.invariant_checks,
        generation: record.generation,
        state: record.state.as_str().to_owned(),
        recorded_at_event: record.recorded_at_event,
        note: record.note.clone(),
    }
}

pub(crate) fn integrated_disk_preempt_fault_manifest(
    record: &semantic_core::IntegratedDiskPreemptFaultRecord,
) -> IntegratedDiskPreemptFaultManifest {
    IntegratedDiskPreemptFaultManifest {
        id: record.id,
        scenario: record.scenario.clone(),
        preemption: record.preemption,
        preemption_generation: record.preemption_generation,
        timer_interrupt: record.timer_interrupt,
        timer_interrupt_generation: record.timer_interrupt_generation,
        block_pending_io_policy: record.block_pending_io_policy,
        block_pending_io_policy_generation: record.block_pending_io_policy_generation,
        block_wait: record.block_wait,
        block_wait_generation: record.block_wait_generation,
        wait: record.wait,
        wait_generation: record.wait_generation,
        block_request: record.block_request,
        block_request_generation: record.block_request_generation,
        retry_request: record.retry_request,
        retry_request_generation: record.retry_request_generation,
        block_device: record.block_device,
        block_device_generation: record.block_device_generation,
        block_range: record.block_range,
        block_range_generation: record.block_range_generation,
        driver_store: record.driver_store,
        driver_store_generation: record.driver_store_generation,
        action: record.action.as_str().to_owned(),
        errno: record.errno,
        preempted_activation: record.preempted_activation,
        preempted_activation_generation_after: record.preempted_activation_generation_after,
        invariant_checks: record.invariant_checks,
        generation: record.generation,
        state: record.state.as_str().to_owned(),
        recorded_at_event: record.recorded_at_event,
        note: record.note.clone(),
    }
}

pub(crate) fn integrated_simd_migration_manifest(
    record: &semantic_core::IntegratedSimdMigrationRecord,
) -> IntegratedSimdMigrationManifest {
    IntegratedSimdMigrationManifest {
        id: record.id,
        scenario: record.scenario.clone(),
        activation_migration: record.activation_migration,
        activation_migration_generation: record.activation_migration_generation,
        target_feature_set: record.target_feature_set,
        target_feature_set_generation: record.target_feature_set_generation,
        source_vector_state: contract_object_ref_manifest(record.source_vector_state),
        migrated_vector_state: contract_object_ref_manifest(record.migrated_vector_state),
        activation: record.activation,
        activation_generation_before: record.activation_generation_before,
        activation_generation_after: record.activation_generation_after,
        context: record.context,
        context_generation_after: record.context_generation_after,
        source_hart: u64::from(record.source_hart),
        source_hart_generation: record.source_hart_generation,
        target_hart: u64::from(record.target_hart),
        target_hart_generation: record.target_hart_generation,
        source_queue: record.source_queue,
        source_queue_generation: record.source_queue_generation,
        target_queue: record.target_queue,
        target_queue_generation: record.target_queue_generation,
        simd_abi: record.simd_abi.clone(),
        vector_register_count: record.vector_register_count,
        vector_register_bits: record.vector_register_bits,
        invariant_checks: record.invariant_checks,
        generation: record.generation,
        state: record.state.as_str().to_owned(),
        recorded_at_event: record.recorded_at_event,
        note: record.note.clone(),
    }
}

pub(crate) fn integrated_network_disk_io_manifest(
    record: &semantic_core::IntegratedNetworkDiskIoRecord,
) -> IntegratedNetworkDiskIoManifest {
    IntegratedNetworkDiskIoManifest {
        id: record.id,
        scenario: record.scenario.clone(),
        network_benchmark: record.network_benchmark,
        network_benchmark_generation: record.network_benchmark_generation,
        block_benchmark: record.block_benchmark,
        block_benchmark_generation: record.block_benchmark_generation,
        network_owner_store: record.network_owner_store,
        network_owner_store_generation: record.network_owner_store_generation,
        network_adapter: record.network_adapter,
        network_adapter_generation: record.network_adapter_generation,
        packet_device: record.packet_device,
        packet_device_generation: record.packet_device_generation,
        socket: record.socket,
        socket_generation: record.socket_generation,
        block_backend: contract_object_ref_manifest(record.block_backend),
        block_device: record.block_device,
        block_device_generation: record.block_device_generation,
        block_request_queue: record.block_request_queue,
        block_request_queue_generation: record.block_request_queue_generation,
        block_dma_buffer: record.block_dma_buffer,
        block_dma_buffer_generation: record.block_dma_buffer_generation,
        network_sample_bytes: record.network_sample_bytes,
        block_sample_bytes: record.block_sample_bytes,
        network_sample_packets: record.network_sample_packets,
        block_sample_requests: record.block_sample_requests,
        concurrent_window_nanos: record.concurrent_window_nanos,
        combined_throughput_bytes_per_sec: record.combined_throughput_bytes_per_sec,
        max_p99_latency_nanos: record.max_p99_latency_nanos,
        invariant_checks: record.invariant_checks,
        generation: record.generation,
        state: record.state.as_str().to_owned(),
        recorded_at_event: record.recorded_at_event,
        note: record.note.clone(),
    }
}

pub(crate) fn integrated_display_scheduler_load_manifest(
    record: &semantic_core::IntegratedDisplaySchedulerLoadRecord,
) -> IntegratedDisplaySchedulerLoadManifest {
    IntegratedDisplaySchedulerLoadManifest {
        id: record.id,
        scenario: record.scenario.clone(),
        framebuffer_benchmark: record.framebuffer_benchmark,
        framebuffer_benchmark_generation: record.framebuffer_benchmark_generation,
        scheduler_decision: record.scheduler_decision,
        scheduler_decision_generation: record.scheduler_decision_generation,
        owner_store: record.owner_store,
        owner_store_generation: record.owner_store_generation,
        owner_task: u64::from(record.owner_task),
        owner_task_generation: record.owner_task_generation,
        queue: record.queue,
        queue_generation: record.queue_generation,
        selected_activation: record.selected_activation,
        selected_activation_generation: record.selected_activation_generation,
        display: record.display,
        display_generation: record.display_generation,
        framebuffer: record.framebuffer,
        framebuffer_generation: record.framebuffer_generation,
        display_capability: record.display_capability,
        display_capability_generation: record.display_capability_generation,
        framebuffer_write: record.framebuffer_write,
        framebuffer_write_generation: record.framebuffer_write_generation,
        framebuffer_flush_region: record.framebuffer_flush_region,
        framebuffer_flush_region_generation: record.framebuffer_flush_region_generation,
        display_event_log: record.display_event_log,
        display_event_log_generation: record.display_event_log_generation,
        sample_frames: record.sample_frames,
        sample_bytes: record.sample_bytes,
        scheduler_load_units: record.scheduler_load_units,
        display_measured_nanos: record.display_measured_nanos,
        scheduler_decided_at_event: record.scheduler_decided_at_event,
        display_recorded_at_event: record.display_recorded_at_event,
        invariant_checks: record.invariant_checks,
        generation: record.generation,
        state: record.state.as_str().to_owned(),
        recorded_at_event: record.recorded_at_event,
        note: record.note.clone(),
    }
}

pub(crate) fn integrated_snapshot_io_lease_barrier_manifest(
    record: &semantic_core::IntegratedSnapshotIoLeaseBarrierRecord,
) -> IntegratedSnapshotIoLeaseBarrierManifest {
    IntegratedSnapshotIoLeaseBarrierManifest {
        id: record.id,
        scenario: record.scenario.clone(),
        smp_snapshot_barrier: record.smp_snapshot_barrier,
        smp_snapshot_barrier_generation: record.smp_snapshot_barrier_generation,
        io_cleanup: record.io_cleanup,
        io_cleanup_generation: record.io_cleanup_generation,
        display_snapshot_barrier: record.display_snapshot_barrier,
        display_snapshot_barrier_generation: record.display_snapshot_barrier_generation,
        driver_store: record.driver_store,
        driver_store_generation: record.driver_store_generation,
        device: record.device,
        device_generation: record.device_generation,
        display: record.display,
        display_generation: record.display_generation,
        framebuffer: record.framebuffer,
        framebuffer_generation: record.framebuffer_generation,
        active_dmw_lease_count: record.active_dmw_lease_count,
        in_flight_dma_count: record.in_flight_dma_count,
        raw_dma_binding_count: record.raw_dma_binding_count,
        raw_mmio_binding_count: record.raw_mmio_binding_count,
        active_framebuffer_window_lease_count: record.active_framebuffer_window_lease_count,
        active_framebuffer_mapping_count: record.active_framebuffer_mapping_count,
        dirty_framebuffer_region_count: record.dirty_framebuffer_region_count,
        released_dma_buffers: record.released_dma_buffers,
        released_mmio_regions: record.released_mmio_regions,
        released_irq_lines: record.released_irq_lines,
        released_framebuffer_window_leases: record.released_framebuffer_window_leases,
        revoked_device_capabilities: record.revoked_device_capabilities,
        revoked_display_capabilities: record.revoked_display_capabilities,
        smp_barrier_event: record.smp_barrier_event,
        io_cleanup_completed_event: record.io_cleanup_completed_event,
        display_barrier_event: record.display_barrier_event,
        invariant_checks: record.invariant_checks,
        generation: record.generation,
        state: record.state.as_str().to_owned(),
        recorded_at_event: record.recorded_at_event,
        note: record.note.clone(),
    }
}

pub(crate) fn integrated_code_publish_smp_workload_manifest(
    record: &semantic_core::IntegratedCodePublishSmpWorkloadRecord,
) -> IntegratedCodePublishSmpWorkloadManifest {
    IntegratedCodePublishSmpWorkloadManifest {
        id: record.id,
        scenario: record.scenario.clone(),
        smp_stress_run: record.smp_stress_run,
        smp_stress_run_generation: record.smp_stress_run_generation,
        smp_code_publish_barrier: record.smp_code_publish_barrier,
        smp_code_publish_barrier_generation: record.smp_code_publish_barrier_generation,
        publish_rendezvous: record.publish_rendezvous,
        publish_rendezvous_generation: record.publish_rendezvous_generation,
        publish_safe_point: record.publish_safe_point,
        publish_safe_point_generation: record.publish_safe_point_generation,
        hart_count: record.hart_count,
        workload_iterations: record.workload_iterations,
        observed_safe_point_count: record.observed_safe_point_count,
        observed_rendezvous_count: record.observed_rendezvous_count,
        observed_code_publish_barrier_count: record.observed_code_publish_barrier_count,
        code_publish_epoch_before: record.code_publish_epoch_before,
        code_publish_epoch_after: record.code_publish_epoch_after,
        remote_icache_sync_required: record.remote_icache_sync_required,
        code_publish_executed: record.code_publish_executed,
        participant_count: record.participant_count,
        stress_event_log_cursor: record.stress_event_log_cursor,
        barrier_event: record.barrier_event,
        stress_recorded_at_event: record.stress_recorded_at_event,
        invariant_checks: record.invariant_checks,
        generation: record.generation,
        state: record.state.as_str().to_owned(),
        recorded_at_event: record.recorded_at_event,
        note: record.note.clone(),
    }
}

pub(crate) fn integrated_display_panic_manifest(
    record: &semantic_core::IntegratedDisplayPanicRecord,
) -> IntegratedDisplayPanicManifest {
    IntegratedDisplayPanicManifest {
        id: record.id,
        scenario: record.scenario.clone(),
        substrate_panic_event: record.substrate_panic_event,
        substrate_panic_epoch: record.substrate_panic_epoch,
        substrate_panic_cpu: record.substrate_panic_cpu,
        substrate_panic_reason_code: record.substrate_panic_reason_code,
        display_panic_last_frame: record.display_panic_last_frame,
        display_panic_last_frame_generation: record.display_panic_last_frame_generation,
        panic_ring_bytes: record.panic_ring_bytes,
        panic_record_max_bytes: record.panic_record_max_bytes,
        panic_ring_oldest_seq: record.panic_ring_oldest_seq,
        panic_ring_newest_seq: record.panic_ring_newest_seq,
        panic_ring_record_count: record.panic_ring_record_count,
        panic_ring_lost_count: record.panic_ring_lost_count,
        jsonl_frame_count: record.jsonl_frame_count,
        contract_panic_summary_records: record.contract_panic_summary_records,
        last_frame_summary_records: record.last_frame_summary_records,
        corrupt_record_count: record.corrupt_record_count,
        truncated_record_count: record.truncated_record_count,
        summary_record_bytes: record.summary_record_bytes,
        raw_framebuffer_bytes_exported: record.raw_framebuffer_bytes_exported,
        panic_path_allocates: record.panic_path_allocates,
        invariant_checks: record.invariant_checks,
        generation: record.generation,
        state: record.state.as_str().to_owned(),
        recorded_at_event: record.recorded_at_event,
        note: record.note.clone(),
    }
}

pub(crate) fn integrated_osctl_trace_replay_manifest(
    record: &semantic_core::IntegratedOsctlTraceReplayRecord,
) -> IntegratedOsctlTraceReplayManifest {
    IntegratedOsctlTraceReplayManifest {
        id: record.id,
        scenario: record.scenario.clone(),
        integrated_smp_preemption_cleanup: record.integrated_smp_preemption_cleanup,
        integrated_smp_preemption_cleanup_generation: record
            .integrated_smp_preemption_cleanup_generation,
        integrated_smp_network_fault: record.integrated_smp_network_fault,
        integrated_smp_network_fault_generation: record.integrated_smp_network_fault_generation,
        integrated_disk_preempt_fault: record.integrated_disk_preempt_fault,
        integrated_disk_preempt_fault_generation: record.integrated_disk_preempt_fault_generation,
        integrated_simd_migration: record.integrated_simd_migration,
        integrated_simd_migration_generation: record.integrated_simd_migration_generation,
        integrated_network_disk_io: record.integrated_network_disk_io,
        integrated_network_disk_io_generation: record.integrated_network_disk_io_generation,
        integrated_display_scheduler_load: record.integrated_display_scheduler_load,
        integrated_display_scheduler_load_generation: record
            .integrated_display_scheduler_load_generation,
        integrated_snapshot_io_lease_barrier: record.integrated_snapshot_io_lease_barrier,
        integrated_snapshot_io_lease_barrier_generation: record
            .integrated_snapshot_io_lease_barrier_generation,
        integrated_code_publish_smp_workload: record.integrated_code_publish_smp_workload,
        integrated_code_publish_smp_workload_generation: record
            .integrated_code_publish_smp_workload_generation,
        integrated_display_panic: record.integrated_display_panic,
        integrated_display_panic_generation: record.integrated_display_panic_generation,
        replay_event_cursor: record.replay_event_cursor,
        stable_view_count: record.stable_view_count,
        historical_edge_count: record.historical_edge_count,
        replayed_root_count: record.replayed_root_count,
        integrated_scenario_count: record.integrated_scenario_count,
        replay_fixture_count: record.replay_fixture_count,
        contract_validation_ok: record.contract_validation_ok,
        replay_validation_ok: record.replay_validation_ok,
        graph_history_ok: record.graph_history_ok,
        roots_match_counts: record.roots_match_counts,
        invariant_checks: record.invariant_checks,
        generation: record.generation,
        state: record.state.as_str().to_owned(),
        recorded_at_event: record.recorded_at_event,
        note: record.note.clone(),
    }
}
